/* auto-generated by honey — do not edit */

import type { ClientConfig, ClientError } from "honey/client"

type SDKResult<T> =
	| { data: T; error: null; response: Response; status: number }
	| { data: null; error: ClientError; response: Response; status: number }
import { createSDK as _createSDK } from "honey/client/sdk"
import type { TypedWebSocket } from "honey/client"

export const serviceMap = {
	input: {
		createForm: { method: "POST", path: "/in/form" },
		createJson: { method: "POST", path: "/in/json" },
		none: { method: "GET", path: "/in/none" },
		search: { method: "GET", path: "/in/search" },
	},
	resources: {
		create: { method: "POST", path: "/methods/resource" },
		delete: { method: "DELETE", path: "/methods/resource/{id}", params: ["id"] },
		list: { method: "GET", path: "/methods/resource" },
		patch: { method: "PATCH", path: "/methods/resource/{id}", params: ["id"] },
		update: { method: "PUT", path: "/methods/resource/{id}", params: ["id"] },
	},
	ws: {
		chat: { method: "GET", path: "/ws/chat/{channelId}", params: ["channelId"], ws: true },
		echo: { method: "GET", path: "/ws/echo", ws: true },
		joinRoom: { method: "GET", path: "/ws/room", ws: true },
		reconnect: { method: "GET", path: "/ws/reconnect", ws: true },
	},
} as const

export interface Demo2SDK {
	input: {
		createForm(input: {
			form: { password: string; username: string }
		}): Promise<SDKResult<{ token: string }>>
		createJson(input: { json: { email: string; name: string } }): Promise<SDKResult<{ id: string }>>
		none(): Promise<SDKResult<{ ping: "pong" }>>
		search(input: {
			search: { limit: number; page: number; q?: string }
		}): Promise<SDKResult<{ results: string[] }>>
	}
	resources: {
		create(input: { json: { name: string } }): Promise<SDKResult<{ id: string }>>
		delete(input: { params: { id: string } }): Promise<SDKResult<void>>
		list(): Promise<SDKResult<{ items: string[] }>>
		patch(input: {
			params: { id: string }
			json: { name?: string }
		}): Promise<SDKResult<{ id: string }>>
		update(input: {
			params: { id: string }
			json: { name: string }
		}): Promise<SDKResult<{ id: string; name: string }>>
	}
	ws: {
		chat(input: { params: { channelId: string } }): TypedWebSocket
		echo(): TypedWebSocket
		joinRoom(input: { search: { roomId: string } }): TypedWebSocket
		reconnect(): TypedWebSocket
	}
}

export function createDemo2SDK(config: ClientConfig): Demo2SDK {
	return _createSDK<Demo2SDK>(serviceMap, config)
}
