_generated: honey checksum:b8b90f648dbb
info:
  description: null
  title: Honey Gateway
  version: "0.0.1"
openapi: "3.1.0"
paths:
  /articles:
    get:
      summary: List articles
      x-permissions:
        - articles.read
      x-tenant:
        param: project_id
      x-entity: article
      x-generated:
        - id
        - created_at
      x-identity: id
      x-immutable:
        - id
      x-soft-delete: deleted_at
      x-query:
        filter:
          - title
        maxLimit: 100
        select:
          - id
          - title
        sort:
          - title
      parameters:
        - in: query
          name: cursor
          required: false
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListArticlesResponse200"
          description: ok
  /articles/meta:
    get:
      x-tenant:
        param: project_id
      responses:
        "200":
          description: Success
  /ping:
    get:
      responses:
        "200":
          description: Success
components:
  schemas:
    ListArticlesResponse200:
      type: object
      properties:
        articles:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              title:
                type: string
            required:
              - id
              - title
            additionalProperties: false
            x-comb:
              generated:
                - id
                - created_at
              identity: id
              immutable:
                - id
              kind: entity
              name: article
              softDelete: deleted_at
              tenantColumn: null
              v: 1
        count:
          type: number
        hasMore:
          type: boolean
        nextCursor:
          oneOf:
            - type: string
            - type: "null"
      required:
        - articles
        - count
        - hasMore
        - nextCursor
      additionalProperties: false
