/* @generated by honey — do not edit. checksum: 500a0841ec97 */
import type { TreeNode, RouteHandler, RouteTree } from "@lovrozagar/honey/tree"

const E = Object.create(null) as Record<string, TreeNode>
function N(s: Record<string, TreeNode>, m: Record<string, RouteHandler> | null = null, d: TreeNode["d"] = null, w: { n: string; m: Record<string, RouteHandler> } | null = null): TreeNode {
	return { s, d, w: w as TreeNode["w"], m: m as TreeNode["m"], ws: null }
}
function S(o: Record<string, TreeNode>): Record<string, TreeNode> {
	return Object.assign(Object.create(null), o) as Record<string, TreeNode>
}
const FN = null as unknown as RouteHandler["fn"]

const P0 = "GET /ping"
const T0 = "project_id"
const P1 = "GET /articles"
const P2 = "GET /articles/meta"
const P3 = "GET /openapi.json"
const P4 = "GET /openapi.yml"
const P5 = "GET /openapi.yaml"
const P6 = "GET /docs"
const P7 = "GET /manifest.json"
const J0 = {"type":"string"}
const A0 = ["title"]
const A1 = ["id","title"]
const M1 = {"tenant":T0} as unknown as MetaShape
const M0 = {"tenant":T0,"permissions":["articles.read"],"summary":"List articles","worker":"origin"} as unknown as MetaShape
const I0 = {"search":{"type":"object","properties":{"cursor":J0},"x-comb":{"defaultOrder":"created_at.desc","filterable":A0,"grammar":"postgrest","kind":"query","maxLimit":100,"searchable":null,"selectable":A1,"sortable":A0,"stableTiebreak":"id","v":1}}} as unknown as RouteHandler["iv"]
const O0 = {"application/json":{"ok":{"type":"object","properties":{"articles":{"type":"array","items":{"type":"object","properties":{"id":J0,"title":J0},"required":A1,"additionalProperties":false,"x-comb":{"generated":["id","created_at"],"identity":"id","immutable":["id"],"kind":"entity","name":"article","softDelete":"deleted_at","tenantColumn":null,"v":1}}},"count":{"type":"number"},"hasMore":{"type":"boolean"},"nextCursor":{"oneOf":[J0,{"type":"null"}]}},"required":["articles","count","hasMore","nextCursor"],"additionalProperties":false}}} as unknown as RouteHandler["os"]

const H0: RouteHandler = { bek: null, ef: null, fn: FN, mw: [], ek: new Set(), iv: null, os: null, mt: null, ov: null, rp: "" }
const H1: RouteHandler = { bek: null, ef: null, fn: FN, mw: [], ek: new Set(), iv: I0, os: O0, mt: M0, ov: null, rp: "" }
const H2: RouteHandler = { bek: null, ef: null, fn: FN, mw: [], ek: new Set(), iv: null, os: null, mt: M1, ov: null, rp: "" }
const H3: RouteHandler = { bek: null, ef: null, fn: FN, mw: [], ek: new Set(), iv: null, os: null, mt: null, ov: null, rp: "" }
const H4: RouteHandler = { bek: null, ef: null, fn: FN, mw: [], ek: new Set(), iv: null, os: null, mt: null, ov: null, rp: "" }
const H5: RouteHandler = { bek: null, ef: null, fn: FN, mw: [], ek: new Set(), iv: null, os: null, mt: null, ov: null, rp: "" }
const H6: RouteHandler = { bek: null, ef: null, fn: FN, mw: [], ek: new Set(), iv: null, os: null, mt: null, ov: null, rp: "" }
const H7: RouteHandler = { bek: null, ef: null, fn: FN, mw: [], ek: new Set(), iv: null, os: null, mt: null, ov: null, rp: "" }

export const tree: TreeNode = N(S({ "ping": N(E, { GET: H0 }), "articles": N(S({ "meta": N(E, { GET: H2 }) }), { GET: H1 }), "openapi.json": N(E, { GET: H3 }), "openapi.yml": N(E, { GET: H4 }), "openapi.yaml": N(E, { GET: H5 }), "docs": N(E, { GET: H6 }), "manifest.json": N(E, { GET: H7 }) }))

export const handlers: Record<string, RouteHandler> = {
	[P0]: H0,
	[P1]: H1,
	[P2]: H2,
	[P3]: H3,
	[P4]: H4,
	[P5]: H5,
	[P6]: H6,
	[P7]: H7
}

export type MetaShape = {
	permissions?: ["articles.read"]
	summary?: "List articles"
	tenant: "project_id"
	worker?: "origin"
} & Record<string, unknown>


export type RouteSelector = typeof P1 | typeof P2 | typeof P0
export const meta: Record<string, MetaShape> = {
	[P1]: M0,
	[P2]: M1
}
export const routeTree: RouteTree = { root: tree, meta, handlers }
