/* @generated by honey — do not edit. checksum: 8386e6e58e2f */
import type { TreeNode, RouteHandler, RouteTree } from "@lovrozagar/honey/tree"

const E = Object.create(null) as Record<string, TreeNode>

const H0: RouteHandler = { bek: null, ef: null, fn: null as unknown as RouteHandler["fn"], mw: [], ek: new Set(), iv: null, os: null, mt: null, ov: null, rp: "" }
const H1: RouteHandler = { bek: null, ef: null, fn: null as unknown as RouteHandler["fn"], mw: [], ek: new Set(), iv: null, os: null, mt: null, ov: null, rp: "" }
const H2: RouteHandler = { bek: null, ef: null, fn: null as unknown as RouteHandler["fn"], mw: [], ek: new Set(), iv: null, os: null, mt: null, ov: null, rp: "" }
const H3: RouteHandler = { bek: null, ef: null, fn: null as unknown as RouteHandler["fn"], mw: [], ek: new Set(), iv: null, os: null, mt: null, ov: null, rp: "" }
const H4: RouteHandler = { bek: null, ef: null, fn: null as unknown as RouteHandler["fn"], mw: [], ek: new Set(), iv: null, os: null, mt: null, ov: null, rp: "" }
const H5: RouteHandler = { bek: null, ef: null, fn: null as unknown as RouteHandler["fn"], mw: [], ek: new Set(), iv: null, os: null, mt: null, ov: null, rp: "" }

export const tree: TreeNode = { s: Object.assign(Object.create(null), { "ping": { s: E, d: null, w: null, m: { GET: H0 }, ws: null }, "openapi.json": { s: E, d: null, w: null, m: { GET: H1 }, ws: null }, "openapi.yml": { s: E, d: null, w: null, m: { GET: H2 }, ws: null }, "openapi.yaml": { s: E, d: null, w: null, m: { GET: H3 }, ws: null }, "docs": { s: E, d: null, w: null, m: { GET: H4 }, ws: null }, "manifest.json": { s: E, d: null, w: null, m: { GET: H5 }, ws: null } }), d: null, w: null, m: null, ws: null }

export const handlers: Record<string, RouteHandler> = {
	"GET /ping": H0,
	"GET /openapi.json": H1,
	"GET /openapi.yml": H2,
	"GET /openapi.yaml": H3,
	"GET /docs": H4,
	"GET /manifest.json": H5
}

export type RouteSelector = "GET /ping"
export const routeTree: RouteTree = { root: tree, meta: {}, handlers }
