/* @generated by honey — do not edit. checksum: 2e2b21edc1e1 */
import type { TreeNode, RouteHandler, RouteTree } from "@lovrozagar/honey/tree"

const E = Object.create(null) as Record<string, TreeNode>
function N(s: Record<string, TreeNode>, m: Record<string, RouteHandler> | null = null, d: TreeNode["d"] = null, w: { n: string; m: Record<string, RouteHandler> } | null = null): TreeNode {
	return { s, d, w: w as TreeNode["w"], m: m as TreeNode["m"], ws: null }
}
function S(o: Record<string, TreeNode>): Record<string, TreeNode> {
	return Object.assign(Object.create(null), o) as Record<string, TreeNode>
}
const FN = null as unknown as RouteHandler["fn"]

const P0 = "GET /ping"
const T0 = "project_id"
const P1 = "GET /articles"
const P2 = "GET /articles/meta"
const P3 = "GET /openapi.json"
const P4 = "GET /openapi.yml"
const P5 = "GET /openapi.yaml"
const P6 = "GET /docs"
const P7 = "GET /manifest.json"
const M1 = {"tenant":T0} as unknown as MetaShape
const M0 = {"tenant":T0,"permissions":["articles.read"],"summary":"List articles","worker":"origin"} as unknown as MetaShape

const H0: RouteHandler = { bek: null, fn: FN, mw: [], ek: new Set(), mt: null }
const H1: RouteHandler = { bek: null, fn: FN, mw: [], ek: new Set(), mt: M0 }
const H2: RouteHandler = { bek: null, fn: FN, mw: [], ek: new Set(), mt: M1 }
const H3: RouteHandler = { bek: null, fn: FN, mw: [], ek: new Set(), mt: null }
const H4: RouteHandler = { bek: null, fn: FN, mw: [], ek: new Set(), mt: null }
const H5: RouteHandler = { bek: null, fn: FN, mw: [], ek: new Set(), mt: null }
const H6: RouteHandler = { bek: null, fn: FN, mw: [], ek: new Set(), mt: null }
const H7: RouteHandler = { bek: null, fn: FN, mw: [], ek: new Set(), mt: null }

export const tree: TreeNode = N(S({ "ping": N(E, { GET: H0 }), "articles": N(S({ "meta": N(E, { GET: H2 }) }), { GET: H1 }), "openapi.json": N(E, { GET: H3 }), "openapi.yml": N(E, { GET: H4 }), "openapi.yaml": N(E, { GET: H5 }), "docs": N(E, { GET: H6 }), "manifest.json": N(E, { GET: H7 }) }))

export const handlers: Record<string, RouteHandler> = {
	[P0]: H0,
	[P1]: H1,
	[P2]: H2,
	[P3]: H3,
	[P4]: H4,
	[P5]: H5,
	[P6]: H6,
	[P7]: H7
}

export type MetaShape = {
	permissions?: ["articles.read"]
	summary?: "List articles"
	tenant: "project_id"
	worker?: "origin"
} & Record<string, unknown>


export type RouteSelector = typeof P1 | typeof P2 | typeof P0
export const meta: Record<string, MetaShape> = {
	[P1]: M0,
	[P2]: M1
}
export const routeTree: RouteTree = { root: tree, meta, handlers }
