/* @generated by honey — do not edit. checksum: 16fdecf297a4 */
import type { HoneyContext, WithOutput } from "@lovrozagar/honey"

export type BaseCtx = HoneyContext<unknown> & { realtime: { publish: (topic: string, data: unknown) => void } }

export type RouteSelector = "GET /ping"

declare module "honey" {
	interface HoneyCodegen {
		routeSelector: RouteSelector
	}
}

export type Routes = {
	"/ping": {
		get: {
			ctx: WithOutput<BaseCtx, {}>
			errors: never
			input: {}
			meta: {}
			output: {}
		}
	}
	"/openapi.json": {
		get: {
			ctx: WithOutput<BaseCtx, {}>
			errors: never
			input: {}
			meta: {}
			output: {}
		}
	}
	"/openapi.yml": {
		get: {
			ctx: WithOutput<BaseCtx, {}>
			errors: never
			input: {}
			meta: {}
			output: {}
		}
	}
	"/openapi.yaml": {
		get: {
			ctx: WithOutput<BaseCtx, {}>
			errors: never
			input: {}
			meta: {}
			output: {}
		}
	}
	"/docs": {
		get: {
			ctx: WithOutput<BaseCtx, {}>
			errors: never
			input: {}
			meta: {}
			output: {}
		}
	}
	"/manifest.json": {
		get: {
			ctx: WithOutput<BaseCtx, {}>
			errors: never
			input: {}
			meta: {}
			output: {}
		}
	}
}

export type RouteCtx<
	TPath extends keyof Routes,
	TMethod extends keyof Routes[TPath] & string
> = Routes[TPath][TMethod] extends { ctx: infer C } ? C : never

export type RouteInput<
	TPath extends keyof Routes,
	TMethod extends keyof Routes[TPath] & string
> = Routes[TPath][TMethod] extends { input: infer I } ? I : never

export type RouteOutput<
	TPath extends keyof Routes,
	TMethod extends keyof Routes[TPath] & string
> = Routes[TPath][TMethod] extends { output: infer O } ? O : never

export type RouteErrors<
	TPath extends keyof Routes,
	TMethod extends keyof Routes[TPath] & string
> = Routes[TPath][TMethod] extends { errors: infer E } ? E : never

export type RouteErrorShapes<
	TPath extends keyof Routes,
	TMethod extends keyof Routes[TPath] & string
> = Routes[TPath][TMethod] extends { errorShapes: infer S } ? S : never

export type RouteErrorsByStatus<
	TPath extends keyof Routes,
	TMethod extends keyof Routes[TPath] & string
> = Routes[TPath][TMethod] extends { errorsByStatus: infer S } ? S : never

export type RouteMeta<
	TPath extends keyof Routes,
	TMethod extends keyof Routes[TPath] & string
> = Routes[TPath][TMethod] extends { meta: infer M } ? M : never
