/* @generated by honey — do not edit. checksum: c5d7db173149 */
import type { TreeNode, RouteHandler, RouteTree } from "@lovrozagar/honey/tree"

const E = Object.create(null) as Record<string, TreeNode>
function N(s: Record<string, TreeNode>, m: Record<string, RouteHandler> | null = null, d: TreeNode["d"] = null, w: { n: string; m: Record<string, RouteHandler> } | null = null): TreeNode {
	return { s, d, w: w as TreeNode["w"], m: m as TreeNode["m"], ws: null }
}
function S(o: Record<string, TreeNode>): Record<string, TreeNode> {
	return Object.assign(Object.create(null), o) as Record<string, TreeNode>
}
const FN = null as unknown as RouteHandler["fn"]

const T0 = "validation_error"
const T1 = "unauthorized"
const P0 = "POST /in/json"
const P1 = "POST /in/form"
const P2 = "GET /in/search"
const P3 = "GET /in/headers"
const P4 = "GET /in/cookies"
const T2 = "memberId"
const P5 = "GET /in/params/:orgId/members/:memberId"
const P6 = "GET /in/none"
const P7 = "POST /in/file"
const P8 = "PUT /in/all/:resourceId"
const P9 = "GET /out/text"
const P10 = "GET /out/html"
const P11 = "GET /out/csv"
const P12 = "GET /out/xml"
const P13 = "GET /out/binary"
const P14 = "GET /out/sse"
const P15 = "POST /out/multi-status"
const P16 = "DELETE /out/no-content/:id"
const P17 = "GET /methods/resource"
const P18 = "POST /methods/resource"
const P19 = "PUT /methods/resource/:id"
const P20 = "PATCH /methods/resource/:id"
const P21 = "DELETE /methods/resource/:id"
const P22 = "GET /status/ok"
const P23 = "POST /status/created"
const P24 = "POST /status/accepted"
const P25 = "DELETE /status/no-content"
const P26 = "GET /stream/filtered"
const P27 = "POST /rs/upload"
const P28 = "GET /openapi.json"
const P29 = "GET /openapi.yml"
const P30 = "GET /openapi.yaml"
const P31 = "GET /docs"
const P32 = "GET /manifest.json"
const A0 = [T1,T0]
const J0 = {"type":"string"}
const A1 = ["id"]
const A2 = ["input"]
const J4 = {"type":"number"}
const J6 = {"type":"boolean"}
const J7 = {"type":"string","minLength":1}
const A3 = [T2,"orgId"]
const A4 = ["methods"]
const A5 = ["name"]
const J3 = {"id":J0}
const M0 = {"operationId":"input.createJson","tags":A2} as unknown as MetaShape
const M1 = {"operationId":"input.createForm","tags":A2} as unknown as MetaShape
const J5 = {"type":"array","items":J0}
const M2 = {"operationId":"input.search","tags":A2} as unknown as MetaShape
const M3 = {"operationId":"input.none","tags":A2} as unknown as MetaShape
const J8 = {"ok":J0}
const M4 = {"operationId":"resources.list","tags":A4} as unknown as MetaShape
const J10 = {"name":J0}
const M5 = {"operationId":"resources.create","tags":A4} as unknown as MetaShape
const J12 = {"id":J7}
const M6 = {"operationId":"resources.update","tags":A4} as unknown as MetaShape
const M7 = {"operationId":"resources.patch","tags":A4} as unknown as MetaShape
const M8 = {"operationId":"resources.delete","tags":A4} as unknown as MetaShape
const J2 = {"type":"object","properties":J3,"required":A1,"additionalProperties":false}
const O9 = {"text/plain":J8} as unknown as RouteHandler["os"]
const O10 = {"text/html":J8} as unknown as RouteHandler["os"]
const O11 = {"text/csv":J8} as unknown as RouteHandler["os"]
const O12 = {"application/xml":J8} as unknown as RouteHandler["os"]
const O13 = {"application/octet-stream":{"ok":{"vendor":"zod","version":1}}} as unknown as RouteHandler["os"]
const O14 = {"text/event-stream":J8} as unknown as RouteHandler["os"]
const J9 = {"type":"object","properties":J10,"required":A5}
const J11 = {"type":"object","properties":J12,"required":A1}
const I0 = {"json":{"type":"object","properties":{"email":J0,"name":J0},"required":["email","name"]}} as unknown as RouteHandler["iv"]
const J1 = {"created":J2}
const I1 = {"form":{"type":"object","properties":{"password":J0,"username":J0},"required":["password","username"]}} as unknown as RouteHandler["iv"]
const I2 = {"search":{"type":"object","properties":{"limit":J4,"page":J4,"q":J0},"required":["limit","page"]}} as unknown as RouteHandler["iv"]
const I3 = {"headers":{"type":"object","properties":{"x-api-key":J0,"x-request-id":J0},"required":["x-api-key","x-request-id"]}} as unknown as RouteHandler["iv"]
const I4 = {"cookies":{"type":"object","properties":{"locale":J0,"sid":J0},"required":["locale","sid"]}} as unknown as RouteHandler["iv"]
const I5 = {"params":{"type":"object","properties":{"memberId":J7,"orgId":J7},"required":A3}} as unknown as RouteHandler["iv"]
const I6 = {"form":{"type":"object","properties":{"title":J0,"upload":{"type":"string","format":"binary","contentEncoding":"binary"}},"required":["title","upload"]}} as unknown as RouteHandler["iv"]
const I8 = {"json":{"type":"object","properties":{"slug":J0},"required":["slug"]}} as unknown as RouteHandler["iv"]
const I9 = {"json":J9} as unknown as RouteHandler["iv"]
const I10 = {"json":J9,"params":J11} as unknown as RouteHandler["iv"]
const I11 = {"json":{"type":"object","properties":J10},"params":J11} as unknown as RouteHandler["iv"]
const I12 = {"json":{"type":"object","properties":{"x":J0},"required":["x"]}} as unknown as RouteHandler["iv"]
const I13 = {"json":{"type":"object","properties":{"task":J0},"required":["task"]}} as unknown as RouteHandler["iv"]
const I14 = {"search":{"type":"object","properties":{"channel":J0,"since":J0},"required":["channel"]}} as unknown as RouteHandler["iv"]
const I15 = {"json":{"type":"object","properties":{"chunks":J4,"fileName":J0},"required":["chunks","fileName"]}} as unknown as RouteHandler["iv"]
const O0 = {"application/json":J1} as unknown as RouteHandler["os"]
const O1 = {"application/json":{"ok":{"type":"object","properties":{"token":J0},"required":["token"],"additionalProperties":false}}} as unknown as RouteHandler["os"]
const O3 = {"application/json":{"ok":{"type":"object","properties":{"accepted":J6},"required":["accepted"],"additionalProperties":false}}} as unknown as RouteHandler["os"]
const O4 = {"application/json":{"ok":{"type":"object","properties":{"locale":J0,"valid":J6},"required":["locale","valid"],"additionalProperties":false}}} as unknown as RouteHandler["os"]
const O5 = {"application/json":{"ok":{"type":"object","properties":{"memberId":J0,"orgId":J0},"required":A3,"additionalProperties":false}}} as unknown as RouteHandler["os"]
const O6 = {"application/json":{"ok":{"type":"object","properties":{"ping":{"type":"string","const":"pong"}},"required":["ping"],"additionalProperties":false}}} as unknown as RouteHandler["os"]
const O7 = {"application/json":{"ok":{"type":"object","properties":{"name":J0,"title":J0},"required":["name","title"],"additionalProperties":false}}} as unknown as RouteHandler["os"]
const I7 = {"headers":{"type":"object","properties":{"if-match":J0},"required":["if-match"]},"json":{"type":"object","properties":{"data":{"type":"object","propertyNames":J0,"additionalProperties":{}}},"required":["data"]},"search":{"type":"object","properties":{"force":J6,"version":J4},"required":["version"]}} as unknown as RouteHandler["iv"]
const O8 = {"application/json":{"ok":{"type":"object","properties":{"etag":J0,"version":J4},"required":["etag","version"],"additionalProperties":false}}} as unknown as RouteHandler["os"]
const O15 = {"application/json":{"conflict":{"type":"object","properties":{"existing":J0,"message":J0},"required":["existing","message"],"additionalProperties":false},"created":{"type":"object","properties":{"id":J0,"slug":J0},"required":["id","slug"],"additionalProperties":false}}} as unknown as RouteHandler["os"]
const O17 = {"application/json":{"ok":{"type":"object","properties":{"id":J0,"name":J0},"required":["id","name"],"additionalProperties":false}}} as unknown as RouteHandler["os"]
const O18 = {"application/json":{"ok":J2}} as unknown as RouteHandler["os"]
const O19 = {"application/json":{"ok":{"type":"object","properties":{"v":J4},"required":["v"],"additionalProperties":false}}} as unknown as RouteHandler["os"]
const O20 = {"application/json":{"accepted":{"type":"object","properties":{"jobId":J0},"required":["jobId"],"additionalProperties":false}}} as unknown as RouteHandler["os"]
const O21 = {"application/json":{"accepted":{"type":"object","properties":{"uploadId":J0},"required":["uploadId"],"additionalProperties":false}}} as unknown as RouteHandler["os"]
const O2 = {"application/json":{"ok":{"type":"object","properties":{"results":J5},"required":["results"],"additionalProperties":false}}} as unknown as RouteHandler["os"]
const O16 = {"application/json":{"ok":{"type":"object","properties":{"items":J5},"required":["items"],"additionalProperties":false}}} as unknown as RouteHandler["os"]

const H0: RouteHandler = { bek: T0, fn: FN, mw: [], ek: new Set(A0), iv: I0, os: O0, mt: M0 }
const H1: RouteHandler = { bek: T0, fn: FN, mw: [], ek: new Set(A0), iv: I1, os: O1, mt: M1 }
const H2: RouteHandler = { bek: T0, fn: FN, mw: [], ek: new Set(A0), iv: I2, os: O2, mt: M2 }
const H3: RouteHandler = { bek: T0, fn: FN, mw: [], ek: new Set(A0), iv: I3, os: O3, mt: null }
const H4: RouteHandler = { bek: T0, fn: FN, mw: [], ek: new Set(A0), iv: I4, os: O4, mt: null }
const H5: RouteHandler = { bek: T0, fn: FN, mw: [], ek: new Set(A0), iv: I5, os: O5, mt: null }
const H6: RouteHandler = { bek: T0, fn: FN, mw: [], ek: new Set(A0), iv: null, os: O6, mt: M3 }
const H7: RouteHandler = { bek: T0, fn: FN, mw: [], ek: new Set(A0), iv: I6, os: O7, mt: null }
const H8: RouteHandler = { bek: T0, fn: FN, mw: [], ek: new Set(A0), iv: I7, os: O8, mt: null }
const H9: RouteHandler = { bek: T0, fn: FN, mw: [], ek: new Set(A0), iv: null, os: O9, mt: null }
const H10: RouteHandler = { bek: T0, fn: FN, mw: [], ek: new Set(A0), iv: null, os: O10, mt: null }
const H11: RouteHandler = { bek: T0, fn: FN, mw: [], ek: new Set(A0), iv: null, os: O11, mt: null }
const H12: RouteHandler = { bek: T0, fn: FN, mw: [], ek: new Set(A0), iv: null, os: O12, mt: null }
const H13: RouteHandler = { bek: T0, fn: FN, mw: [], ek: new Set(A0), iv: null, os: O13, mt: null }
const H14: RouteHandler = { bek: T0, fn: FN, mw: [], ek: new Set(A0), iv: null, os: O14, mt: null }
const H15: RouteHandler = { bek: T0, fn: FN, mw: [], ek: new Set([T1,T0,"conflict"]), iv: I8, os: O15, mt: null }
const H16: RouteHandler = { bek: T0, fn: FN, mw: [], ek: new Set([T1,T0,"not_found"]), iv: null, os: null, mt: null }
const H17: RouteHandler = { bek: T0, fn: FN, mw: [], ek: new Set(A0), iv: null, os: O16, mt: M4 }
const H18: RouteHandler = { bek: T0, fn: FN, mw: [], ek: new Set(A0), iv: I9, os: O0, mt: M5 }
const H19: RouteHandler = { bek: T0, fn: FN, mw: [], ek: new Set(A0), iv: I10, os: O17, mt: M6 }
const H20: RouteHandler = { bek: T0, fn: FN, mw: [], ek: new Set(A0), iv: I11, os: O18, mt: M7 }
const H21: RouteHandler = { bek: T0, fn: FN, mw: [], ek: new Set(A0), iv: null, os: null, mt: M8 }
const H22: RouteHandler = { bek: T0, fn: FN, mw: [], ek: new Set(A0), iv: null, os: O19, mt: null }
const H23: RouteHandler = { bek: T0, fn: FN, mw: [], ek: new Set(A0), iv: I12, os: O0, mt: null }
const H24: RouteHandler = { bek: T0, fn: FN, mw: [], ek: new Set(A0), iv: I13, os: O20, mt: null }
const H25: RouteHandler = { bek: T0, fn: FN, mw: [], ek: new Set(A0), iv: null, os: null, mt: null }
const H26: RouteHandler = { bek: T0, fn: FN, mw: [], ek: new Set(A0), iv: I14, os: O14, mt: null }
const H27: RouteHandler = { bek: T0, fn: FN, mw: [], ek: new Set(A0), iv: I15, os: O21, mt: null }
const H28: RouteHandler = { bek: T0, fn: FN, mw: [], ek: new Set(A0), iv: null, os: null, mt: null }
const H29: RouteHandler = { bek: T0, fn: FN, mw: [], ek: new Set(A0), iv: null, os: null, mt: null }
const H30: RouteHandler = { bek: T0, fn: FN, mw: [], ek: new Set(A0), iv: null, os: null, mt: null }
const H31: RouteHandler = { bek: T0, fn: FN, mw: [], ek: new Set(A0), iv: null, os: null, mt: null }
const H32: RouteHandler = { bek: T0, fn: FN, mw: [], ek: new Set(A0), iv: null, os: null, mt: null }

export const tree: TreeNode = N(S({ "in": N(S({ "json": N(E, { POST: H0 }), "form": N(E, { POST: H1 }), "search": N(E, { GET: H2 }), "headers": N(E, { GET: H3 }), "cookies": N(E, { GET: H4 }), "params": N(E, null, { n: "orgId", c: N(S({ "members": N(E, null, { n: "memberId", c: N(E, { GET: H5 }) }) })) }), "none": N(E, { GET: H6 }), "file": N(E, { POST: H7 }), "all": N(E, null, { n: "resourceId", c: N(E, { PUT: H8 }) }) })), "out": N(S({ "text": N(E, { GET: H9 }), "html": N(E, { GET: H10 }), "csv": N(E, { GET: H11 }), "xml": N(E, { GET: H12 }), "binary": N(E, { GET: H13 }), "sse": N(E, { GET: H14 }), "multi-status": N(E, { POST: H15 }), "no-content": N(E, null, { n: "id", c: N(E, { DELETE: H16 }) }) })), "methods": N(S({ "resource": N(E, { GET: H17, POST: H18 }, { n: "id", c: N(E, { PUT: H19, PATCH: H20, DELETE: H21 }) }) })), "status": N(S({ "ok": N(E, { GET: H22 }), "created": N(E, { POST: H23 }), "accepted": N(E, { POST: H24 }), "no-content": N(E, { DELETE: H25 }) })), "stream": N(S({ "filtered": N(E, { GET: H26 }) })), "rs": N(S({ "upload": N(E, { POST: H27 }) })), "openapi.json": N(E, { GET: H28 }), "openapi.yml": N(E, { GET: H29 }), "openapi.yaml": N(E, { GET: H30 }), "docs": N(E, { GET: H31 }), "manifest.json": N(E, { GET: H32 }) }))

export const handlers: Record<string, RouteHandler> = {
	[P0]: H0,
	[P1]: H1,
	[P2]: H2,
	[P3]: H3,
	[P4]: H4,
	[P5]: H5,
	[P6]: H6,
	[P7]: H7,
	[P8]: H8,
	[P9]: H9,
	[P10]: H10,
	[P11]: H11,
	[P12]: H12,
	[P13]: H13,
	[P14]: H14,
	[P15]: H15,
	[P16]: H16,
	[P17]: H17,
	[P18]: H18,
	[P19]: H19,
	[P20]: H20,
	[P21]: H21,
	[P22]: H22,
	[P23]: H23,
	[P24]: H24,
	[P25]: H25,
	[P26]: H26,
	[P27]: H27,
	[P28]: H28,
	[P29]: H29,
	[P30]: H30,
	[P31]: H31,
	[P32]: H32
}

export type MetaShape = {
	operationId: "input.createJson" | "input.createForm" | "input.search" | "input.none" | "resources.list" | "resources.create" | "resources.update" | "resources.patch" | "resources.delete"
	tags: ["input"] | ["methods"]
} & Record<string, unknown>


export type RouteSelector = typeof P21 | typeof P16 | typeof P25 | typeof P4 | typeof P3 | typeof P6 | typeof P5 | typeof P2 | typeof P17 | typeof P13 | typeof P11 | typeof P10 | typeof P14 | typeof P9 | typeof P12 | typeof P22 | typeof P26 | typeof P20 | typeof P7 | typeof P1 | typeof P0 | typeof P18 | typeof P15 | typeof P27 | typeof P24 | typeof P23 | typeof P8 | typeof P19
export const meta: Record<string, MetaShape> = {
	[P0]: M0,
	[P1]: M1,
	[P2]: M2,
	[P6]: M3,
	[P17]: M4,
	[P18]: M5,
	[P19]: M6,
	[P20]: M7,
	[P21]: M8
}
export const routeTree: RouteTree = { root: tree, meta, handlers }
