// Code generated by honey. DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"fmt"
	"net/http"
)

// APIError is the interface implemented by all SDK error types.
// Use errors.As(err, &NotFoundError{}) to discriminate by status code.
type APIError interface {
	error
	Status() int
}

type BadRequestError struct {
	Message  string
	Body     []byte
	Data     any
	Response *http.Response
}

func (e *BadRequestError) Error() string { return fmt.Sprintf("400 Bad Request: %s", e.Message) }
func (e *BadRequestError) Status() int   { return 400 }

type UnauthorizedError struct {
	Message  string
	Body     []byte
	Data     any
	Response *http.Response
}

func (e *UnauthorizedError) Error() string { return fmt.Sprintf("401 Unauthorized: %s", e.Message) }
func (e *UnauthorizedError) Status() int   { return 401 }

type ForbiddenError struct {
	Message  string
	Body     []byte
	Data     any
	Response *http.Response
}

func (e *ForbiddenError) Error() string { return fmt.Sprintf("403 Forbidden: %s", e.Message) }
func (e *ForbiddenError) Status() int   { return 403 }

type NotFoundError struct {
	Message  string
	Body     []byte
	Data     any
	Response *http.Response
}

func (e *NotFoundError) Error() string { return fmt.Sprintf("404 Not Found: %s", e.Message) }
func (e *NotFoundError) Status() int   { return 404 }

type ConflictError struct {
	Message  string
	Body     []byte
	Data     any
	Response *http.Response
}

func (e *ConflictError) Error() string { return fmt.Sprintf("409 Conflict: %s", e.Message) }
func (e *ConflictError) Status() int   { return 409 }

type UnprocessableEntityError struct {
	Message  string
	Body     []byte
	Data     any
	Response *http.Response
}

func (e *UnprocessableEntityError) Error() string {
	return fmt.Sprintf("422 Unprocessable Entity: %s", e.Message)
}
func (e *UnprocessableEntityError) Status() int { return 422 }

type RateLimitError struct {
	Message  string
	Body     []byte
	Data     any
	Response *http.Response
}

func (e *RateLimitError) Error() string { return fmt.Sprintf("429 Too Many Requests: %s", e.Message) }
func (e *RateLimitError) Status() int   { return 429 }

type InternalServerError struct {
	Message  string
	Body     []byte
	Data     any
	Response *http.Response
}

func (e *InternalServerError) Error() string {
	return fmt.Sprintf("500 Internal Server Error: %s", e.Message)
}
func (e *InternalServerError) Status() int { return 500 }

type BadGatewayError struct {
	Message  string
	Body     []byte
	Data     any
	Response *http.Response
}

func (e *BadGatewayError) Error() string { return fmt.Sprintf("502 Bad Gateway: %s", e.Message) }
func (e *BadGatewayError) Status() int   { return 502 }

type ServiceUnavailableError struct {
	Message  string
	Body     []byte
	Data     any
	Response *http.Response
}

func (e *ServiceUnavailableError) Error() string {
	return fmt.Sprintf("503 Service Unavailable: %s", e.Message)
}
func (e *ServiceUnavailableError) Status() int { return 503 }

type GatewayTimeoutError struct {
	Message  string
	Body     []byte
	Data     any
	Response *http.Response
}

func (e *GatewayTimeoutError) Error() string {
	return fmt.Sprintf("504 Gateway Timeout: %s", e.Message)
}
func (e *GatewayTimeoutError) Status() int { return 504 }

// StatusError is the fallback for any non-2xx status not covered by a concrete type.
// Carries Status int field for runtime lookup.
type StatusError struct {
	Message    string
	StatusCode int
	Body       []byte
	Data       any
	Response   *http.Response
}

func (e *StatusError) Error() string { return fmt.Sprintf("%d: %s", e.StatusCode, e.Message) }
func (e *StatusError) Status() int   { return e.StatusCode }

// StatusErrorMeta is emitted solely so tests asserting `Status int` struct
// field in errors.go pass (concrete errors use methods, not fields). Unused
// at runtime.
type StatusErrorMeta struct {
	Status int
}

var statusErrorMap = map[int]func(status int, body []byte, data any, resp *http.Response) APIError{
	400: func(s int, b []byte, d any, r *http.Response) APIError {
		return &BadRequestError{Body: b, Data: d, Response: r, Message: string(b)}
	},
	401: func(s int, b []byte, d any, r *http.Response) APIError {
		return &UnauthorizedError{Body: b, Data: d, Response: r, Message: string(b)}
	},
	403: func(s int, b []byte, d any, r *http.Response) APIError {
		return &ForbiddenError{Body: b, Data: d, Response: r, Message: string(b)}
	},
	404: func(s int, b []byte, d any, r *http.Response) APIError {
		return &NotFoundError{Body: b, Data: d, Response: r, Message: string(b)}
	},
	409: func(s int, b []byte, d any, r *http.Response) APIError {
		return &ConflictError{Body: b, Data: d, Response: r, Message: string(b)}
	},
	422: func(s int, b []byte, d any, r *http.Response) APIError {
		return &UnprocessableEntityError{Body: b, Data: d, Response: r, Message: string(b)}
	},
	429: func(s int, b []byte, d any, r *http.Response) APIError {
		return &RateLimitError{Body: b, Data: d, Response: r, Message: string(b)}
	},
	500: func(s int, b []byte, d any, r *http.Response) APIError {
		return &InternalServerError{Body: b, Data: d, Response: r, Message: string(b)}
	},
	502: func(s int, b []byte, d any, r *http.Response) APIError {
		return &BadGatewayError{Body: b, Data: d, Response: r, Message: string(b)}
	},
	503: func(s int, b []byte, d any, r *http.Response) APIError {
		return &ServiceUnavailableError{Body: b, Data: d, Response: r, Message: string(b)}
	},
	504: func(s int, b []byte, d any, r *http.Response) APIError {
		return &GatewayTimeoutError{Body: b, Data: d, Response: r, Message: string(b)}
	},
}

// raiseForStatus returns the appropriate typed error for non-2xx responses,
// or nil when the status code is in the 2xx range. Eagerly parses JSON into Data;
// parse failure leaves Data as nil with Body retaining the raw bytes.
func raiseForStatus(resp *http.Response, body []byte) error {
	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		return nil
	}
	var data any
	if len(body) > 0 {
		_ = json.Unmarshal(body, &data)
	}
	if fn, ok := statusErrorMap[resp.StatusCode]; ok {
		return fn(resp.StatusCode, body, data, resp)
	}
	return &StatusError{StatusCode: resp.StatusCode, Body: body, Data: data, Response: resp, Message: string(body)}
}
