// Code generated by honey. DO NOT EDIT.

package sdk

import (
	"bytes"
	"encoding/json"
)

// Nullable is an optional field that may also be null. Its zero value is "absent": the key is
// left out of the request (the field carries `omitzero`). NullOf sends an explicit null, Some a
// value. Decoding sets it from the response: absent stays absent, null becomes null.
type Nullable[T any] struct {
	value T
	set   bool
	null  bool
}

// Some is a present, non-null value.
func Some[T any](v T) Nullable[T] {
	return Nullable[T]{value: v, set: true}
}

// NullOf is an explicit null.
func NullOf[T any]() Nullable[T] {
	return Nullable[T]{set: true, null: true}
}

// IsZero reports an absent field; encoding/json leaves it out under `omitzero`.
func (n Nullable[T]) IsZero() bool {
	return !n.set
}

// IsNull reports an explicit null.
func (n Nullable[T]) IsNull() bool {
	return n.set && n.null
}

// Get returns the value and whether there is one (false for absent and for null).
func (n Nullable[T]) Get() (T, bool) {
	return n.value, n.set && !n.null
}

func (n Nullable[T]) MarshalJSON() ([]byte, error) {
	if !n.set || n.null {
		return []byte("null"), nil
	}
	return json.Marshal(n.value)
}

func (n *Nullable[T]) UnmarshalJSON(data []byte) error {
	if bytes.Equal(bytes.TrimSpace(data), []byte("null")) {
		*n = NullOf[T]()
		return nil
	}
	var v T
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	*n = Some(v)
	return nil
}
