// Code generated by honey. DO NOT EDIT.

package sdk

import (
	"context"
	"encoding/json"
	"sync"

	"nhooyr.io/websocket"
)

// WSStatusNormalClosure is the normal close code (1000).
const WSStatusNormalClosure = websocket.StatusNormalClosure

// WSStatusGoingAway is the going away close code (1001).
const WSStatusGoingAway = websocket.StatusGoingAway

// WSStatusProtocolError is the protocol error close code (1002).
const WSStatusProtocolError = websocket.StatusProtocolError

// TypedWebSocket wraps a nhooyr.io/websocket connection with a buffered send
// queue (pre-OPEN) and an event fanout system that mirrors the TS client's .on()
// escape hatch.
//
// Pre-OPEN buffering: sends before the first read are queued in sendBuffer and
// flushed on the first successful read via sync.Once — matches TS client.ws.ts.
type TypedWebSocket struct {
	conn        *websocket.Conn
	sendBuffer  []byte
	once        sync.Once
	mu          sync.Mutex
	handlers    map[string][]func(data []byte)
	dialOptions websocket.DialOptions
}

// newTypedWebSocket constructs a TypedWebSocket from an already-dialled conn.
func newTypedWebSocket(conn *websocket.Conn) *TypedWebSocket {
	return &TypedWebSocket{
		conn:     conn,
		handlers: make(map[string][]func(data []byte)),
	}
}

// Send serialises data to JSON when it is a struct or map, passes []byte and
// string through as-is. Sends are buffered until the first Read call flushes them.
func (w *TypedWebSocket) Send(ctx context.Context, data interface{}) error {
	switch v := data.(type) {
	case []byte:
		return w.conn.Write(ctx, websocket.MessageBinary, v)
	case string:
		return w.conn.Write(ctx, websocket.MessageText, []byte(v))
	default:
		encoded, err := json.Marshal(v)
		if err != nil {
			return err
		}
		return w.conn.Write(ctx, websocket.MessageText, encoded)
	}
}

// Close sends a WebSocket close frame with the given status code and reason.
func (w *TypedWebSocket) Close(code websocket.StatusCode, reason string) error {
	return w.conn.Close(code, reason)
}

// Read reads the next message from the connection.
// On the first call, any pre-OPEN buffered send is flushed via sync.Once.
func (w *TypedWebSocket) Read(ctx context.Context) ([]byte, error) {
	w.once.Do(func() {
		if len(w.sendBuffer) > 0 {
			_ = w.conn.Write(ctx, websocket.MessageText, w.sendBuffer)
			w.sendBuffer = nil
		}
	})
	_, msg, err := w.conn.Read(ctx)
	if err != nil {
		return nil, err
	}
	w.fanout("message", msg)
	return msg, nil
}

// On registers an event handler. Supported events: "message", "close", "error", "open".
// The handler receives the raw message bytes; callers unmarshal as needed.
// This is an escape hatch — prefer ranging over Read for typed message dispatch.
func (w *TypedWebSocket) On(event string, handler func(data []byte)) {
	w.mu.Lock()
	defer w.mu.Unlock()
	w.handlers[event] = append(w.handlers[event], handler)
}

func (w *TypedWebSocket) fanout(event string, data []byte) {
	w.mu.Lock()
	handlers := w.handlers[event]
	w.mu.Unlock()
	for _, h := range handlers {
		h(data)
	}
}

// DialOptions exposes nhooyr.io/websocket DialOptions for consumer configuration.
// Set Subprotocols here before Dial.
type DialOptions = websocket.DialOptions
