// Code generated by honey. DO NOT EDIT.

package sdk

import (
	"context"
	"encoding/json"
	"errors"
	"sync"

	"nhooyr.io/websocket"
)

// WSStatusNormalClosure is the normal close code (1000).
const WSStatusNormalClosure = websocket.StatusNormalClosure

// WSStatusGoingAway is the going away close code (1001).
const WSStatusGoingAway = websocket.StatusGoingAway

// WSStatusProtocolError is the protocol error close code (1002).
const WSStatusProtocolError = websocket.StatusProtocolError

// defaultWSReadLimit replaces nhooyr's 32 KiB default, which closes the
// connection on any larger frame.
const defaultWSReadLimit = 16 << 20

// TypedWebSocket wraps a nhooyr.io/websocket connection with an event fanout
// system that mirrors the TS client's .on() escape hatch.
type TypedWebSocket struct {
	conn     *websocket.Conn
	mu       sync.Mutex
	handlers map[string][]func(data []byte)
	closed   bool
}

// newTypedWebSocket constructs a TypedWebSocket from an already-dialled conn.
func newTypedWebSocket(conn *websocket.Conn) *TypedWebSocket {
	conn.SetReadLimit(defaultWSReadLimit)
	return &TypedWebSocket{
		conn:     conn,
		handlers: make(map[string][]func(data []byte)),
	}
}

// SetReadLimit sets the largest inbound message, in bytes (default 16 MiB).
func (w *TypedWebSocket) SetReadLimit(n int64) {
	w.conn.SetReadLimit(n)
}

// Send serialises data to JSON when it is a struct or map, and passes []byte
// (binary frame) and string (text frame) through as-is.
func (w *TypedWebSocket) Send(ctx context.Context, data interface{}) error {
	switch v := data.(type) {
	case []byte:
		return w.conn.Write(ctx, websocket.MessageBinary, v)
	case string:
		return w.conn.Write(ctx, websocket.MessageText, []byte(v))
	default:
		encoded, err := json.Marshal(v)
		if err != nil {
			return err
		}
		return w.conn.Write(ctx, websocket.MessageText, encoded)
	}
}

// Close sends a WebSocket close frame with the given status code and reason.
// A reason over 123 bytes is truncated to fit the frame.
func (w *TypedWebSocket) Close(code websocket.StatusCode, reason string) error {
	if len(reason) > 123 {
		reason = reason[:123]
	}
	err := w.conn.Close(code, reason)
	w.fireClose(int(code), reason)
	return err
}

// Read reads the next message from the connection. On a close frame it fires
// "close" handlers (data is the close reason); on any other failure it fires
// "error" handlers (data is the error text).
func (w *TypedWebSocket) Read(ctx context.Context) ([]byte, error) {
	_, msg, err := w.conn.Read(ctx)
	if err != nil {
		var ce websocket.CloseError
		if errors.As(err, &ce) {
			w.fireClose(int(ce.Code), ce.Reason)
		} else {
			w.fanout("error", []byte(err.Error()))
		}
		return nil, err
	}
	w.fanout("message", msg)
	return msg, nil
}

// On registers an event handler. Supported events: "message", "close", "error".
// The handler receives the raw message bytes; callers unmarshal as needed.
// This is an escape hatch — prefer ranging over Read for typed message dispatch.
func (w *TypedWebSocket) On(event string, handler func(data []byte)) {
	w.mu.Lock()
	defer w.mu.Unlock()
	w.handlers[event] = append(w.handlers[event], handler)
}

func (w *TypedWebSocket) fireClose(code int, reason string) {
	w.mu.Lock()
	if w.closed {
		w.mu.Unlock()
		return
	}
	w.closed = true
	w.mu.Unlock()
	_ = code
	w.fanout("close", []byte(reason))
}

func (w *TypedWebSocket) fanout(event string, data []byte) {
	w.mu.Lock()
	handlers := append([]func([]byte){}, w.handlers[event]...)
	w.mu.Unlock()
	for _, h := range handlers {
		h(data)
	}
}

// DialOptions exposes nhooyr.io/websocket DialOptions for consumer configuration.
// Set Subprotocols here before Dial.
type DialOptions = websocket.DialOptions
