/* @generated by honey — do not edit. checksum: e48c097b2e19 */
import { assembleRouteTree, type PackedRouteTable, type RouteHandler, type RouteTree, type TreeNode } from "@lovrozagar/honey/tree"

declare const P: readonly ["GET /health","GET /users/:id","POST /echo","GET /openapi.json","GET /openapi.yml","GET /openapi.yaml","GET /docs","GET /manifest.json"]
const D: PackedRouteTable = {"s":["GET /health","GET /users/:id","POST /echo","GET /openapi.json","GET /openapi.yml","GET /openapi.yaml","GET /docs","GET /manifest.json"],"o":{"t":[null,{"j":{"created":{"t":"s"}}}],"x":[0,0,1,0,0,0,0,0]}}
export const routeTree: RouteTree = assembleRouteTree(D)
export const tree: TreeNode = routeTree.root
export const handlers: Record<string, RouteHandler> = routeTree.handlers ?? {}
export type RouteSelector = typeof P[0] | typeof P[1] | typeof P[2]
