/* @generated by honey — do not edit. checksum: 4b15eddf19eb */
import type { TreeNode, RouteHandler, RouteTree } from "@lovrozagar/honey/tree"

const E = Object.create(null) as Record<string, TreeNode>
function N(s: Record<string, TreeNode>, m: Record<string, RouteHandler> | null = null, d: TreeNode["d"] = null, w: { n: string; m: Record<string, RouteHandler> } | null = null): TreeNode {
	return { s, d, w: w as TreeNode["w"], m: m as TreeNode["m"], ws: null }
}
function S(o: Record<string, TreeNode>): Record<string, TreeNode> {
	return Object.assign(Object.create(null), o) as Record<string, TreeNode>
}
const FN = null as unknown as RouteHandler["fn"]

const P0 = "GET /health"
const P1 = "GET /users/:id"
const P2 = "POST /echo"
const P3 = "GET /openapi.json"
const P4 = "GET /openapi.yml"
const P5 = "GET /openapi.yaml"
const P6 = "GET /docs"
const P7 = "GET /manifest.json"
const O0 = {"application/json":{"created":{"type":"string"}}} as unknown as RouteHandler["os"]

const H0: RouteHandler = { bek: null, ef: null, fn: FN, mw: [], ek: new Set(), iv: null, os: null, mt: null, ov: null, rp: "" }
const H1: RouteHandler = { bek: null, ef: null, fn: FN, mw: [], ek: new Set(), iv: null, os: null, mt: null, ov: null, rp: "" }
const H2: RouteHandler = { bek: null, ef: null, fn: FN, mw: [], ek: new Set(), iv: null, os: O0, mt: null, ov: null, rp: "" }
const H3: RouteHandler = { bek: null, ef: null, fn: FN, mw: [], ek: new Set(), iv: null, os: null, mt: null, ov: null, rp: "" }
const H4: RouteHandler = { bek: null, ef: null, fn: FN, mw: [], ek: new Set(), iv: null, os: null, mt: null, ov: null, rp: "" }
const H5: RouteHandler = { bek: null, ef: null, fn: FN, mw: [], ek: new Set(), iv: null, os: null, mt: null, ov: null, rp: "" }
const H6: RouteHandler = { bek: null, ef: null, fn: FN, mw: [], ek: new Set(), iv: null, os: null, mt: null, ov: null, rp: "" }
const H7: RouteHandler = { bek: null, ef: null, fn: FN, mw: [], ek: new Set(), iv: null, os: null, mt: null, ov: null, rp: "" }

export const tree: TreeNode = N(S({ "health": N(E, { GET: H0 }), "users": N(E, null, { n: "id", c: N(E, { GET: H1 }) }), "echo": N(E, { POST: H2 }), "openapi.json": N(E, { GET: H3 }), "openapi.yml": N(E, { GET: H4 }), "openapi.yaml": N(E, { GET: H5 }), "docs": N(E, { GET: H6 }), "manifest.json": N(E, { GET: H7 }) }))

export const handlers: Record<string, RouteHandler> = {
	[P0]: H0,
	[P1]: H1,
	[P2]: H2,
	[P3]: H3,
	[P4]: H4,
	[P5]: H5,
	[P6]: H6,
	[P7]: H7
}

export type RouteSelector = typeof P0 | typeof P1 | typeof P2
export const routeTree: RouteTree = { root: tree, meta: {}, handlers }
