/* @generated by honey — do not edit. checksum: e2b0ee4468d4 */
import type { RouteTree, TreeNode } from "@lovrozagar/honey/tree"

function S<T>(o: Record<string, T>): Record<string, T> {
	return Object.assign(Object.create(null) as Record<string, T>, o)
}
function N(s: Record<string, TreeNode> = S({}), m: Record<string, string> | null = null, d: TreeNode["d"] = null, w: TreeNode["w"] = null, ws: string | null = null): TreeNode {
	return { d, m, s, w, ws }
}

const P0 = "GET /health"
const P1 = "GET /users/:id"
const P2 = "POST /echo"

export const tree: TreeNode = N(S({ "health": N(undefined, S({ "GET": P0 })), "users": N(undefined, null, { n: "id", c: N(undefined, S({ "GET": P1 })) }), "echo": N(undefined, S({ "POST": P2 })) }))

export const routes: RouteTree["routes"] = S({
	[P0]: {},
	[P1]: {},
	[P2]: {}
})

export type RouteSelector = typeof P0 | typeof P1 | typeof P2
export const routeTree: RouteTree = { v: 2, root: tree, routes, meta: {} }
