import { createHash, randomBytes } from "node:crypto"
import { existsSync, mkdirSync, readdirSync, readFileSync, renameSync, rmdirSync, rmSync, writeFileSync } from "node:fs"
import { dirname, extname, isAbsolute, join, relative, resolve, sep } from "node:path"
import { toYaml } from "./yaml.ts"

/** Lists what one generator run wrote into an output directory, so the next run can delete leftovers. */
export const OUTPUT_MANIFEST = ".honey-generated.json"

/**
 * Writes `content` unless the file already holds exactly that. The write goes to a temp file in
 * the same directory and is renamed over the target, so a crash never leaves a truncated file.
 * Returns true when the file was written.
 */
export function writeFileIfChanged(filePath: string, content: string): boolean {
	if (existsSync(filePath)) {
		try {
			if (readFileSync(filePath, "utf-8") === content) return false
		} catch {
			/* unreadable — overwrite */
		}
	}
	mkdirSync(dirname(filePath), { recursive: true })
	const tmp = `${filePath}.${randomBytes(6).toString("hex")}.tmp`
	writeFileSync(tmp, content, "utf-8")
	try {
		renameSync(tmp, filePath)
	} catch (err) {
		rmSync(tmp, { force: true })
		throw err
	}
	return true
}

function checksum(text: string): string {
	return createHash("sha256").update(text).digest("hex").slice(0, 12)
}

/** Source file with a `@generated` header. Compares the full content, not only the header checksum. */
export function writeGenFile(filePath: string, body: string, generator: string): boolean {
	const normalized = body.replace(/\n*$/, "\n")
	const ext = filePath.endsWith(".d.ts") ? ".d.ts" : extname(filePath)
	const hash = checksum(normalized)
	const header =
		ext === ".sql"
			? `-- @generated by ${generator} — do not edit. checksum: ${hash}`
			: `/* @generated by ${generator} — do not edit. checksum: ${hash} */`
	return writeFileIfChanged(filePath, `${header}\n${normalized}`)
}

/** `x-generated` marker: an extension key, so the document stays valid OpenAPI. */
function withMarker(data: unknown, generator: string): Record<string, unknown> {
	const hash = checksum(JSON.stringify(data, null, 2))
	return { "x-generated": `${generator} checksum:${hash}`, ...(data as Record<string, unknown>) }
}

export function writeGenJsonFile(filePath: string, data: unknown, generator: string): boolean {
	return writeFileIfChanged(filePath, `${JSON.stringify(withMarker(data, generator), null, 2)}\n`)
}

export function writeGenYamlFile(filePath: string, data: unknown, generator: string): boolean {
	return writeFileIfChanged(filePath, toYaml(withMarker(data, generator)))
}

/**
 * Writes a generated directory (an SDK port, the Go CLI) and deletes the files the previous run
 * wrote that this run no longer produces. Only files listed in the previous manifest are ever
 * deleted, so hand-written files next to generated ones survive. Paths must stay inside `outDir`.
 */
export function writeOutputDir(outDir: string, files: Record<string, string>): void {
	const root = resolve(outDir)
	const written = new Set<string>()
	for (const [rel, content] of Object.entries(files)) {
		const abs = resolveInside(root, rel)
		writeFileIfChanged(abs, content)
		written.add(toPosix(relative(root, abs)))
	}

	for (const stale of readOutputManifest(root)) {
		if (written.has(stale)) continue
		const abs = resolveInside(root, stale)
		rmSync(abs, { force: true })
		removeEmptyParents(dirname(abs), root)
	}

	const manifest = `${JSON.stringify({ files: [...written].sort(compareCodeUnits) }, null, 2)}\n`
	writeFileIfChanged(join(root, OUTPUT_MANIFEST), manifest)
}

function readOutputManifest(root: string): string[] {
	const path = join(root, OUTPUT_MANIFEST)
	if (!existsSync(path)) return []
	try {
		const parsed = JSON.parse(readFileSync(path, "utf-8")) as { files?: unknown }
		return Array.isArray(parsed.files) ? parsed.files.filter((f): f is string => typeof f === "string") : []
	} catch {
		return []
	}
}

function resolveInside(root: string, rel: string): string {
	const abs = resolve(root, rel)
	if (isAbsolute(rel) || (abs !== root && !abs.startsWith(root + sep))) {
		throw new Error(`generated file path escapes its output directory: ${rel}`)
	}
	if (abs === root) throw new Error(`generated file path is the output directory itself: ${rel}`)
	return abs
}

function removeEmptyParents(dir: string, root: string): void {
	let current = dir
	while (current !== root && current.startsWith(root + sep)) {
		/* a directory the user already deleted counts as removed; keep walking up */
		if (existsSync(current)) {
			if (readdirSync(current).length > 0) return
			rmdirSync(current)
		}
		current = dirname(current)
	}
}

function toPosix(p: string): string {
	return p.split(sep).join("/")
}

function compareCodeUnits(a: string, b: string): number {
	return a < b ? -1 : a > b ? 1 : 0
}
