/* auto-generated by @ecomet/honey — do not edit */

import type { HoneyCtx, HoneyError, WithOutput } from "@ecomet/honey"

export type BaseCtx = HoneyCtx<{ SECRET: string }> & { errors: Record<string, (args: never[]) => unknown>; executionCtx: undefined | ({ waitUntil?: undefined | ((p: Promise<unknown>) => void) }); meta: Record<string, unknown>; path: string; routePattern: string; searchAll: Record<string, string[]>; db: { query: (_sql: string, _params: undefined | unknown[]) => unknown[]; url: string }; userId: string }

export type Routes = {
	"/orgs": {
		get: {
			ctx: WithOutput<BaseCtx & { input: { search: { limit: number; offset: number } }; readonly errors: { internal_server_error: (opts?: { cause?: unknown; vars?: Record<string, string | number> }) => HoneyError; validation_failed: (opts?: { cause?: unknown; vars?: Record<string, string | number> }) => HoneyError } }, { "application/json": { ok: { items: string[]; total: number } } }>
			errors: "internal_server_error" | "validation_failed"
			input: { search: { limit: number; offset: number } }
			meta: { auth: "required"; openApi: { "operationId": "listOrgs"; "summary": "List organizations"; "tags": ["Organization"] }; rateLimit: "strict" }
			output: { "application/json": { ok: { items: string[]; total: number } } }
		}
		post: {
			ctx: BaseCtx & { input: { json: { name: string; slug: string } }; readonly errors: { internal_server_error: (opts?: { cause?: unknown; vars?: Record<string, string | number> }) => HoneyError; org_limit_reached: (opts?: { cause?: unknown; vars?: Record<string, string | number> }) => HoneyError; org_slug_taken: (opts?: { cause?: unknown; vars?: Record<string, string | number> }) => HoneyError; validation_failed: (opts?: { cause?: unknown; vars?: Record<string, string | number> }) => HoneyError } }
			errors: "internal_server_error" | "org_limit_reached" | "org_slug_taken" | "validation_failed"
			input: { json: { name: string; slug: string } }
			meta: { auth: "required"; openApi: { "summary": "Create organization"; "tags": ["Organization"] } }
			output: {}
		}
	}
	"/orgs/:orgId": {
		get: {
			ctx: BaseCtx & { readonly params: { orgId: string }; readonly errors: { internal_server_error: (opts?: { cause?: unknown; vars?: Record<string, string | number> }) => HoneyError; not_found: (opts?: { cause?: unknown; vars?: Record<string, string | number> }) => HoneyError; validation_failed: (opts?: { cause?: unknown; vars?: Record<string, string | number> }) => HoneyError } }
			errors: "internal_server_error" | "not_found" | "validation_failed"
			input: {}
			meta: { auth: "required"; openApi: { "summary": "Get organization by ID"; "tags": ["Organization"] } }
			output: {}
		}
	}
}
