/* auto-generated by honey — do not edit */

import type { TreeNode, RouteHandler, RouteTree } from "honey/tree"

const E = Object.create(null) as Record<string, TreeNode>

const H0: RouteHandler = { bek: null, ef: null, fn: null as unknown as RouteHandler["fn"], mw: [], ek: new Set(["internal_server_error","validation_failed"]), iv: null, os: null, mt: {"auth":"required","openApi":{"operationId":"listOrgs","summary":"List organizations","tags":["Organization"]},"rateLimit":"strict"}, ov: null, rp: "" }
const H1: RouteHandler = { bek: null, ef: null, fn: null as unknown as RouteHandler["fn"], mw: [], ek: new Set(["internal_server_error","validation_failed","org_slug_taken","org_limit_reached"]), iv: null, os: null, mt: {"auth":"required","openApi":{"summary":"Create organization","tags":["Organization"]}}, ov: null, rp: "" }
const H2: RouteHandler = { bek: null, ef: null, fn: null as unknown as RouteHandler["fn"], mw: [], ek: new Set(["internal_server_error","validation_failed","not_found"]), iv: null, os: null, mt: {"auth":"required","openApi":{"summary":"Get organization by ID","tags":["Organization"]}}, ov: null, rp: "" }

export const tree: TreeNode = { s: Object.assign(Object.create(null), { "orgs": { s: E, d: { n: "orgId", c: { s: E, d: null, w: null, m: { GET: H2 }, ws: null } }, w: null, m: { GET: H0, POST: H1 }, ws: null } }), d: null, w: null, m: null, ws: null }

export const handlers: Record<string, RouteHandler> = {
	"GET /orgs": H0,
	"POST /orgs": H1,
	"GET /orgs/:orgId": H2
}
export const meta: Record<string, Record<string, unknown>> = {
	"GET /orgs": {"auth":"required","openApi":{"operationId":"listOrgs","summary":"List organizations","tags":["Organization"]},"rateLimit":"strict"},
	"POST /orgs": {"auth":"required","openApi":{"summary":"Create organization","tags":["Organization"]}},
	"GET /orgs/:orgId": {"auth":"required","openApi":{"summary":"Get organization by ID","tags":["Organization"]}}
}
export const routeTree: RouteTree = { root: tree, meta, handlers }
