import { readFileSync } from "node:fs"
import { describe, expect, it } from "vitest"
import { generateGoCLI } from "../../../../src/codegen-go-cli.ts"

function loadFixture(name: string): Record<string, unknown> {
	const url = new URL(`../fixtures/go-cli/${name}.json`, import.meta.url)
	return JSON.parse(readFileSync(url, "utf8")) as Record<string, unknown>
}

const RUNTIME_FILES = [
	"config.go",
	"auth.go",
	"output.go",
	"errors.go",
	"stream.go",
	"multipart.go",
	"version.go",
	"root.go",
]

function presentUnder(files: Record<string, string>, prefix: string): string[] {
	return Object.keys(files).filter((k) => k.startsWith(prefix))
}

/* ── Tier 11: runtime embed ── */

describe("go-cli codegen — Tier 11: runtime embed", () => {
	const crudSpec = loadFixture("crud")

	it("[#70] generator copies all cli-go/*.go runtime files into emitted files map", () => {
		const result = generateGoCLI(crudSpec, { binaryName: "acme" })
		for (const name of RUNTIME_FILES) {
			const key = `cli-go/${name}`
			const altKey = `internal/cli/${name}`
			const found = Object.hasOwn(result.files, key) || Object.hasOwn(result.files, altKey)
			expect(found, `runtime file ${name} missing from files map`).toBe(true)
		}
	})

	it("[#71] every embedded runtime file starts with `// Code generated by honey. DO NOT EDIT.` header", () => {
		const result = generateGoCLI(crudSpec, { binaryName: "acme" })
		for (const name of RUNTIME_FILES) {
			const src = result.files[`cli-go/${name}`] ?? result.files[`internal/cli/${name}`]
			expect(src, `missing runtime ${name}`).toBeDefined()
			expect(src as string).toMatch(/^\/\/ Code generated by honey\. DO NOT EDIT\./)
		}
	})

	it("[#72] SDK-embedded mode (sdkModulePath omitted) → all client-go/*.go files copied into internal/sdk/", () => {
		const result = generateGoCLI(crudSpec, { binaryName: "acme" })
		const sdkKeys = presentUnder(result.files, "internal/sdk/")
		expect(sdkKeys.length).toBeGreaterThan(0)
		expect(sdkKeys.some((k) => k.endsWith("runtime.go"))).toBe(true)
		expect(sdkKeys.some((k) => k.endsWith("client.go"))).toBe(true)
	})

	it("[#73] SDK-replace mode (sdkModulePath set) → go.mod has `replace` directive; no internal/sdk/ files", () => {
		const result = generateGoCLI(crudSpec, {
			binaryName: "acme",
			modulePath: "example.com/cli",
			sdkModulePath: "example.com/sdk",
		})
		expect(result.files["go.mod"]).toMatch(/replace\s+example\.com\/sdk\s*=>/)
		expect(presentUnder(result.files, "internal/sdk/").length).toBe(0)
	})

	it("[#74] cmd/*.go import paths match active branch (internal/sdk vs sdkModulePath)", () => {
		const embedded = generateGoCLI(crudSpec, { binaryName: "acme", modulePath: "example.com/cli" })
		const embeddedUsers = embedded.files["cmd/users.go"]
		expect(embeddedUsers).toContain(`"example.com/cli/internal/sdk"`)

		const replaced = generateGoCLI(crudSpec, {
			binaryName: "acme",
			modulePath: "example.com/cli",
			sdkModulePath: "github.com/acme/acme-go",
		})
		const replacedUsers = replaced.files["cmd/users.go"]
		expect(replacedUsers).toContain(`"github.com/acme/acme-go"`)
		expect(replacedUsers).not.toContain(`"example.com/cli/internal/sdk"`)
	})
})
