/* Code generated by honey. DO NOT EDIT. */

#![allow(dead_code)]

use crate::runtime::InvalidationConfig;
use once_cell::sync::Lazy;
use regex::Regex;
use std::collections::HashMap;
use std::time::{Duration, Instant};
use tokio::sync::Mutex;

/* PLACEHOLDER_RE matches `{name}` and `:name` placeholders. */
static PLACEHOLDER_RE: Lazy<Regex> =
    Lazy::new(|| Regex::new(r"\{([a-zA-Z_][a-zA-Z0-9_]*)\}|:([a-zA-Z_][a-zA-Z0-9_]*)").unwrap());

/* PATTERN_REGEX_CACHE caches compiled placeholder→`[^/]+` regexps per pattern key.
 * std::sync::Mutex is fine — pure CPU work, never held across an .await point. */
static PATTERN_REGEX_CACHE: Lazy<std::sync::Mutex<HashMap<String, Regex>>> =
    Lazy::new(|| std::sync::Mutex::new(HashMap::new()));

/// StaleEntry is the per-key invalidation record. `by` records mutation
/// selectors that contributed to the entry, `seq` is the monotonic version
/// stamp at write time, `until` is the absolute expiry.
#[derive(Clone, Debug)]
pub struct StaleEntry {
    pub by: Vec<String>,
    pub seq: u64,
    pub until: Instant,
}

/// RequestMeta is the per-request invalidation snapshot consumers see on hook
/// contexts. Mirrors TS `_RequestMeta`, Python `_RequestMeta`, Go `RequestMeta`.
#[derive(Clone, Debug)]
pub struct RequestMeta {
    pub selector: String,
    pub is_stale: bool,
    pub invalidated_by: Vec<String>,
    pub seq_snapshot: u64,
}

/// compile_pattern returns a cached anchored regex for the given pattern,
/// substituting `{name}` and `:name` placeholders with `[^/]+`.
pub fn compile_pattern(pattern: &str) -> Regex {
    {
        let cache = PATTERN_REGEX_CACHE.lock().unwrap();
        if let Some(re) = cache.get(pattern) {
            return re.clone();
        }
    }
    let mut out = String::with_capacity(pattern.len() + 4);
    out.push('^');
    let mut last = 0usize;
    for m in PLACEHOLDER_RE.find_iter(pattern) {
        out.push_str(&regex::escape(&pattern[last..m.start()]));
        out.push_str("[^/]+");
        last = m.end();
    }
    out.push_str(&regex::escape(&pattern[last..]));
    out.push('$');
    let re = Regex::new(&out).unwrap();
    let mut cache = PATTERN_REGEX_CACHE.lock().unwrap();
    cache.entry(pattern.to_string()).or_insert(re).clone()
}

/// path_has_placeholders returns true when `path` contains a `{name}` or `:name` segment.
pub fn path_has_placeholders(path: &str) -> bool {
    PLACEHOLDER_RE.is_match(path)
}

/// path_matches_pattern returns true when `concrete_path` matches `pattern`,
/// where `pattern` may contain `{name}` / `:name` placeholders.
pub fn path_matches_pattern(concrete_path: &str, pattern: &str) -> bool {
    if concrete_path == pattern {
        return true;
    }
    compile_pattern(pattern).is_match(concrete_path)
}

/// interpolate_path substitutes `{name}` / `:name` placeholders in `template`
/// using `params`. Returns Err(missing_key) if any placeholder is not in params.
pub fn interpolate_path(
    template: &str,
    params: &HashMap<String, String>,
) -> Result<String, String> {
    if !path_has_placeholders(template) {
        return Ok(template.to_string());
    }
    let mut missing: Option<String> = None;
    let mut out = String::with_capacity(template.len());
    let mut last = 0usize;
    for caps in PLACEHOLDER_RE.captures_iter(template) {
        let m = caps.get(0).unwrap();
        out.push_str(&template[last..m.start()]);
        let key = caps
            .get(1)
            .or_else(|| caps.get(2))
            .map(|c| c.as_str())
            .unwrap_or_default();
        match params.get(key) {
            Some(v) => out.push_str(&urlencoding::encode(v)),
            None => {
                if missing.is_none() {
                    missing = Some(key.to_string());
                }
                out.push_str(m.as_str());
            }
        }
        last = m.end();
    }
    out.push_str(&template[last..]);
    if let Some(k) = missing {
        return Err(k);
    }
    Ok(out)
}

/// resolve_invalidation_targets_for_mutation expands templated `METHOD /path/{x}`
/// invalidation entries to concrete `METHOD /path/abc` selectors using params.
/// Pattern-only entries (no placeholders) pass through; entries whose
/// placeholders cannot be resolved are dropped.
pub fn resolve_invalidation_targets_for_mutation(
    targets: &[String],
    params: &HashMap<String, String>,
) -> Vec<String> {
    let mut out = Vec::with_capacity(targets.len());
    for entry in targets {
        let space_idx = match entry.find(' ') {
            Some(i) => i,
            None => {
                out.push(entry.clone());
                continue;
            }
        };
        let method = &entry[..space_idx];
        let template = &entry[space_idx + 1..];
        if !path_has_placeholders(template) {
            out.push(entry.clone());
            continue;
        }
        match interpolate_path(template, params) {
            Ok(concrete) => out.push(format!("{} {}", method, concrete)),
            Err(_) => continue,
        }
    }
    out
}

struct TrackerState {
    entries: HashMap<String, StaleEntry>,
    /* insertion order; oldest at index 0 */
    order: Vec<String>,
    seq: u64,
}

/// StaleTracker tracks invalidation state per `METHOD /path` selector with TS-
/// parity semantics: exact-key + pattern-key two-tier lookup, TTL stale window,
/// LRU eviction at cap, monotonic seq for clear-after-mutate ordering.
/// All public methods are safe for concurrent async use (interior tokio Mutex).
pub struct StaleTracker {
    state: Mutex<TrackerState>,
    enabled: bool,
    stale_time: Duration,
    max_entries: usize,
    max_sources: usize,
}

impl StaleTracker {
    /// new constructs a tracker from an InvalidationConfig.
    /// Tracker is disabled (cheap no-op) when cfg is None or stale_time ≤ 0.
    pub fn new(cfg: Option<&InvalidationConfig>) -> Self {
        let mut enabled = false;
        let mut stale_time = Duration::from_millis(0);
        let mut max_entries = 1000usize;
        let mut max_sources = 16usize;
        if let Some(c) = cfg {
            if c.stale_time > 0 {
                enabled = true;
                stale_time = Duration::from_millis(c.stale_time as u64);
                if c.stale_max_entries > 0 {
                    max_entries = c.stale_max_entries;
                }
                if c.max_sources_per_target > 0 {
                    max_sources = c.max_sources_per_target;
                }
            }
        }
        StaleTracker {
            state: Mutex::new(TrackerState {
                entries: HashMap::new(),
                order: Vec::new(),
                seq: 0,
            }),
            enabled,
            stale_time,
            max_entries,
            max_sources,
        }
    }

    /// enabled reports whether the tracker will record / report stale entries.
    pub fn enabled(&self) -> bool {
        self.enabled
    }

    /// mark_stale bumps seq, expands templated invalidation entries with
    /// `params`, and records each resolved target as freshly stale.
    /// `mutation_selector` is appended to each entry's `by` list (capped at
    /// max_sources, deduped).
    pub async fn mark_stale(
        &self,
        invalidate: &[String],
        params: &HashMap<String, String>,
        mutation_selector: &str,
    ) {
        if !self.enabled || invalidate.is_empty() {
            return;
        }
        let mut s = self.state.lock().await;
        s.seq += 1;
        let seq = s.seq;
        let until = Instant::now() + self.stale_time;
        let resolved = resolve_invalidation_targets_for_mutation(invalidate, params);
        for target in resolved {
            upsert_locked(&mut s, &target, until, seq, mutation_selector, self.max_sources);
        }
        enforce_capacity_locked(&mut s, self.max_entries);
    }

    /// lookup_stale returns (invalidated_by, is_stale): exact + pattern lookup
    /// with expired-key sweep. Disabled tracker → (vec![], false).
    pub async fn lookup_stale(
        &self,
        concrete_selector: &str,
        concrete_path: &str,
        method: &str,
        now: Instant,
    ) -> (Vec<String>, bool) {
        if !self.enabled {
            return (Vec::new(), false);
        }
        let mut s = self.state.lock().await;
        lookup_locked(&mut s, concrete_selector, concrete_path, method, now)
    }

    /// clear_stale drops stale entries whose seq ≤ seq_snapshot and which match
    /// the given concrete_path under method (exact key + pattern keys).
    pub async fn clear_stale(
        &self,
        concrete_selector: &str,
        concrete_path: &str,
        method: &str,
        seq_snapshot: u64,
    ) {
        if !self.enabled {
            return;
        }
        let mut s = self.state.lock().await;
        if let Some(entry) = s.entries.get(concrete_selector) {
            if entry.seq <= seq_snapshot {
                delete_locked(&mut s, concrete_selector);
            }
        }
        let mut to_delete: Vec<String> = Vec::new();
        for (key, entry) in s.entries.iter() {
            if entry.seq > seq_snapshot {
                continue;
            }
            if !key.contains('{') && !key.contains(':') {
                continue;
            }
            let space_idx = match key.find(' ') {
                Some(i) => i,
                None => continue,
            };
            if &key[..space_idx] != method {
                continue;
            }
            if path_matches_pattern(concrete_path, &key[space_idx + 1..]) {
                to_delete.push(key.clone());
            }
        }
        for key in to_delete {
            delete_locked(&mut s, &key);
        }
    }

    /// is_stale reports whether (method, path) currently sits inside an active
    /// stale window. Walks pattern entries too. Disabled tracker → false.
    pub async fn is_stale(&self, method: &str, path: &str) -> bool {
        if !self.enabled {
            return false;
        }
        let mut s = self.state.lock().await;
        let selector = format!("{} {}", method, path);
        let (_, is_stale) = lookup_locked(&mut s, &selector, path, method, Instant::now());
        is_stale
    }

    /// build_request_meta returns a RequestMeta snapshot for the request about
    /// to fire, or None when tracker is disabled.
    pub async fn build_request_meta(
        &self,
        concrete_selector: &str,
        concrete_path: &str,
        method: &str,
    ) -> Option<RequestMeta> {
        if !self.enabled {
            return None;
        }
        let mut s = self.state.lock().await;
        let (by, is_stale) =
            lookup_locked(&mut s, concrete_selector, concrete_path, method, Instant::now());
        Some(RequestMeta {
            selector: concrete_selector.to_string(),
            is_stale,
            invalidated_by: by,
            seq_snapshot: s.seq,
        })
    }
}

fn upsert_locked(
    s: &mut TrackerState,
    key: &str,
    until: Instant,
    seq: u64,
    mutation_selector: &str,
    max_sources: usize,
) {
    if let Some(existing) = s.entries.get_mut(key) {
        existing.until = until;
        existing.seq = seq;
        if !mutation_selector.is_empty() && existing.by.len() < max_sources {
            let already = existing.by.iter().any(|b| b == mutation_selector);
            if !already {
                existing.by.push(mutation_selector.to_string());
            }
        }
        touch_order_locked(s, key);
        return;
    }
    let by = if mutation_selector.is_empty() {
        Vec::new()
    } else {
        vec![mutation_selector.to_string()]
    };
    s.entries.insert(key.to_string(), StaleEntry { by, seq, until });
    s.order.push(key.to_string());
}

fn touch_order_locked(s: &mut TrackerState, key: &str) {
    if let Some(idx) = s.order.iter().position(|k| k == key) {
        s.order.remove(idx);
    }
    s.order.push(key.to_string());
}

fn delete_locked(s: &mut TrackerState, key: &str) {
    if s.entries.remove(key).is_none() {
        return;
    }
    if let Some(idx) = s.order.iter().position(|k| k == key) {
        s.order.remove(idx);
    }
}

fn lookup_locked(
    s: &mut TrackerState,
    concrete_selector: &str,
    concrete_path: &str,
    method: &str,
    now: Instant,
) -> (Vec<String>, bool) {
    let mut all_by: Vec<String> = Vec::new();
    let mut exact_expired = false;
    if let Some(exact) = s.entries.get(concrete_selector) {
        if exact.until > now {
            all_by.extend(exact.by.iter().cloned());
        } else {
            exact_expired = true;
        }
    }
    if exact_expired {
        delete_locked(s, concrete_selector);
    }
    let mut expired: Vec<String> = Vec::new();
    for (key, entry) in s.entries.iter() {
        if entry.until <= now {
            expired.push(key.clone());
            continue;
        }
        if key == concrete_selector {
            continue;
        }
        if !key.contains('{') && !key.contains(':') {
            continue;
        }
        let space_idx = match key.find(' ') {
            Some(i) => i,
            None => continue,
        };
        if &key[..space_idx] != method {
            continue;
        }
        if path_matches_pattern(concrete_path, &key[space_idx + 1..]) {
            all_by.extend(entry.by.iter().cloned());
        }
    }
    for key in expired {
        delete_locked(s, &key);
    }
    let mut deduped: Vec<String> = Vec::with_capacity(all_by.len());
    for src in all_by {
        if !deduped.iter().any(|d| d == &src) {
            deduped.push(src);
        }
    }
    let any = !deduped.is_empty();
    (deduped, any)
}

fn enforce_capacity_locked(s: &mut TrackerState, max_entries: usize) {
    if s.entries.len() <= max_entries {
        return;
    }
    let now = Instant::now();
    let expired: Vec<String> = s
        .entries
        .iter()
        .filter(|(_, e)| e.until <= now)
        .map(|(k, _)| k.clone())
        .collect();
    for key in expired {
        delete_locked(s, &key);
    }
    let target = if max_entries / 2 < 1 { 1 } else { max_entries / 2 };
    while s.entries.len() > target && !s.order.is_empty() {
        let oldest = s.order[0].clone();
        delete_locked(s, &oldest);
    }
}
