/* Code generated by honey. DO NOT EDIT. */

//! Optional fields that may also be null.
//!
//! Such a field is `Option<Option<T>>`: `None` leaves the key out, `Some(None)` sends an explicit
//! `null`, `Some(Some(v))` a value. `#[serde(default)]` keeps a missing key `None`;
//! `deserialize` turns a present `null` into `Some(None)` (serde alone would read it as `None`).

use serde::{Deserialize, Deserializer};

pub fn deserialize<'de, D, T>(deserializer: D) -> Result<Option<Option<T>>, D::Error>
where
    D: Deserializer<'de>,
    T: Deserialize<'de>,
{
    Option::<T>::deserialize(deserializer).map(Some)
}
