/* Code generated by honey. DO NOT EDIT. */

#![allow(dead_code)]

/* WARNING: reqwest::blocking::Client WILL deadlock if called from inside a tokio async task.
   Only use SyncClient and do_request_blocking from non-async contexts (e.g. plain threads,
   test harnesses, CLI tools). Never call blocking methods from within an async runtime. */

use crate::errors::{raise_for_status, Error};
use crate::runtime::{LogEntry, OnLogHook};
use std::collections::HashMap;
use std::sync::Arc;
use std::sync::atomic::{AtomicBool, Ordering};
use std::time::Duration;

/// SyncOnRequestHook is a synchronous (non-async) request hook.
/// Returns Result<(), Error> directly — no Future, no Pin<Box<...>>.
pub type SyncOnRequestHook =
    Arc<dyn Fn(&mut SyncRequestContext) -> Result<(), Error> + Send + Sync>;

/// SyncOnResponseHook is a synchronous (non-async) response hook.
pub type SyncOnResponseHook =
    Arc<dyn Fn(&mut SyncResponseContext) -> Result<(), Error> + Send + Sync>;

/// SyncRequestContext carries mutable request metadata through SyncOnRequestHook invocations.
/// `selector` / `is_stale` / `invalidated_by` mirror the async RequestContext fields.
pub struct SyncRequestContext {
    pub method: reqwest::Method,
    pub url: String,
    pub path: String,
    pub headers: HashMap<String, String>,
    pub is_retry: bool,
    pub selector: String,
    pub is_stale: bool,
    pub invalidated_by: Vec<String>,
}

/// SyncResponseContext carries response metadata through SyncOnResponseHook invocations.
pub struct SyncResponseContext {
    pub status: u16,
    pub response: Vec<u8>,
    pub headers: reqwest::header::HeaderMap,
    pub is_retry: bool,
    pub selector: String,
    pub is_stale: bool,
    pub invalidated_by: Vec<String>,
}

/// SyncRequestBody represents the different body types a blocking request can carry.
/// `Stream` carries an owned, single-shot `reqwest::blocking::Body` (built via
/// `reqwest::blocking::Body::new` over any `impl Read + Send + 'static`); like
/// `Multipart`, it cannot be retried on 401 because the underlying body is not
/// `Clone`.
pub enum SyncRequestBody<'a> {
    None,
    Json(&'a serde_json::Value),
    FormUrl(&'a HashMap<String, String>),
    Multipart(reqwest::blocking::multipart::Form),
    Stream(reqwest::blocking::Body),
}

/// SyncClientConfig holds all configuration for the blocking SDK client.
#[derive(Clone)]
pub struct SyncClientConfig {
    pub base_url: String,
    pub bearer_token: Option<String>,
    pub headers: HashMap<String, String>,
    pub timeout: Duration,
    pub throw_on_error: bool,
    pub stale_max_entries: usize,
    pub invalidation: Option<crate::runtime::InvalidationConfig>,
    pub on_auth_expired:
        Option<Arc<dyn Fn() -> Result<String, Error> + Send + Sync>>,
    pub http_client: Option<reqwest::blocking::Client>,
    pub auth_header_name: Option<String>,
    pub auth_header_prefix: Option<String>,
    pub on_request: Vec<SyncOnRequestHook>,
    pub on_response: Vec<SyncOnResponseHook>,
    pub on_log: Option<OnLogHook>,
    pub state: Option<Arc<std::sync::Mutex<HashMap<String, serde_json::Value>>>>,
}

impl Default for SyncClientConfig {
    fn default() -> Self {
        SyncClientConfig {
            base_url: String::new(),
            bearer_token: None,
            headers: HashMap::new(),
            timeout: Duration::from_secs(30),
            throw_on_error: true,
            stale_max_entries: 500,
            invalidation: None,
            on_auth_expired: None,
            http_client: None,
            auth_header_name: None,
            auth_header_prefix: None,
            on_request: Vec::new(),
            on_response: Vec::new(),
            on_log: None,
            state: None,
        }
    }
}

/* emit_log invokes the on_log callback if configured, swallowing any panic so a
   faulty logger cannot break the request path. Mirrors runtime.rs sibling. */
fn emit_log(cfg: &SyncClientConfig, entry: LogEntry) {
    if let Some(ref hook) = cfg.on_log {
        let h = Arc::clone(hook);
        let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(move || h(entry)));
    }
}

/* err_status extracts an HTTP status from a typed Error::Api. */
fn err_status(err: &Error) -> Option<i32> {
    if let Error::Api(api) = err {
        Some(api.status() as i32)
    } else {
        None
    }
}

/// SyncRequestResult carries the raw bytes, status, headers, and final URL from a blocking request.
#[allow(dead_code)]
pub(crate) struct SyncRequestResult {
    pub body: Vec<u8>,
    pub status: u16,
    pub headers: reqwest::header::HeaderMap,
    pub url: String,
}

/// do_request_blocking executes a blocking HTTP request, injects auth, merges headers,
/// handles on_auth_expired retry on 401, fires on_request/on_response hooks, and wraps
/// errors into typed Error variants. Emits on_log lifecycle entries (request_start once,
/// response_received once for the final response, error on terminal failure).
#[allow(clippy::too_many_arguments)]
pub(crate) fn do_request_blocking(
    client: &reqwest::blocking::Client,
    cfg: &SyncClientConfig,
    method: reqwest::Method,
    raw_url: &str,
    query: &[(String, String)],
    body: SyncRequestBody<'_>,
    call_headers: Option<&HashMap<String, String>>,
    timeout: Option<Duration>,
    cancel_token: Option<Arc<AtomicBool>>,
    operation: &str,
    request_meta: Option<&crate::invalidation::RequestMeta>,
) -> Result<SyncRequestResult, Error> {
    let start = std::time::Instant::now();

    /* Pre-flight cancellation check — short-circuit before any work. */
    if let Some(ref tok) = cancel_token {
        if tok.load(Ordering::Acquire) {
            emit_log(
                cfg,
                LogEntry {
                    level: "error".to_string(),
                    event: "error".to_string(),
                    operation: operation.to_string(),
                    duration_ms: start.elapsed().as_millis() as i64,
                    status: None,
                    error: Some("Canceled".to_string()),
                },
            );
            return Err(Error::Canceled);
        }
    }

    emit_log(
        cfg,
        LogEntry {
            level: "debug".to_string(),
            event: "request_start".to_string(),
            operation: operation.to_string(),
            duration_ms: 0,
            status: None,
            error: None,
        },
    );

    /* Reborrow body for retry path; Multipart + Stream are not Clone so cannot retry 401 */
    let retry_body: Option<SyncRequestBody<'_>> = match &body {
        SyncRequestBody::None => Some(SyncRequestBody::None),
        SyncRequestBody::Json(v) => Some(SyncRequestBody::Json(v)),
        SyncRequestBody::FormUrl(m) => Some(SyncRequestBody::FormUrl(m)),
        SyncRequestBody::Multipart(_) => None,
        SyncRequestBody::Stream(_) => None,
    };

    let mut result = match execute_request_blocking(
        client,
        cfg,
        method.clone(),
        raw_url,
        query,
        body,
        call_headers,
        cfg.bearer_token.as_deref(),
        false,
        timeout,
        cancel_token.clone(),
        request_meta,
    ) {
        Ok(r) => r,
        Err(e) => {
            emit_log(
                cfg,
                LogEntry {
                    level: "error".to_string(),
                    event: "error".to_string(),
                    operation: operation.to_string(),
                    duration_ms: start.elapsed().as_millis() as i64,
                    status: err_status(&e),
                    error: Some(format!("{:?}", e)),
                },
            );
            return Err(e);
        }
    };

    if result.status == 401 {
        if let Some(ref hook) = cfg.on_auth_expired {
            if let Some(retry) = retry_body {
                let new_token = match hook() {
                    Ok(t) => t,
                    Err(e) => {
                        let mapped = Error::AuthExpired(e.to_string());
                        emit_log(
                            cfg,
                            LogEntry {
                                level: "error".to_string(),
                                event: "error".to_string(),
                                operation: operation.to_string(),
                                duration_ms: start.elapsed().as_millis() as i64,
                                status: err_status(&mapped),
                                error: Some(format!("{:?}", mapped)),
                            },
                        );
                        return Err(mapped);
                    }
                };
                result = match execute_request_blocking(
                    client,
                    cfg,
                    method,
                    raw_url,
                    query,
                    retry,
                    call_headers,
                    Some(&new_token),
                    true,
                    timeout,
                    cancel_token,
                    request_meta,
                ) {
                    Ok(r) => r,
                    Err(e) => {
                        emit_log(
                            cfg,
                            LogEntry {
                                level: "error".to_string(),
                                event: "error".to_string(),
                                operation: operation.to_string(),
                                duration_ms: start.elapsed().as_millis() as i64,
                                status: err_status(&e),
                                error: Some(format!("{:?}", e)),
                            },
                        );
                        return Err(e);
                    }
                };
            }
            /* Multipart/Stream 401: Form/Body is not Clone, cannot retry; fall through */
        }
    }

    let status_i32 = result.status as i32;
    let level = if result.status >= 400 { "warn" } else { "info" };
    emit_log(
        cfg,
        LogEntry {
            level: level.to_string(),
            event: "response_received".to_string(),
            operation: operation.to_string(),
            duration_ms: start.elapsed().as_millis() as i64,
            status: Some(status_i32),
            error: None,
        },
    );

    if let Some(err) = raise_for_status(result.status, result.body.clone()) {
        emit_log(
            cfg,
            LogEntry {
                level: "error".to_string(),
                event: "error".to_string(),
                operation: operation.to_string(),
                duration_ms: start.elapsed().as_millis() as i64,
                status: Some(status_i32),
                error: Some(format!("{:?}", err)),
            },
        );
        return Err(err);
    }

    Ok(result)
}

#[allow(clippy::too_many_arguments)]
fn execute_request_blocking(
    client: &reqwest::blocking::Client,
    cfg: &SyncClientConfig,
    method: reqwest::Method,
    raw_url: &str,
    query: &[(String, String)],
    body: SyncRequestBody<'_>,
    call_headers: Option<&HashMap<String, String>>,
    bearer_token: Option<&str>,
    is_retry: bool,
    per_call_timeout: Option<Duration>,
    cancel_token: Option<Arc<AtomicBool>>,
    request_meta: Option<&crate::invalidation::RequestMeta>,
) -> Result<SyncRequestResult, Error> {
    let url = build_url_sync(&cfg.base_url, raw_url, query)?;
    let url_str = url.to_string();

    /* build merged headers map for hook inspection */
    let mut hook_headers: HashMap<String, String> = cfg.headers.clone();
    if let Some(ch) = call_headers {
        for (k, v) in ch {
            hook_headers.insert(k.clone(), v.clone());
        }
    }
    if let Some(token) = bearer_token {
        if !token.is_empty() {
            let name = cfg.auth_header_name.as_deref().unwrap_or("Authorization");
            let prefix = cfg.auth_header_prefix.as_deref().unwrap_or("Bearer ");
            hook_headers.insert(name.to_string(), format!("{}{}", prefix, token));
        }
    }

    let (meta_selector, meta_is_stale, meta_by) = match request_meta {
        Some(m) => (m.selector.clone(), m.is_stale, m.invalidated_by.clone()),
        None => (String::new(), false, Vec::new()),
    };

    let mut req_ctx = SyncRequestContext {
        method: method.clone(),
        url: url_str.clone(),
        path: raw_url.to_string(),
        headers: hook_headers,
        is_retry,
        selector: meta_selector.clone(),
        is_stale: meta_is_stale,
        invalidated_by: meta_by.clone(),
    };

    /* fire on_request hooks */
    for hook in cfg.on_request.iter() {
        hook(&mut req_ctx)?;
    }

    let mut req = client.request(req_ctx.method.clone(), &req_ctx.url);

    /* apply headers from context */
    for (k, v) in &req_ctx.headers {
        req = req.header(k.as_str(), v.as_str());
    }

    /* apply body and content-type */
    req = match body {
        SyncRequestBody::Json(v) => {
            req = req.header("Content-Type", "application/json");
            req.json(v)
        }
        SyncRequestBody::FormUrl(m) => req.form(m),
        SyncRequestBody::Multipart(f) => req.multipart(f),
        SyncRequestBody::Stream(b) => {
            req = req.header("Content-Type", "application/octet-stream");
            req.body(b)
        }
        SyncRequestBody::None => req,
    };

    /* apply per-call timeout (overrides cfg.timeout) */
    let effective_timeout = per_call_timeout.unwrap_or(cfg.timeout);
    req = req.timeout(effective_timeout);

    /* Re-check cancellation just before the blocking send (covers the window
       between do_request_blocking pre-flight check and actual send). */
    if let Some(ref tok) = cancel_token {
        if tok.load(Ordering::Acquire) {
            return Err(Error::Canceled);
        }
    }

    let resp = req.send().map_err(|e| {
        if e.is_timeout() {
            Error::Timeout
        } else if e.is_request() {
            Error::Canceled
        } else {
            Error::Transport(e)
        }
    })?;

    let status = resp.status().as_u16();
    let resp_headers = resp.headers().clone();
    let resp_url = resp.url().to_string();
    let body_bytes = resp.bytes().map_err(Error::Transport)?.to_vec();

    let mut resp_ctx = SyncResponseContext {
        status,
        response: body_bytes.clone(),
        headers: resp_headers.clone(),
        is_retry,
        selector: meta_selector,
        is_stale: meta_is_stale,
        invalidated_by: meta_by,
    };

    /* fire on_response hooks */
    for hook in cfg.on_response.iter() {
        hook(&mut resp_ctx)?;
    }

    Ok(SyncRequestResult {
        body: body_bytes,
        status,
        headers: resp_headers,
        url: resp_url,
    })
}

/// build_url_sync constructs the full URL from base + path + query params.
pub(crate) fn build_url_sync(
    base_url: &str,
    path: &str,
    query: &[(String, String)],
) -> Result<url::Url, Error> {
    let base = url::Url::parse(base_url)?;
    let joined = base.join(path)?;
    let mut url = joined;
    if !query.is_empty() {
        let mut pairs = url.query_pairs_mut();
        for (k, v) in query {
            pairs.append_pair(k, v);
        }
    }
    Ok(url)
}
