/* Code generated by honey. DO NOT EDIT. */

use crate::errors::{raise_for_status, Error};
use futures_util::StreamExt;

/// SseEvent represents a single server-sent event. `id` is the last event id
/// seen on the stream so far (the spec's sticky "last event ID buffer").
#[derive(Debug, Clone, Default, PartialEq)]
pub struct SseEvent {
    pub data: String,
    pub event: String,
    pub id: String,
    pub retry: i32,
}

/// Largest single line, and largest data of one event.
pub const SSE_MAX_LINE: usize = 1024 * 1024;
pub const SSE_MAX_EVENT: usize = 8 * 1024 * 1024;

/// SseParser is an incremental WHATWG event-stream parser. Lines end in CRLF,
/// LF or CR; a blank line dispatches; a final event without its blank line is
/// never dispatched; `id` is sticky; `retry` needs ASCII digits; field values
/// are not trimmed. Each input byte is scanned once.
#[derive(Debug, Default)]
pub struct SseParser {
    line: Vec<u8>,
    pending_cr: bool,
    started: bool,
    data: String,
    has_data: bool,
    event: String,
    last_id: String,
    retry: i32,
}

impl SseParser {
    pub fn new() -> Self {
        Self::default()
    }

    /// feed consumes a chunk and returns every event it completes.
    pub fn feed(&mut self, chunk: &[u8]) -> Result<Vec<SseEvent>, Error> {
        let mut out = Vec::new();
        for &b in chunk {
            if self.pending_cr {
                self.pending_cr = false;
                if b == b'\n' {
                    continue;
                }
            }
            match b {
                b'\n' | b'\r' => {
                    if b == b'\r' {
                        self.pending_cr = true;
                    }
                    let line = std::mem::take(&mut self.line);
                    if let Some(ev) = self.process(&line)? {
                        out.push(ev);
                    }
                }
                _ => {
                    if self.line.len() >= SSE_MAX_LINE {
                        return Err(Error::Other("sse line exceeds 1 MiB".into()));
                    }
                    self.line.push(b);
                }
            }
        }
        Ok(out)
    }

    fn process(&mut self, raw: &[u8]) -> Result<Option<SseEvent>, Error> {
        let mut line = String::from_utf8_lossy(raw).into_owned();
        if !self.started {
            self.started = true;
            if let Some(rest) = line.strip_prefix('\u{feff}') {
                line = rest.to_string();
            }
        }
        if line.is_empty() {
            return Ok(self.dispatch());
        }
        if line.starts_with(':') {
            return Ok(None);
        }
        let (field, value) = match line.find(':') {
            Some(i) => {
                let v = &line[i + 1..];
                (&line[..i], v.strip_prefix(' ').unwrap_or(v))
            }
            None => (line.as_str(), ""),
        };
        match field {
            "data" => {
                if self.has_data {
                    self.data.push('\n');
                }
                if self.data.len() + value.len() > SSE_MAX_EVENT {
                    return Err(Error::Other("sse event exceeds 8 MiB".into()));
                }
                self.data.push_str(value);
                self.has_data = true;
            }
            "event" => self.event = value.to_string(),
            "id" => {
                if !value.contains('\0') {
                    self.last_id = value.to_string();
                }
            }
            "retry" => {
                if !value.is_empty() && value.bytes().all(|c| c.is_ascii_digit()) {
                    if let Ok(n) = value.parse::<i32>() {
                        self.retry = n;
                    }
                }
            }
            _ => {}
        }
        Ok(None)
    }

    fn dispatch(&mut self) -> Option<SseEvent> {
        let ev = if self.has_data {
            Some(SseEvent {
                data: std::mem::take(&mut self.data),
                event: std::mem::take(&mut self.event),
                id: self.last_id.clone(),
                retry: self.retry,
            })
        } else {
            None
        };
        self.data.clear();
        self.has_data = false;
        self.event.clear();
        self.retry = 0;
        ev
    }
}

/// parse_sse_text parses complete text; used by the conformance vectors.
pub fn parse_sse_text(chunks: &[&str]) -> Result<Vec<SseEvent>, Error> {
    let mut p = SseParser::new();
    let mut out = Vec::new();
    for c in chunks {
        out.extend(p.feed(c.as_bytes())?);
    }
    Ok(out)
}

/// parse_sse_stream returns a Stream of SseEvent values read from a reqwest Response.
/// On non-2xx response it yields a typed error immediately then terminates.
pub fn parse_sse_stream(
    resp: reqwest::Response,
) -> impl futures_util::Stream<Item = Result<SseEvent, Error>> {
    async_stream::stream! {
        let status = resp.status().as_u16();
        if !(200..300).contains(&status) {
            let body = resp.bytes().await.unwrap_or_default().to_vec();
            if let Some(err) = raise_for_status(status, body) {
                yield Err(err);
            }
            return;
        }

        let mut byte_stream = resp.bytes_stream();
        let mut parser = SseParser::new();
        while let Some(chunk) = byte_stream.next().await {
            match chunk {
                Err(e) => {
                    yield Err(Error::Transport(e));
                    return;
                }
                Ok(bytes) => match parser.feed(&bytes) {
                    Ok(events) => {
                        for ev in events {
                            yield Ok(ev);
                        }
                    }
                    Err(e) => {
                        yield Err(e);
                        return;
                    }
                },
            }
        }
    }
}
