/* Code generated by honey. DO NOT EDIT. */

use crate::errors::{raise_for_status, Error};
use bytes::Bytes;
use futures_util::StreamExt;

/// SseEvent represents a single server-sent event.
pub struct SseEvent {
    pub data: String,
    pub event: String,
    pub id: String,
    pub retry: i32,
}

/// parse_sse_stream returns a Stream of SseEvent values read from a reqwest Response.
/// On non-2xx response it yields a typed error immediately then terminates.
/// Hand-parsed over reqwest bytes_stream; mirrors Go parseSSEStream line-for-line.
pub fn parse_sse_stream(
    resp: reqwest::Response,
) -> impl futures_util::Stream<Item = Result<SseEvent, Error>> {
    async_stream::stream! {
        let status = resp.status().as_u16();
        if !(200..300).contains(&status) {
            let body = resp.bytes().await.unwrap_or_default().to_vec();
            if let Some(err) = raise_for_status(status, body) {
                yield Err(err);
            }
            return;
        }

        let mut byte_stream = resp.bytes_stream();
        let mut buf = Vec::<u8>::new();

        while let Some(chunk) = byte_stream.next().await {
            match chunk {
                Err(e) => {
                    yield Err(Error::Transport(e));
                    return;
                }
                Ok(bytes) => {
                    buf.extend_from_slice(&bytes);
                    loop {
                        /* find next double-newline delimiter: \r\n\r\n, \n\n, \r\r */
                        let delim_pos = find_double_newline(&buf);
                        match delim_pos {
                            None => break,
                            Some((start, end)) => {
                                let block = buf[..start].to_vec();
                                buf.drain(..end);
                                let block_str = String::from_utf8_lossy(&block);
                                let trimmed = block_str.trim();
                                if !trimmed.is_empty() {
                                    if let Some(ev) = parse_sse_block(trimmed) {
                                        yield Ok(ev);
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }

        /* flush any remaining data */
        if !buf.is_empty() {
            let block_str = String::from_utf8_lossy(&buf);
            let trimmed = block_str.trim();
            if !trimmed.is_empty() {
                if let Some(ev) = parse_sse_block(trimmed) {
                    yield Ok(ev);
                }
            }
        }
    }
}

/// find_double_newline returns (content_end, advance) positions for the first
/// occurrence of \r\n\r\n, \n\n, or \r\r in buf.
pub(crate) fn find_double_newline(buf: &[u8]) -> Option<(usize, usize)> {
    let delimiters: &[&[u8]] = &[b"\r\n\r\n", b"\n\n", b"\r\r"];
    for delim in delimiters {
        let dlen = delim.len();
        if buf.len() < dlen {
            continue;
        }
        for i in 0..=(buf.len() - dlen) {
            if &buf[i..i + dlen] == *delim {
                return Some((i, i + dlen));
            }
        }
    }
    None
}

/// parse_sse_block parses a single SSE message block into an SseEvent.
/// Mirrors Go parseSSEBlock line-for-line:
/// - colon-prefix lines are comments and skipped
/// - field/val split on first colon; leading space stripped from val
/// - data lines joined with \n
/// - id containing null byte (\0) is ignored per spec
/// - retry parsed as non-negative i32
pub(crate) fn parse_sse_block(block: &str) -> Option<SseEvent> {
    let mut data = String::new();
    let mut has_data = false;
    let mut event = String::new();
    let mut id = String::new();
    let mut retry: i32 = 0;
    let mut is_comment = true;

    for raw_line in block.split('\n') {
        let line = raw_line.trim_end_matches('\r');
        if line.starts_with(':') {
            continue;
        }
        is_comment = false;

        let (field, val) = if let Some(colon_idx) = line.find(':') {
            let f = &line[..colon_idx];
            let v = &line[colon_idx + 1..];
            let v = v.strip_prefix(' ').unwrap_or(v);
            (f, v)
        } else {
            (line, "")
        };

        match field {
            "data" => {
                if has_data {
                    data.push('\n');
                    data.push_str(val);
                } else {
                    data = val.to_string();
                    has_data = true;
                }
            }
            "event" => {
                event = val.to_string();
            }
            "id" => {
                /* per spec: id containing null byte must be ignored */
                if !val.contains('\0') {
                    id = val.to_string();
                }
            }
            "retry" => {
                use std::str::FromStr;
                if let Ok(n) = i32::from_str(val) {
                    if n >= 0 {
                        retry = n;
                    }
                }
            }
            _ => {}
        }
    }

    if is_comment || !has_data {
        return None;
    }

    Some(SseEvent { data, event, id, retry })
}

/* suppress unused import warning — Bytes is part of the public API contract */
const _: fn() = || {
    let _: Bytes = Bytes::new();
};
