_generated: honey checksum:3317b718b433
info:
  description: null
  title: Demo API
  version: "1.0.0"
openapi: "3.1.0"
paths:
  /orgs:
    get:
      parameters:
        - in: query
          name: limit
          required: true
          schema:
            type: number
        - in: query
          name: offset
          required: true
          schema:
            type: number
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListOrgsResponse200"
          description: ok
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Err400ValidationFailed"
          description: validation_failed
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Err500InternalServerError"
          description: internal_server_error
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateOrgRequest"
        required: true
      responses:
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Err400ValidationFailed"
          description: validation_failed
        "403":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateOrgResponse403"
          description: org_limit_reached
        "409":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateOrgResponse409"
          description: org_slug_taken
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Err500InternalServerError"
          description: internal_server_error
  /orgs/{orgId}:
    get:
      parameters:
        - in: path
          name: orgId
          required: true
          schema:
            type: string
      responses:
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Err400ValidationFailed"
          description: validation_failed
        "404":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetOrgResponse404"
          description: not_found
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Err500InternalServerError"
          description: internal_server_error
components:
  schemas:
    ListOrgsResponse200:
      type: object
      properties:
        items:
          type: array
          items:
            type: string
        total:
          type: number
      required:
        - items
        - total
      additionalProperties: false
    Err400ValidationFailed:
      properties:
        error_key:
          enum:
            - validation_failed
          type: string
        fields:
          additionalProperties:
            items:
              properties:
                error_key:
                  type: string
                message:
                  type: string
                path:
                  type: string
              required:
                - error_key
                - message
                - path
              type: object
            type: array
          type: object
        message:
          type: string
        status:
          enum:
            - 400
          type: integer
        status_key:
          type: string
        success:
          const: false
      required:
        - error_key
        - fields
        - message
        - status
        - status_key
        - success
      type: object
    Err500InternalServerError:
      properties:
        error_key:
          enum:
            - internal_server_error
          type: string
        fields:
          additionalProperties:
            items:
              properties:
                error_key:
                  type: string
                message:
                  type: string
                path:
                  type: string
              required:
                - error_key
                - message
                - path
              type: object
            type: array
          type: object
        message:
          type: string
        status:
          enum:
            - 500
          type: integer
        status_key:
          type: string
        success:
          const: false
      required:
        - error_key
        - fields
        - message
        - status
        - status_key
        - success
      type: object
    CreateOrgRequest:
      type: object
      properties:
        name:
          type: string
        slug:
          type: string
      required:
        - name
        - slug
    CreateOrgResponse403:
      properties:
        error_key:
          enum:
            - org_limit_reached
          type: string
        fields:
          additionalProperties:
            items:
              properties:
                error_key:
                  type: string
                message:
                  type: string
                path:
                  type: string
              required:
                - error_key
                - message
                - path
              type: object
            type: array
          type: object
        message:
          type: string
        status:
          enum:
            - 403
          type: integer
        status_key:
          type: string
        success:
          const: false
      required:
        - error_key
        - fields
        - message
        - status
        - status_key
        - success
      type: object
    CreateOrgResponse409:
      properties:
        error_key:
          enum:
            - org_slug_taken
          type: string
        fields:
          additionalProperties:
            items:
              properties:
                error_key:
                  type: string
                message:
                  type: string
                path:
                  type: string
              required:
                - error_key
                - message
                - path
              type: object
            type: array
          type: object
        message:
          type: string
        status:
          enum:
            - 409
          type: integer
        status_key:
          type: string
        success:
          const: false
      required:
        - error_key
        - fields
        - message
        - status
        - status_key
        - success
      type: object
    GetOrgResponse404:
      properties:
        error_key:
          enum:
            - not_found
          type: string
        fields:
          additionalProperties:
            items:
              properties:
                error_key:
                  type: string
                message:
                  type: string
                path:
                  type: string
              required:
                - error_key
                - message
                - path
              type: object
            type: array
          type: object
        message:
          type: string
        status:
          enum:
            - 404
          type: integer
        status_key:
          type: string
        success:
          const: false
      required:
        - error_key
        - fields
        - message
        - status
        - status_key
        - success
      type: object
