/* auto-generated by honey — do not edit */

import type { HoneyContext, HoneyError } from "honey"

export type BaseCtx = HoneyContext<{ JWT_SECRET: string; REDIS_URL: string }> & {
	cache: { get: (_k: string) => null | string; set: (_k: string, _v: string) => void }
	session: { orgId: string; permissions: string[]; userId: string }
}

export type Routes = {
	"/health": {
		get: {
			ctx: BaseCtx & {
				readonly errors: {
					expired_token: (opts?: {
						cause?: unknown
						vars?: Record<string, string | number>
					}) => HoneyError
					invalid_token: (opts?: {
						cause?: unknown
						vars?: Record<string, string | number>
					}) => HoneyError
				}
			}
			errors: "expired_token" | "invalid_token"
			input: {}
			meta: {}
			output: {}
		}
	}
	"/docs": {
		get: {
			ctx: BaseCtx & {
				readonly errors: {
					expired_token: (opts?: {
						cause?: unknown
						vars?: Record<string, string | number>
					}) => HoneyError
					invalid_token: (opts?: {
						cause?: unknown
						vars?: Record<string, string | number>
					}) => HoneyError
				}
			}
			errors: "expired_token" | "invalid_token"
			input: {}
			meta: {}
			output: {}
		}
	}
	"/feed": {
		get: {
			ctx: BaseCtx & {
				input: { search: { page: number } }
				readonly errors: {
					expired_token: (opts?: {
						cause?: unknown
						vars?: Record<string, string | number>
					}) => HoneyError
					invalid_token: (opts?: {
						cause?: unknown
						vars?: Record<string, string | number>
					}) => HoneyError
				}
			}
			errors: "expired_token" | "invalid_token"
			input: { search: { page: number } }
			meta: {}
			output: {}
		}
	}
	"/account": {
		get: {
			ctx: BaseCtx & {
				readonly errors: {
					expired_token: (opts?: {
						cause?: unknown
						vars?: Record<string, string | number>
					}) => HoneyError
					forbidden: (opts?: {
						cause?: unknown
						vars?: Record<string, string | number>
					}) => HoneyError
					invalid_token: (opts?: {
						cause?: unknown
						vars?: Record<string, string | number>
					}) => HoneyError
				}
			}
			errors: "expired_token" | "forbidden" | "invalid_token"
			input: {}
			meta: {}
			output: {}
		}
	}
	"/account/settings": {
		post: {
			ctx: BaseCtx & {
				input: { json: { notifications: boolean; theme: "dark" | "light" } }
				readonly errors: {
					expired_token: (opts?: {
						cause?: unknown
						vars?: Record<string, string | number>
					}) => HoneyError
					forbidden: (opts?: {
						cause?: unknown
						vars?: Record<string, string | number>
					}) => HoneyError
					invalid_token: (opts?: {
						cause?: unknown
						vars?: Record<string, string | number>
					}) => HoneyError
				}
			}
			errors: "expired_token" | "forbidden" | "invalid_token"
			input: { json: { notifications: boolean; theme: "dark" | "light" } }
			meta: {}
			output: {}
		}
	}
	"/resources": {
		post: {
			ctx: BaseCtx & {
				input: { json: { name: string; type: "doc" | "image" | "video" } }
				readonly errors: {
					expired_token: (opts?: {
						cause?: unknown
						vars?: Record<string, string | number>
					}) => HoneyError
					forbidden: (opts?: {
						cause?: unknown
						vars?: Record<string, string | number>
					}) => HoneyError
					invalid_token: (opts?: {
						cause?: unknown
						vars?: Record<string, string | number>
					}) => HoneyError
					rate_limited: (opts?: {
						cause?: unknown
						vars?: Record<string, string | number>
					}) => HoneyError
				}
			}
			errors: "expired_token" | "forbidden" | "invalid_token" | "rate_limited"
			input: { json: { name: string; type: "doc" | "image" | "video" } }
			meta: {}
			output: {}
		}
	}
	"/resources/:resourceId": {
		get: {
			ctx: BaseCtx & {
				readonly params: { resourceId: string }
				readonly errors: {
					expired_token: (opts?: {
						cause?: unknown
						vars?: Record<string, string | number>
					}) => HoneyError
					forbidden: (opts?: {
						cause?: unknown
						vars?: Record<string, string | number>
					}) => HoneyError
					invalid_token: (opts?: {
						cause?: unknown
						vars?: Record<string, string | number>
					}) => HoneyError
					not_found: (opts?: {
						cause?: unknown
						vars?: Record<string, string | number>
					}) => HoneyError
				}
			}
			errors: "expired_token" | "forbidden" | "invalid_token" | "not_found"
			input: {}
			meta: {}
			output: {}
		}
		delete: {
			ctx: BaseCtx & {
				readonly params: { resourceId: string }
				readonly errors: {
					expired_token: (opts?: {
						cause?: unknown
						vars?: Record<string, string | number>
					}) => HoneyError
					forbidden: (opts?: {
						cause?: unknown
						vars?: Record<string, string | number>
					}) => HoneyError
					invalid_token: (opts?: {
						cause?: unknown
						vars?: Record<string, string | number>
					}) => HoneyError
					not_found: (opts?: {
						cause?: unknown
						vars?: Record<string, string | number>
					}) => HoneyError
				}
			}
			errors: "expired_token" | "forbidden" | "invalid_token" | "not_found"
			input: {}
			meta: {}
			output: {}
		}
	}
}
