import { describe, expect, expectTypeOf, it } from "vitest"
import * as z from "zod"
import { generateRouteTreeFromApp } from "../../../src/codegen.ts"
import { createMiddleware, defineErrors, honey } from "../../../src/index.ts"
import { testClient } from "../../../src/testing.ts"
import type { RouteEntry, RouteTree } from "../../../src/tree.ts"
import { createNode, insertRoute } from "../../../src/tree.ts"

/* ---- helpers ---- */

/** A generated-style tree: topology with RouteId leaves plus route data, no handlers. */
function treeOf(routes: Array<[string, string, RouteEntry?]>): RouteTree {
	const root = createNode()
	const entries: Record<string, RouteEntry> = {}
	for (const [method, path, entry] of routes) {
		const id = insertRoute(root, method as "GET", path)
		entries[id] = entry ?? {}
	}
	return { meta: {}, root, routes: entries, v: 2 }
}

function buildStaticTree(): RouteTree {
	return treeOf([
		["GET", "/orgs", { ek: ["not_found"], mt: { auth: "required", rateLimit: "strict" } }],
		["POST", "/orgs", { mt: { auth: "required" } }],
		["GET", "/health"],
	])
}

/* ---- .routeTree() hydration ---- */

describe(".routeTree() hydration", () => {
	it("binds registered handlers to the loaded leaves", async () => {
		const app = honey<{}>()
			.routeTree(buildStaticTree())
			.get("/orgs")
			.handler((c) => c.res.text("ok", "orgs-list"))
			.post("/orgs")
			.handler((c) => c.res.text("ok", "orgs-create"))
			.get("/health")
			.handler((c) => c.res.text("ok", "ok"))

		const client = testClient(app, { env: {} })
		expect(await (await client.get("/orgs")).text()).toBe("orgs-list")
		expect(await (await client.post("/orgs")).text()).toBe("orgs-create")
		expect(await (await client.get("/health")).text()).toBe("ok")
	})

	it("the registered route is the whole record — the tree's data is not consulted for it", async () => {
		const app = honey<{}>()
			.routeTree(buildStaticTree())
			.get("/orgs")
			.meta({ fresh: true })
			.handler((c) => c.res.json("ok", { meta: c.meta, pattern: c.routePattern }))
		const res = await testClient(app, { env: {} }).get("/orgs")
		expect(await res.json()).toEqual({ meta: { fresh: true }, pattern: "/orgs" })
	})

	it("never mutates the loaded tree, which is frozen", () => {
		const tree = buildStaticTree()
		honey<{}>()
			.routeTree(tree)
			.get("/orgs")
			.handler((c) => c.res.text("ok", "ok"))
		expect(Object.isFrozen(tree.root)).toBe(true)
		expect(Object.isFrozen(tree.root.s.orgs)).toBe(true)
		expect(tree.routes["GET /orgs"]).toEqual({ ek: ["not_found"], mt: { auth: "required", rateLimit: "strict" } })
	})

	it("chain middleware runs for hydrated routes", async () => {
		const withDb = createMiddleware(async (_ctx, next) => next({ db: "connected" }))
		const app = honey<{}>()
			.routeTree(buildStaticTree())
			.use(withDb)
			.get("/orgs")
			.handler((c) => c.res.text("ok", c.db))
		expect(await (await testClient(app, { env: {} }).get("/orgs")).text()).toBe("connected")
	})

	it("input schemas of the registered route validate", async () => {
		const app = honey<{}>()
			.routeTree(buildStaticTree())
			.get("/orgs")
			.input({ search: z.object({ limit: z.coerce.number() }) })
			.handler((c) => c.res.json("ok", { limit: c.input.search.limit }))
		const res = await testClient(app, { env: {} }).get("/orgs?limit=10")
		expect(await res.json()).toEqual({ limit: 10 })
	})

	it("a route the tree does not hold makes the tree stale: finalize names it", () => {
		const app = honey<{}>()
			.routeTree(buildStaticTree())
			.get("/new-route")
			.handler((c) => c.res.text("ok", "new"))
		expect(() => app.fetch(new Request("http://x/orgs"), {})).toThrow(/GET \/new-route is registered but missing/)
	})

	it("a leaf no handler serves is documented but answers 404", async () => {
		const app = honey<{}>()
			.routeTree(buildStaticTree())
			.get("/health")
			.handler((c) => c.res.text("ok", "ok"))
		const client = testClient(app, { env: {} })
		expect((await client.get("/orgs")).status).toBe(404)
		expect((await client.get("/health")).status).toBe(200)
		const routes = (app as unknown as { _collectRoutes(): Array<{ method: string; path: string }> })._collectRoutes()
		expect(routes.map((r) => `${r.method} ${r.path}`)).toContain("GET /orgs")
	})

	it("routeTree() after a route is registered throws", () => {
		const app = honey<{}>()
		app.get("/x").handler((c) => c.res.text("ok", "x"))
		expect(() => app.routeTree(buildStaticTree())).toThrow(/before routes are registered/)
	})

	it("rejects a tree generated by an older honey (handler objects at the leaves)", () => {
		const root = createNode()
		root.m = { GET: { fn: null } as unknown as string }
		expect(() => honey<{}>().routeTree({ meta: {}, root, routes: {} })).toThrow(/older honey/)
	})

	it("registration after the first request re-finalizes (epoch)", async () => {
		const app = honey<{}>()
		app.get("/a").handler((c) => c.res.text("ok", "a"))
		expect((await app.fetch(new Request("http://x/a"), {})).status).toBe(200)
		app.get("/b").handler((c) => c.res.text("ok", "b"))
		const res = await app.fetch(new Request("http://x/b"), {})
		expect(await res.text()).toBe("b")
	})
})

/* ---- two apps, one tree ---- */

describe("two apps built from one generated tree", () => {
	it("each serves its own handlers", async () => {
		const tree = treeOf([["GET", "/who"]])
		const make = (name: string) =>
			honey<{}>()
				.routeTree(tree)
				.get("/who")
				.handler((c) => c.res.text("ok", name))
		const a = make("A")
		const b = make("B")
		expect(await (await a.fetch(new Request("http://x/who"), {})).text()).toBe("A")
		expect(await (await b.fetch(new Request("http://x/who"), {})).text()).toBe("B")
		/* a third app that registers nothing serves nobody's handler */
		const c = honey<{}>().routeTree(tree)
		expect((await c.fetch(new Request("http://x/who"), {})).status).toBe(404)
	})
})

/* ---- error factory with a loaded tree ---- */

describe(".routeTree() error factory", () => {
	it("ctx.errors carries the route's declared keys", async () => {
		const errors = defineErrors({ not_found: "not_found" })
		const app = honey<{}>()
			.errorFactory(errors)
			.routeTree(buildStaticTree())
			.get("/orgs")
			.errors("not_found")
			.handler((c) => {
				throw c.errors.not_found()
			})
		expect((await testClient(app, { env: {} }).get("/orgs")).status).toBe(404)
	})
})

/* ---- scoped middleware with a loaded tree (C1) ---- */

describe(".routeTree() with scoped middleware", () => {
	const auth = createMiddleware(async (ctx, next) => {
		if (ctx.req.headers.get("authorization") !== "ok") return new Response("no", { status: 401 })
		return next()
	})

	it("guards hydrated routes exactly like the runtime tree", async () => {
		const build = (tree?: RouteTree) => {
			const app = honey<{}>()
			if (tree) app.routeTree(tree)
			app.use("/admin", auth)
			app.get("/admin/secret").handler((c) => c.res.json("ok", { pattern: c.routePattern }))
			app.get("/public").handler((c) => c.res.text("ok", "pub"))
			return app
		}
		const runtime = build()
		const loaded = build(runtime.toRouteTree())
		for (const app of [runtime, loaded]) {
			const denied = await app.fetch(new Request("http://x/admin/secret"), {})
			expect(denied.status).toBe(401)
			const ok = await app.fetch(new Request("http://x/admin/secret", { headers: { authorization: "ok" } }), {})
			expect(await ok.json()).toEqual({ pattern: "/admin/secret" })
			expect((await app.fetch(new Request("http://x/public"), {})).status).toBe(200)
		}
	})

	it("guards delegated routes by their own pattern, not the catch-all's", async () => {
		const tree = treeOf([
			["GET", "/admin/users", { mt: { worker: "admin" } }],
			["GET", "/public", { mt: { worker: "web" } }],
		])
		const app = honey<{}>().routeTree(tree)
		app.use("/admin", auth)
		app.all("/*").handler((c) => c.res.json("ok", { meta: c.meta, pattern: c.routePattern }))
		expect((await app.fetch(new Request("http://x/admin/users"), {})).status).toBe(401)
		const pub = await app.fetch(new Request("http://x/public"), {})
		expect(await pub.json()).toEqual({ meta: { worker: "web" }, pattern: "/public" })
	})
})

/* ---- .on() with a loaded tree (H19) ---- */

describe(".routeTree() with .on()", () => {
	it("binds every method", async () => {
		const live = honey<{}>()
		live.on(["GET", "POST"], "/multi").handler((c) => c.res.text("ok", c.req.method))
		const app = honey<{}>().routeTree(live.toRouteTree())
		app.on(["GET", "POST"], "/multi").handler((c) => c.res.text("ok", `local ${c.req.method}`))
		expect(await (await app.fetch(new Request("http://x/multi"), {})).text()).toBe("local GET")
		expect(await (await app.fetch(new Request("http://x/multi", { method: "POST" }), {})).text()).toBe("local POST")
	})
})

/* ---- root wildcard that the tree holds (H22) ---- */

describe(".routeTree() with the app's own root wildcard", () => {
	it("serves an SPA fallback that is part of the tree for GET and HEAD alike", async () => {
		const build = () => {
			const app = honey<{}>()
			app.get("/api/x").handler((c) => c.res.text("ok", "x"))
			app.get("/*path").handler((c) => c.res.text("ok", `spa ${c.params.path}`))
			return app
		}
		const app = honey<{}>().routeTree(build().toRouteTree())
		app.get("/api/x").handler((c) => c.res.text("ok", "x"))
		app.get("/*path").handler((c) => c.res.text("ok", `spa ${c.params.path}`))
		const get = await app.fetch(new Request("http://x/some/page"), {})
		expect(await get.text()).toBe("spa some/page")
		const head = await app.fetch(new Request("http://x/some/page", { method: "HEAD" }), {})
		expect(head.status).toBe(200)
	})
})

/* ---- internal routes with a loaded tree (H20) ---- */

describe(".routeTree() with openapi()", () => {
	it("mounts spec and docs although the generated tree leaves them out", async () => {
		const build = (tree?: RouteTree) => {
			const app = honey<{}>()
			if (tree) app.routeTree(tree)
			app.get("/users").handler((c) => c.res.json("ok", []))
			return app.openapi({ docs: "scalar", title: "T", version: "1" })
		}
		const live = build()
		const code = generateRouteTreeFromApp(live)
		expect(code).not.toContain("openapi.json")
		const app = build(live.toRouteTree())
		expect((await app.fetch(new Request("http://x/openapi.json"), {})).status).toBe(200)
		expect((await app.fetch(new Request("http://x/docs"), {})).status).toBe(200)
	})
})

/* ---- codegen ---- */

describe("codegen emits topology and route data", () => {
	it("leaves are route ids and route data is keyed by them", () => {
		const app = honey<{}>()
			.get("/orgs")
			.handler((c) => c.res.text("ok", "ok"))
			.post("/orgs")
			.handler((c) => c.res.text("ok", "ok"))
		const code = generateRouteTreeFromApp(app)
		expect(code).toContain("export const routes")
		expect(code).toContain('"GET /orgs"')
		expect(code).toContain('"POST /orgs"')
		expect(code).not.toContain("export const handlers")
		expect(code).not.toContain("RouteHandler")
	})

	it("emits the routeTree convenience export", () => {
		const app = honey<{}>()
			.get("/health")
			.handler((c) => c.res.text("ok", "ok"))
		const code = generateRouteTreeFromApp(app)
		expect(code).toContain("export const routeTree: RouteTree")
		expect(code).toContain("root: tree")
		expect(code).toContain("routes")
	})

	it("emits declared error keys and meta as route data", () => {
		const errors = defineErrors({ email_taken: "conflict" })
		const app = honey<{}>()
			.meta<{ auth: string }>()
			.get("/users")
			.errors(errors, "email_taken")
			.meta({ auth: "required" })
			.handler((c) => c.res.text("ok", "ok"))
		const code = generateRouteTreeFromApp(app)
		expect(code).toContain('ek: ["email_taken"]')
		expect(code).toContain('"auth":"required"')
	})

	it("rejects meta JSON cannot carry", () => {
		const app = honey<{}>()
		app
			.get("/when")
			.meta({ at: new Date(0) } as never)
			.handler((c) => c.res.text("ok", "ok"))
		expect(() => generateRouteTreeFromApp(app)).toThrow(/GET \/when.*Date/)
		const nan = honey<{}>()
		nan
			.get("/n")
			.meta({ n: Number.NaN } as never)
			.handler((c) => c.res.text("ok", "ok"))
		expect(() => generateRouteTreeFromApp(nan)).toThrow(/NaN/)
	})
})

/* ---- .routeTree() with mergeTree (gateway pattern) ---- */

describe(".routeTree() with mergeTree", () => {
	it("works with live handlers from mergeTree", async () => {
		const { mergeTree } = await import("../../../src/tree.ts")

		const app1 = honey<{}>()
		app1.get("/a").handler((ctx) => ctx.res.text("ok", "from-a"))

		const app2 = honey<{}>()
		app2.get("/b").handler((ctx) => ctx.res.text("ok", "from-b"))

		const merged = mergeTree(app1.toRouteTree(), app2.toRouteTree())
		const gateway = honey<{}>().routeTree(merged)

		const client = testClient(gateway, { env: {} })
		const resA = await client.get("/a")
		expect(resA.status).toBe(200)
		expect(await resA.text()).toBe("from-a")

		const resB = await client.get("/b")
		expect(resB.status).toBe(200)
		expect(await resB.text()).toBe("from-b")
	})

	it("toRouteTree() returns a copy, never the live root", () => {
		const app = honey<{}>()
		app.get("/a").handler((c) => c.res.text("ok", "a"))
		const snap = app.toRouteTree()
		snap.root.s.a = createNode()
		expect(app.toRouteTree().root.s.a?.m).toEqual({ GET: "GET /a" })
	})
})

/* ---- meta typing — .meta<T>() flows to handler ctx ---- */

describe("routeTree meta typing", () => {
	it("ctx.meta is typed when .meta<T>() is set and no route-level .meta()", () => {
		type AppMeta = { auth: string; worker: string }

		honey<{}>()
			.meta<AppMeta>()
			.all("*")
			.handler((ctx) => {
				expectTypeOf(ctx.meta.auth).toEqualTypeOf<string>()
				expectTypeOf(ctx.meta.worker).toEqualTypeOf<string>()
				return ctx.res.text("ok", "ok")
			})
	})

	it("ctx.meta in .proxy() destination is typed from .meta<T>()", () => {
		type AppMeta = { auth: string; worker: string }

		honey<{}>()
			.meta<AppMeta>()
			.all("*")
			.proxy({
				destination: (ctx) => {
					expectTypeOf(ctx.meta.worker).toEqualTypeOf<string>()
					expectTypeOf(ctx.meta.auth).toEqualTypeOf<string>()
					return new Response("ok")
				},
			})
	})

	it("ctx.meta in catch-all after .routeTree() inherits app meta type", () => {
		type AppMeta = { auth: string; worker: string }
		const staticTree = buildStaticTree()

		honey<{}>()
			.meta<AppMeta>()
			.routeTree(staticTree)
			.all("*")
			.handler((ctx) => {
				expectTypeOf(ctx.meta.auth).toEqualTypeOf<string>()
				expectTypeOf(ctx.meta.worker).toEqualTypeOf<string>()
				return ctx.res.text("ok", "ok")
			})
	})

	it("route-level .meta() intersects with app-level meta type", () => {
		type AppMeta = { auth: string }

		honey<{}>()
			.meta<AppMeta>()
			.get("/test")
			.meta({ auth: "jwt" })
			.handler((ctx) => {
				expectTypeOf(ctx.meta.auth).toEqualTypeOf<string>()
				return ctx.res.text("ok", "ok")
			})
	})
})

/* ---- gateway delegation — leaves without a local handler go to the catch-all ---- */

describe("routeTree delegation to the gateway catch-all", () => {
	it("delegated leaf dispatches to the catch-all with its own meta", async () => {
		const app = honey<{}>()
			.routeTree(buildStaticTree())
			.all("*")
			.handler((c) => {
				const meta = (c as Record<string, unknown>)["meta"] as Record<string, unknown>
				return c.res.json("ok", { auth: meta["auth"], rateLimit: meta["rateLimit"] })
			})
		const res = await testClient(app, { env: {} }).get("/orgs")
		expect(await res.json()).toEqual({ auth: "required", rateLimit: "strict" })
	})

	it("delegated leaf without meta has no route meta", async () => {
		const app = honey<{}>()
			.routeTree(buildStaticTree())
			.all("*")
			.handler((c) => {
				const meta = (c as Record<string, unknown>)["meta"] as Record<string, unknown> | undefined
				return c.res.json("ok", { hasWorker: meta?.["worker"] !== undefined })
			})
		expect(await (await testClient(app, { env: {} }).get("/health")).json()).toEqual({ hasWorker: false })
	})

	it("a local handler wins over delegation", async () => {
		const app = honey<{}>()
			.routeTree(buildStaticTree())
			.get("/orgs")
			.handler((c) => c.res.text("ok", "handled"))
			.all("*")
			.handler((c) => c.res.text("ok", "catch-all"))
		expect(await (await testClient(app, { env: {} }).get("/orgs")).text()).toBe("handled")
		expect(await (await testClient(app, { env: {} }).get("/health")).text()).toBe("catch-all")
	})

	it("unknown paths 404 — for GET and HEAD — even with a catch-all", async () => {
		const app = honey<{}>()
			.routeTree(buildStaticTree())
			.all("*")
			.handler((c) => c.res.text("ok", "should-not-reach"))
		const client = testClient(app, { env: {} })
		expect((await client.get("/unknown")).status).toBe(404)
		expect((await app.fetch(new Request("http://x/unknown", { method: "HEAD" }), {})).status).toBe(404)
	})

	it("unmatched route without a catch-all returns 404", async () => {
		const app = honey<{}>().routeTree(buildStaticTree())
		expect((await testClient(app, { env: {} }).get("/unknown")).status).toBe(404)
	})

	it("wrong method on a tree route returns 405 with a catch-all present", async () => {
		const app = honey<{}>()
			.routeTree(buildStaticTree())
			.all("*")
			.handler((c) => c.res.text("ok", "should-not-reach"))
		expect((await testClient(app, { env: {} }).delete("/orgs")).status).toBe(405)
	})

	it("works with proxy", async () => {
		const app = honey<{}>()
			.routeTree(buildStaticTree())
			.all("*")
			.proxy({
				destination: (ctx) => {
					const meta = (ctx as Record<string, unknown>)["meta"] as Record<string, unknown>
					return new Response(JSON.stringify({ worker: meta?.["auth"] }))
				},
			})
		expect(await (await testClient(app, { env: {} }).get("/orgs")).json()).toEqual({ worker: "required" })
	})

	it("middleware runs before the delegated handler", async () => {
		const withToken = createMiddleware(async (_ctx, next) => next({ token: "abc" }))
		const app = honey<{}>()
			.routeTree(buildStaticTree())
			.use(withToken)
			.all("*")
			.handler((c) => {
				const meta = (c as Record<string, unknown>)["meta"] as Record<string, unknown>
				return c.res.json("ok", { auth: meta?.["auth"], token: c.token })
			})
		expect(await (await testClient(app, { env: {} }).get("/orgs")).json()).toEqual({ auth: "required", token: "abc" })
	})

	it("params from the tree match are available in the delegated handler", async () => {
		const tree = treeOf([["GET", "/users/:id", { mt: { worker: "users" } }]])
		const app = honey<{}>()
			.routeTree(tree)
			.all("*")
			.handler((c) => {
				const meta = (c as Record<string, unknown>)["meta"] as Record<string, unknown>
				return c.res.json("ok", { id: c.params["id"], pattern: c.routePattern, worker: meta["worker"] })
			})
		const res = await testClient(app, { env: {} }).get("/users/42")
		expect(await res.json()).toEqual({ id: "42", pattern: "/users/:id", worker: "users" })
	})

	it("meta-driven taps read the delegated route's meta", async () => {
		const seen: unknown[] = []
		const tree = treeOf([["GET", "/a", { mt: { audit: "a-route" } }]])
		const app = honey<{}>().routeTree(tree)
		app.tap("audit", (_ctx, v) => {
			seen.push(v)
		})
		app.all("/*").handler((c) => c.res.text("ok", "ok"))
		const res = await app.fetch(new Request("http://x/a"), {})
		expect(res.status).toBe(200)
		await new Promise((r) => setTimeout(r, 5))
		expect(seen).toEqual(["a-route"])
	})

	it("a catch-all with nothing to delegate means the tree is stale", () => {
		const app = honey<{}>().routeTree(treeOf([["GET", "/a"]]))
		app.get("/a").handler((c) => c.res.text("ok", "a"))
		app.all("/*").handler((c) => c.res.text("ok", "spa"))
		expect(() => app.fetch(new Request("http://x/a"), {})).toThrow(/missing from the loaded route tree/)
	})
})
