/* @generated by honey — do not edit. checksum: f5864066fe13 */
import type { TreeNode, RouteHandler, RouteTree } from "@lovrozagar/honey/tree"

const E = Object.create(null) as Record<string, TreeNode>
function N(s: Record<string, TreeNode>, m: Record<string, RouteHandler> | null = null, d: TreeNode["d"] = null, w: { n: string; m: Record<string, RouteHandler> } | null = null): TreeNode {
	return { s, d, w: w as TreeNode["w"], m: m as TreeNode["m"], ws: null }
}
function S(o: Record<string, TreeNode>): Record<string, TreeNode> {
	return Object.assign(Object.create(null), o) as Record<string, TreeNode>
}
const FN = null as unknown as RouteHandler["fn"]

const T0 = "invalid_token"
const T1 = "expired_token"
const P0 = "GET /health"
const P1 = "GET /docs"
const P2 = "GET /feed"
const T2 = "forbidden"
const P3 = "GET /account"
const P4 = "POST /account/settings"
const P5 = "POST /resources"
const T3 = "not_found"
const P6 = "GET /resources/:resourceId"
const P7 = "DELETE /resources/:resourceId"
const P8 = "GET /openapi.json"
const P9 = "GET /openapi.yml"
const P10 = "GET /openapi.yaml"
const P11 = "GET /reference"
const P12 = "GET /manifest.json"
const A0 = [T0,T1]
const A1 = [T0,T1,T2]
const A2 = [T0,T1,T3,T2]

const H0: RouteHandler = { bek: null, fn: FN, mw: [], ek: new Set(A0), mt: null }
const H1: RouteHandler = { bek: null, fn: FN, mw: [], ek: new Set(A0), mt: null }
const H2: RouteHandler = { bek: null, fn: FN, mw: [], ek: new Set(A0), mt: null }
const H3: RouteHandler = { bek: null, fn: FN, mw: [], ek: new Set(A1), mt: null }
const H4: RouteHandler = { bek: null, fn: FN, mw: [], ek: new Set(A1), mt: null }
const H5: RouteHandler = { bek: null, fn: FN, mw: [], ek: new Set([T0,T1,T2,"rate_limited"]), mt: null }
const H6: RouteHandler = { bek: null, fn: FN, mw: [], ek: new Set(A2), mt: null }
const H7: RouteHandler = { bek: null, fn: FN, mw: [], ek: new Set(A2), mt: null }
const H8: RouteHandler = { bek: null, fn: FN, mw: [], ek: new Set(A0), mt: null }
const H9: RouteHandler = { bek: null, fn: FN, mw: [], ek: new Set(A0), mt: null }
const H10: RouteHandler = { bek: null, fn: FN, mw: [], ek: new Set(A0), mt: null }
const H11: RouteHandler = { bek: null, fn: FN, mw: [], ek: new Set(A0), mt: null }
const H12: RouteHandler = { bek: null, fn: FN, mw: [], ek: new Set(A0), mt: null }

export const tree: TreeNode = N(S({ "health": N(E, { GET: H0 }), "docs": N(E, { GET: H1 }), "feed": N(E, { GET: H2 }), "account": N(S({ "settings": N(E, { POST: H4 }) }), { GET: H3 }), "resources": N(E, { POST: H5 }, { n: "resourceId", c: N(E, { GET: H6, DELETE: H7 }) }), "openapi.json": N(E, { GET: H8 }), "openapi.yml": N(E, { GET: H9 }), "openapi.yaml": N(E, { GET: H10 }), "reference": N(E, { GET: H11 }), "manifest.json": N(E, { GET: H12 }) }))

export const handlers: Record<string, RouteHandler> = {
	[P0]: H0,
	[P1]: H1,
	[P2]: H2,
	[P3]: H3,
	[P4]: H4,
	[P5]: H5,
	[P6]: H6,
	[P7]: H7,
	[P8]: H8,
	[P9]: H9,
	[P10]: H10,
	[P11]: H11,
	[P12]: H12
}

export type RouteSelector = typeof P7 | typeof P3 | typeof P1 | typeof P2 | typeof P0 | typeof P6 | typeof P4 | typeof P5
export const routeTree: RouteTree = { root: tree, meta: {}, handlers }
