/* @generated by honey — do not edit. checksum: 829a6ccab5f8 */
import type { RouteTree, TreeNode } from "@lovrozagar/honey/tree"

function S<T>(o: Record<string, T>): Record<string, T> {
	return Object.assign(Object.create(null) as Record<string, T>, o)
}
function N(s: Record<string, TreeNode> = S({}), m: Record<string, string> | null = null, d: TreeNode["d"] = null, w: TreeNode["w"] = null, ws: string | null = null): TreeNode {
	return { d, m, s, w, ws }
}

const T0 = "invalid_token"
const T1 = "expired_token"
const P0 = "GET /health"
const P1 = "GET /docs"
const P2 = "GET /feed"
const T2 = "forbidden"
const P3 = "GET /account"
const P4 = "POST /account/settings"
const P5 = "POST /resources"
const T3 = "not_found"
const P6 = "GET /resources/:resourceId"
const P7 = "DELETE /resources/:resourceId"
const A0 = [T0,T1]
const A1 = [T0,T1,T2]
const A2 = [T0,T1,T3,T2]

export const tree: TreeNode = N(S({ "health": N(undefined, S({ "GET": P0 })), "docs": N(undefined, S({ "GET": P1 })), "feed": N(undefined, S({ "GET": P2 })), "account": N(S({ "settings": N(undefined, S({ "POST": P4 })) }), S({ "GET": P3 })), "resources": N(undefined, S({ "POST": P5 }), { n: "resourceId", c: N(undefined, S({ "GET": P6, "DELETE": P7 })) }) }))

export const routes: RouteTree["routes"] = S({
	[P0]: { ek: A0 },
	[P1]: { ek: A0 },
	[P2]: { ek: A0 },
	[P3]: { ek: A1 },
	[P4]: { ek: A1 },
	[P5]: { ek: [T0,T1,T2,"rate_limited"] },
	[P6]: { ek: A2 },
	[P7]: { ek: A2 }
})

export type RouteSelector = typeof P7 | typeof P3 | typeof P1 | typeof P2 | typeof P0 | typeof P6 | typeof P4 | typeof P5
export const routeTree: RouteTree = { v: 2, root: tree, routes, meta: {} }
