/* @generated by honey — do not edit. checksum: a575d3f8f0b0 */
import { assembleRouteTree, type PackedRouteTable, type RouteHandler, type RouteTree, type TreeNode } from "@lovrozagar/honey/tree"

declare const P: readonly ["GET /health","GET /docs","GET /feed","GET /account","POST /account/settings","POST /resources","GET /resources/:resourceId","DELETE /resources/:resourceId","GET /openapi.json","GET /openapi.yml","GET /openapi.yaml","GET /reference","GET /manifest.json"]
const D: PackedRouteTable = {"s":["GET /health","GET /docs","GET /feed","GET /account","POST /account/settings","POST /resources","GET /resources/:resourceId","DELETE /resources/:resourceId","GET /openapi.json","GET /openapi.yml","GET /openapi.yaml","GET /reference","GET /manifest.json"],"k":["invalid_token","expired_token"],"e":{"t":[[],["forbidden"],["forbidden","rate_limited"],["not_found","forbidden"]],"x":[0,0,0,1,1,2,3,3,0,0,0,0,0]},"i":{"t":[null,{"q":{"t":"o","p":{"page":{"d":1,"t":"n"}}}},{"j":{"t":"o","p":{"notifications":{"t":"b"},"theme":{"t":"s","en":["dark","light"]}},"r":["notifications","theme"]}},{"j":{"t":"o","p":{"name":{"t":"s"},"type":{"t":"s","en":["doc","image","video"]}},"r":["name","type"]}}],"x":[0,0,1,0,2,3,0,0,0,0,0,0,0]}}
export const routeTree: RouteTree = assembleRouteTree(D)
export const tree: TreeNode = routeTree.root
export const handlers: Record<string, RouteHandler> = routeTree.handlers ?? {}
export type RouteSelector = typeof P[0] | typeof P[1] | typeof P[2] | typeof P[3] | typeof P[4] | typeof P[5] | typeof P[6] | typeof P[7]
