/* @generated by honey — do not edit. checksum: 44deffc63898 */
import type { HoneyContext, WithOutput, HoneyError } from "honey"

export type BaseCtx = HoneyContext<{ JWT_SECRET: string; REDIS_URL: string }> & { realtime: { publish: (topic: string, data: unknown) => void }; cache: { get: (_k: string) => null | string; set: (_k: string, _v: string) => void }; session: { orgId: string; permissions: string[]; userId: string } }

export type RouteSelector = "DELETE /resources/:resourceId" | "GET /account" | "GET /docs" | "GET /feed" | "GET /health" | "GET /resources/:resourceId" | "POST /account/settings" | "POST /resources"

declare module "honey" {
	interface HoneyCodegen {
		routeSelector: RouteSelector
	}
}

export type Routes = {
	"/health": {
		get: {
			ctx: WithOutput<BaseCtx & { readonly errors: { expired_token: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; invalid_token: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError } }, {}>
			errors: "expired_token" | "invalid_token"
			errorShapes: { expired_token: null; invalid_token: null }
			errorsByStatus: { 401: null | null }
			input: {}
			meta: {}
			output: {}
		}
	}
	"/docs": {
		get: {
			ctx: WithOutput<BaseCtx & { readonly errors: { expired_token: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; invalid_token: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError } }, {}>
			errors: "expired_token" | "invalid_token"
			errorShapes: { expired_token: null; invalid_token: null }
			errorsByStatus: { 401: null | null }
			input: {}
			meta: {}
			output: {}
		}
	}
	"/feed": {
		get: {
			ctx: WithOutput<BaseCtx & { input: { search: { page: number } }; readonly errors: { expired_token: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; invalid_token: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError } }, {}>
			errors: "expired_token" | "invalid_token"
			errorShapes: { expired_token: null; invalid_token: null }
			errorsByStatus: { 401: null | null }
			input: { search: { page: number } }
			meta: {}
			output: {}
		}
	}
	"/account": {
		get: {
			ctx: WithOutput<BaseCtx & { readonly errors: { expired_token: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; forbidden: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; invalid_token: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError } }, {}>
			errors: "expired_token" | "forbidden" | "invalid_token"
			errorShapes: { expired_token: null; forbidden: null; invalid_token: null }
			errorsByStatus: { 401: null | null; 403: null }
			input: {}
			meta: {}
			output: {}
		}
	}
	"/account/settings": {
		post: {
			ctx: WithOutput<BaseCtx & { input: { json: { notifications: boolean; theme: "dark" | "light" } }; readonly errors: { expired_token: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; forbidden: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; invalid_token: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError } }, {}>
			errors: "expired_token" | "forbidden" | "invalid_token"
			errorShapes: { expired_token: null; forbidden: null; invalid_token: null }
			errorsByStatus: { 401: null | null; 403: null }
			input: { json: { notifications: boolean; theme: "dark" | "light" } }
			meta: {}
			output: {}
		}
	}
	"/resources": {
		post: {
			ctx: WithOutput<BaseCtx & { input: { json: { name: string; type: "doc" | "image" | "video" } }; readonly errors: { expired_token: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; forbidden: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; invalid_token: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; rate_limited: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError } }, {}>
			errors: "expired_token" | "forbidden" | "invalid_token" | "rate_limited"
			errorShapes: { expired_token: null; forbidden: null; invalid_token: null; rate_limited: null }
			errorsByStatus: { 401: null | null; 403: null; 429: null }
			input: { json: { name: string; type: "doc" | "image" | "video" } }
			meta: {}
			output: {}
		}
	}
	"/resources/:resourceId": {
		get: {
			ctx: WithOutput<BaseCtx & { readonly params: { resourceId: string }; readonly errors: { expired_token: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; forbidden: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; invalid_token: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; not_found: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError } }, {}>
			errors: "expired_token" | "forbidden" | "invalid_token" | "not_found"
			errorShapes: { expired_token: null; forbidden: null; invalid_token: null; not_found: null }
			errorsByStatus: { 401: null | null; 403: null; 404: null }
			input: {}
			meta: {}
			output: {}
		}
		delete: {
			ctx: WithOutput<BaseCtx & { readonly params: { resourceId: string }; readonly errors: { expired_token: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; forbidden: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; invalid_token: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; not_found: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError } }, {}>
			errors: "expired_token" | "forbidden" | "invalid_token" | "not_found"
			errorShapes: { expired_token: null; forbidden: null; invalid_token: null; not_found: null }
			errorsByStatus: { 401: null | null; 403: null; 404: null }
			input: {}
			meta: {}
			output: {}
		}
	}
	"/openapi.json": {
		get: {
			ctx: WithOutput<BaseCtx & { readonly errors: { expired_token: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; invalid_token: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError } }, {}>
			errors: "expired_token" | "invalid_token"
			errorShapes: { expired_token: null; invalid_token: null }
			errorsByStatus: { 401: null | null }
			input: {}
			meta: {}
			output: {}
		}
	}
	"/openapi.yml": {
		get: {
			ctx: WithOutput<BaseCtx & { readonly errors: { expired_token: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; invalid_token: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError } }, {}>
			errors: "expired_token" | "invalid_token"
			errorShapes: { expired_token: null; invalid_token: null }
			errorsByStatus: { 401: null | null }
			input: {}
			meta: {}
			output: {}
		}
	}
	"/openapi.yaml": {
		get: {
			ctx: WithOutput<BaseCtx & { readonly errors: { expired_token: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; invalid_token: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError } }, {}>
			errors: "expired_token" | "invalid_token"
			errorShapes: { expired_token: null; invalid_token: null }
			errorsByStatus: { 401: null | null }
			input: {}
			meta: {}
			output: {}
		}
	}
	"/reference": {
		get: {
			ctx: WithOutput<BaseCtx & { readonly errors: { expired_token: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; invalid_token: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError } }, {}>
			errors: "expired_token" | "invalid_token"
			errorShapes: { expired_token: null; invalid_token: null }
			errorsByStatus: { 401: null | null }
			input: {}
			meta: {}
			output: {}
		}
	}
	"/manifest.json": {
		get: {
			ctx: WithOutput<BaseCtx & { readonly errors: { expired_token: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; invalid_token: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError } }, {}>
			errors: "expired_token" | "invalid_token"
			errorShapes: { expired_token: null; invalid_token: null }
			errorsByStatus: { 401: null | null }
			input: {}
			meta: {}
			output: {}
		}
	}
}

export type RouteCtx<
	TPath extends keyof Routes,
	TMethod extends keyof Routes[TPath] & string
> = Routes[TPath][TMethod] extends { ctx: infer C } ? C : never

export type RouteInput<
	TPath extends keyof Routes,
	TMethod extends keyof Routes[TPath] & string
> = Routes[TPath][TMethod] extends { input: infer I } ? I : never

export type RouteOutput<
	TPath extends keyof Routes,
	TMethod extends keyof Routes[TPath] & string
> = Routes[TPath][TMethod] extends { output: infer O } ? O : never

export type RouteErrors<
	TPath extends keyof Routes,
	TMethod extends keyof Routes[TPath] & string
> = Routes[TPath][TMethod] extends { errors: infer E } ? E : never

export type RouteErrorShapes<
	TPath extends keyof Routes,
	TMethod extends keyof Routes[TPath] & string
> = Routes[TPath][TMethod] extends { errorShapes: infer S } ? S : never

export type RouteErrorsByStatus<
	TPath extends keyof Routes,
	TMethod extends keyof Routes[TPath] & string
> = Routes[TPath][TMethod] extends { errorsByStatus: infer S } ? S : never

export type RouteMeta<
	TPath extends keyof Routes,
	TMethod extends keyof Routes[TPath] & string
> = Routes[TPath][TMethod] extends { meta: infer M } ? M : never
