import { existsSync, mkdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs"
import { join, resolve } from "node:path"
import { afterEach, beforeEach, describe, expect, it } from "vitest"
import { generateAndWrite, resolveHoneyConfig } from "../../../src/plugin.ts"

const TEMP_ROOT = resolve(import.meta.dirname, "../../../.tmp-generate-write-test")

function writeApp(dir: string, extraRoute = false): void {
	mkdirSync(join(dir, "src"), { recursive: true })
	const extra = extraRoute ? '\n  .get("/extra").handler((ctx) => ctx.res.text("ok", "x"))' : ""
	writeFileSync(
		join(dir, "src/app.ts"),
		[
			'import { honey } from "@lovrozagar/honey"',
			'import * as z from "zod"',
			"",
			"export const app = honey()",
			'  .get("/health").handler((ctx) => ctx.res.text("ok", "ok"))',
			'  .post("/items")',
			"  .input({ json: z.object({ name: z.string() }) })",
			'  .handler((ctx) => ctx.res.json("ok", { name: ctx.input.json.name }))',
			extra,
			"",
		].join("\n"),
		"utf-8",
	)
}

describe("generateAndWrite", () => {
	beforeEach(() => {
		mkdirSync(TEMP_ROOT, { recursive: true })
		writeApp(TEMP_ROOT)
	})

	afterEach(() => {
		rmSync(TEMP_ROOT, { force: true, recursive: true })
	})

	it("writes tree, manifest, openapi json + yaml", async () => {
		const config = resolveHoneyConfig({
			app: "src/app.ts",
			codegen: {
				manifest: true,
				openApi: { title: "Gen", version: "1.0.0" },
				tree: true,
			},
		})
		await generateAndWrite(config, TEMP_ROOT)

		const tree = readFileSync(join(TEMP_ROOT, "src/_gen/routes.gen.ts"), "utf-8")
		expect(tree).toContain("@generated by honey")
		expect(tree).toContain("health")
		expect(tree).toContain("items")

		const manifest = JSON.parse(readFileSync(join(TEMP_ROOT, "src/_gen/manifest.gen.json"), "utf-8")) as {
			routes: Array<{ path: string }>
		}
		expect(manifest.routes.some((r) => r.path === "/health")).toBe(true)

		const spec = JSON.parse(readFileSync(join(TEMP_ROOT, "src/_gen/openapi.gen.json"), "utf-8")) as {
			info: { title: string }
			openapi: string
			paths: Record<string, unknown>
		}
		expect(spec.openapi).toBe("3.1.0")
		expect(spec.info.title).toBe("Gen")
		expect(spec.paths["/health"]).toBeDefined()

		const yaml = readFileSync(join(TEMP_ROOT, "src/_gen/openapi.gen.yaml"), "utf-8")
		expect(yaml).toContain("title: Gen")
		expect(yaml).toContain("/health")
	})

	it("skips rewrite when the content is unchanged", async () => {
		const config = resolveHoneyConfig({
			app: "src/app.ts",
			codegen: { tree: true },
		})
		await generateAndWrite(config, TEMP_ROOT)
		const path = join(TEMP_ROOT, "src/_gen/routes.gen.ts")
		const first = statSync(path).mtimeMs
		await new Promise((r) => setTimeout(r, 20))
		await generateAndWrite(config, TEMP_ROOT)
		expect(statSync(path).mtimeMs).toBe(first)
	})

	it("rewrites tree after a new route is added", async () => {
		const config = resolveHoneyConfig({
			app: "src/app.ts",
			codegen: { tree: true },
		})
		await generateAndWrite(config, TEMP_ROOT)
		expect(readFileSync(join(TEMP_ROOT, "src/_gen/routes.gen.ts"), "utf-8")).not.toContain("extra")

		writeApp(TEMP_ROOT, true)
		await generateAndWrite(config, TEMP_ROOT)
		expect(readFileSync(join(TEMP_ROOT, "src/_gen/routes.gen.ts"), "utf-8")).toContain("extra")
	})

	it("writes TypeScript SDK files when sdk is enabled", async () => {
		const config = resolveHoneyConfig({
			app: "src/app.ts",
			codegen: { sdk: true, tree: false },
		})
		await generateAndWrite(config, TEMP_ROOT)
		expect(existsSync(join(TEMP_ROOT, "src/_gen/sdk.client.gen.ts"))).toBe(true)
		expect(existsSync(join(TEMP_ROOT, "src/_gen/sdk.types.gen.ts"))).toBe(true)
		expect(existsSync(join(TEMP_ROOT, "src/_gen/sdk.index.gen.ts"))).toBe(true)
		expect(readFileSync(join(TEMP_ROOT, "src/_gen/sdk.client.gen.ts"), "utf-8")).toContain("@generated by honey")
	})

	it("throws when manifest is requested without an app", async () => {
		const config = resolveHoneyConfig({
			codegen: { manifest: true, tree: false },
		})
		await expect(generateAndWrite(config, TEMP_ROOT)).rejects.toThrow(/No app configured/)
	})

	it("documents downstream bodies in a gateway built with mergeTree", async () => {
		/* downstream service: the live app carries the schemas */
		const down = join(TEMP_ROOT, "down")
		writeApp(down)
		/* gateway: route-tree merges the downstream app; the app serves the generated tree */
		const gw = join(TEMP_ROOT, "gw")
		mkdirSync(join(gw, "src"), { recursive: true })
		writeFileSync(
			join(gw, "src/route-tree.ts"),
			[
				'import { mergeTree } from "@lovrozagar/honey"',
				'import { app as downApp } from "../../down/src/app.ts"',
				"",
				'export const tree = mergeTree([downApp.toRouteTree(), { worker: "down" }])',
				"",
			].join("\n"),
			"utf-8",
		)
		writeFileSync(
			join(gw, "src/app.ts"),
			[
				'import { honey } from "@lovrozagar/honey"',
				'import { routeTree } from "./_gen/routes.gen.ts"',
				"",
				"export const app = honey().routeTree(routeTree)",
				"",
			].join("\n"),
			"utf-8",
		)
		/* the gateway app imports its generated tree, so a first tree-only pass must exist */
		const treeOnly = resolveHoneyConfig({ app: "src/app.ts", codegen: { mergeTree: "src/route-tree.ts", tree: true } })
		await generateAndWrite(treeOnly, gw)

		const config = resolveHoneyConfig({
			app: "src/app.ts",
			codegen: { mergeTree: "src/route-tree.ts", openApi: { title: "Gateway", version: "1.0.0" }, tree: true },
		})
		await generateAndWrite(config, gw)

		const tree = readFileSync(join(gw, "src/_gen/routes.gen.ts"), "utf-8")
		expect(tree).toContain("items")
		expect(tree).not.toMatch(/\biv:/)

		const spec = JSON.parse(readFileSync(join(gw, "src/_gen/openapi.gen.json"), "utf-8")) as {
			paths: Record<string, { post?: { requestBody?: { content: Record<string, unknown> } } }>
		}
		expect(spec.paths["/items"]?.post?.requestBody?.content["application/json"]).toBeDefined()
	})

	it("throws when the app file does not export a Honey app", async () => {
		writeFileSync(join(TEMP_ROOT, "src/app.ts"), "export const app = { not: true }\n", "utf-8")
		const config = resolveHoneyConfig({
			app: "src/app.ts",
			codegen: { manifest: true, tree: false },
		})
		await expect(generateAndWrite(config, TEMP_ROOT)).rejects.toThrow(/Expected Honey app/)
	})

	it("evaluates the app once per generation, and its top-level serve() binds nothing", async () => {
		const log = join(TEMP_ROOT, "evaluations.log")
		writeFileSync(
			join(TEMP_ROOT, "src/app.ts"),
			[
				'import { appendFileSync } from "node:fs"',
				'import { honey } from "@lovrozagar/honey"',
				`appendFileSync(${JSON.stringify(log)}, "x")`,
				'export const app = honey().get("/health").handler((ctx) => ctx.res.text("ok", "ok"))',
				"const handle = await app.serve({ port: 45_986 })",
				`appendFileSync(${JSON.stringify(log)}, handle.url.includes("45986") ? "s" : "?")`,
			].join("\n"),
		)
		const config = resolveHoneyConfig({
			app: "src/app.ts",
			codegen: { manifest: true, openApi: { title: "T", version: "1" }, tree: true },
		})
		await generateAndWrite(config, TEMP_ROOT)
		expect(readFileSync(log, "utf-8")).toBe("xs")
		await expect(fetch("http://127.0.0.1:45986/health")).rejects.toThrow()
	})
})
