/* auto-generated by @ecomet/honey — do not edit */

import type { HoneyContext } from "@ecomet/honey"

export type BaseCtx = HoneyContext<unknown>

export type Routes = {
	"/health": {
		get: {
			ctx: BaseCtx
			errors: never
			input: {}
			meta: {}
			output: {}
		}
	}
	"/users/:id": {
		get: {
			ctx: BaseCtx & { readonly params: { id: string } }
			errors: never
			input: {}
			meta: {}
			output: {}
		}
	}
	"/echo": {
		post: {
			ctx: BaseCtx
			errors: never
			input: {}
			meta: {}
			output: {}
		}
	}
}
