/* auto-generated by @ecomet/honey — do not edit */

import type { InferCtx } from "@ecomet/honey"
import type { base } from "./context"

export type BaseCtx = Omit<InferCtx<typeof base>, "json">

export type Routes = {
	"/hello": {
		get: {
			ctx: BaseCtx & { input: { search: { q: string } } }
			input: { search: { q: string } }
			output: { "application/json": { ok: { q: string } } }
		}
		post: {
			ctx: BaseCtx & { input: { json: { q: string } } }
			input: { json: { q: string } }
			output: { "application/json": { ok: { q: string } } }
		}
	}
}

export type HelloGetCtx = Routes["/hello"]["get"]["ctx"]
export type HelloPostCtx = Routes["/hello"]["post"]["ctx"]
