/* @generated by honey — do not edit. checksum: d95aa911e861 */
type _ErrField = { error_key: string; message: string; path: string }
type _ErrEnvelope<TStatus extends number, TKey extends string> = {
	error_key: TKey
	fields: Record<string, _ErrField[]>
	message: string
	status: TStatus
	status_key: string
	success: false
}

type _Errs0 = { 400: _ErrEnvelope<400, "validation_error">; 401: _ErrEnvelope<401, "unauthorized"> }

type _ExpandShallow<T> = T extends object ? { [K in keyof T]: T[K] } & {} : T
type _Expand<T> = T extends object ? { [K in keyof T]: _ExpandShallow<T[K]> } & {} : T
type _Res0 = { id: string }

export type SDKResult<T, TErrorsByStatus = never> =
	| { data: T; error: null; response: Response; status: number }
	| ([TErrorsByStatus] extends [never]
		? { data: null; error: unknown; response: Response; status: number }
		: { [S in keyof TErrorsByStatus & number]: { data: null; error: TErrorsByStatus[S]; response: Response; status: S } }[keyof TErrorsByStatus & number])

export type TypedWebSocket = {
	close(code?: number, reason?: string): void
	off(event: "close" | "error" | "message" | "open", handler: (...args: never[]) => void): void
	on(event: "close", handler: (code: number, reason: string) => void): void
	on(event: "error", handler: (error: unknown) => void): void
	on(event: "message", handler: (data: string) => void): void
	on(event: "open", handler: () => void): void
	readonly readyState: number
	send(data: ArrayBuffer | ArrayBufferView | object | string): void
}

export type Demo2SDKConfig<TThrow extends boolean = false> = {
	baseURL: string
	buildSearchParams?: (query: Record<string, unknown>) => URLSearchParams
	credentials?: RequestCredentials
	fetch?: typeof fetch
	headers?: Record<string, string> | ((ctx: { method: string; path: string }) => Record<string, string | undefined> | Promise<Record<string, string | undefined>>)
	invalidation?: { maxSourcesPerTarget?: number; staleMaxEntries?: number; staleTime: number }
	maxErrorMessageChars?: number
	mode?: RequestMode
	onRequest?: Array<(ctx: { body?: BodyInit; headers: Headers; invalidatedBy?: string[]; isStale?: boolean; method: string; path: string; selector?: string; state: Record<string, unknown>; url: string }) => void | Promise<void>>
	onResponse?: Array<(ctx: { invalidatedBy?: string[]; isRetry: boolean; isStale?: boolean; method: string; path: string; request: Request; response: Response; retry: () => Promise<Response>; selector?: string; state: Record<string, unknown>; url: string }) => Response | undefined | Promise<Response | undefined>>
	onAuthExpired?: () => Promise<string | null>
	authHeaderName?: string
	authHeaderPrefix?: string
	onLog?: (entry: _LogEntry) => void
	sortSearchParams?: boolean
	sseMaxBufferChars?: number
	state?: Record<string, unknown>
	throwOnError?: TThrow
	timeout?: number
}

export type _LogEntry = { level: "debug" | "info" | "warn" | "error"; event: "request_start" | "response_received" | "error" | "hook_executed"; operation: string; duration_ms: number; status?: number; error?: unknown }
export type _HttpOpts = { cookies?: Record<string, string>; headers?: Record<string, string>; idempotencyKey?: string; signal?: AbortSignal; timeout?: number }
export type _SseOpts = { cookies?: Record<string, string>; headers?: Record<string, string>; lastEventId?: string; signal?: AbortSignal; timeout?: number }
export type _WsOpts = { protocols?: string | string[]; reconnectToken?: string }

export interface Demo2SDK<TThrow extends boolean = false> {
	state: Record<string, unknown>
	dispose(): void
	input: {
		createForm(input: { form: { password: string; username: string } } & _HttpOpts): TThrow extends true ? Promise<{ token: string }> : Promise<SDKResult<{ token: string }, _Expand<_Errs0>>>
		createJson(input: { json: { email: string; name: string } } & _HttpOpts): TThrow extends true ? Promise<_Expand<_Res0>> : Promise<SDKResult<_Expand<_Res0>, _Expand<_Errs0>>>
		none(input?: _HttpOpts): TThrow extends true ? Promise<{ ping: "pong" }> : Promise<SDKResult<{ ping: "pong" }, _Expand<_Errs0>>>
		search(input: { search: { limit: number; page: number; q?: string } } & _HttpOpts): TThrow extends true ? Promise<{ results: string[] }> : Promise<SDKResult<{ results: string[] }, _Expand<_Errs0>>>
	}
	resources: {
		create(input: { json: { name: string } } & _HttpOpts): TThrow extends true ? Promise<_Expand<_Res0>> : Promise<SDKResult<_Expand<_Res0>, _Expand<_Errs0>>>
		"delete"(input: { params: { id: string } } & _HttpOpts): TThrow extends true ? Promise<void> : Promise<SDKResult<void, _Expand<_Errs0>>>
		list(input?: _HttpOpts): TThrow extends true ? Promise<{ items: string[] }> : Promise<SDKResult<{ items: string[] }, _Expand<_Errs0>>>
		patch(input: { params: { id: string }; json: { name?: string } } & _HttpOpts): TThrow extends true ? Promise<_Expand<_Res0>> : Promise<SDKResult<_Expand<_Res0>, _Expand<_Errs0>>>
		update(input: { params: { id: string }; json: { name: string } } & _HttpOpts): TThrow extends true ? Promise<{ id: string; name: string }> : Promise<SDKResult<{ id: string; name: string }, _Expand<_Errs0>>>
	}
	ws: {
		chat(input: { params: { channelId: string } } & _WsOpts): TypedWebSocket
		echo(input?: _WsOpts): TypedWebSocket
		joinRoom(input: { search: { roomId: string } } & _WsOpts): TypedWebSocket
		reconnect(input?: _WsOpts): TypedWebSocket
	}
}
