/* @generated by honey — do not edit. checksum: e3d81aca4234 */
import type { HoneyContext, WithOutput, HoneyError } from "honey"

export type BaseCtx = HoneyContext<{ API_KEY: string; DATABASE_URL: string }> & { realtime: { publish: (topic: string, data: unknown) => void }; logger: { info: (_msg: string) => void }; user: { id: string; role: "admin" | "member" } }

export type RouteSelector = "DELETE /methods/resource/:id" | "DELETE /out/no-content/:id" | "DELETE /status/no-content" | "GET /in/cookies" | "GET /in/headers" | "GET /in/none" | "GET /in/params/:orgId/members/:memberId" | "GET /in/search" | "GET /in/search-cookies-headers" | "GET /methods/resource" | "GET /out/binary" | "GET /out/csv" | "GET /out/html" | "GET /out/sse" | "GET /out/text" | "GET /out/xml" | "GET /status/ok" | "GET /stream/events" | "GET /stream/filtered" | "PATCH /methods/resource/:id" | "POST /in/form" | "POST /in/form-headers-cookies" | "POST /in/json" | "POST /in/json-cookies" | "POST /in/json-headers" | "POST /in/json-search" | "POST /methods/resource" | "POST /out/multi-status" | "POST /out/ok-or-accepted" | "POST /rs/form-upload" | "POST /rs/ingest" | "POST /rs/upload" | "POST /status/accepted" | "POST /status/created" | "PUT /in/all/:resourceId" | "PUT /methods/resource/:id"

declare module "honey" {
	interface HoneyCodegen {
		routeSelector: RouteSelector
	}
}

export type Routes = {
	"/in/json": {
		post: {
			ctx: WithOutput<BaseCtx & { input: { json: { email: string; name: string } }; readonly errors: { unauthorized: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; validation_error: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError } }, { "application/json": { created: { id: string } } }>
			errors: "unauthorized" | "validation_error"
			errorShapes: { unauthorized: null; validation_error: null }
			errorsByStatus: { 400: null; 401: null }
			input: { json: { email: string; name: string } }
			meta: { operationId: "input.createJson"; tags: ["input"] }
			output: { "application/json": { created: { id: string } } }
		}
	}
	"/in/form": {
		post: {
			ctx: WithOutput<BaseCtx & { input: { form: { password: string; username: string } }; readonly errors: { unauthorized: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; validation_error: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError } }, { "application/json": { ok: { token: string } } }>
			errors: "unauthorized" | "validation_error"
			errorShapes: { unauthorized: null; validation_error: null }
			errorsByStatus: { 400: null; 401: null }
			input: { form: { password: string; username: string } }
			meta: { operationId: "input.createForm"; tags: ["input"] }
			output: { "application/json": { ok: { token: string } } }
		}
	}
	"/in/search": {
		get: {
			ctx: WithOutput<BaseCtx & { input: { search: { limit: number; page: number; q?: string | undefined } }; readonly errors: { unauthorized: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; validation_error: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError } }, { "application/json": { ok: { results: string[] } } }>
			errors: "unauthorized" | "validation_error"
			errorShapes: { unauthorized: null; validation_error: null }
			errorsByStatus: { 400: null; 401: null }
			input: { search: { limit: number; page: number; q?: string | undefined } }
			meta: { operationId: "input.search"; tags: ["input"] }
			output: { "application/json": { ok: { results: string[] } } }
		}
	}
	"/in/headers": {
		get: {
			ctx: WithOutput<BaseCtx & { input: { headers: { "x-api-key": string; "x-request-id": string } }; readonly errors: { unauthorized: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; validation_error: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError } }, { "application/json": { ok: { accepted: boolean } } }>
			errors: "unauthorized" | "validation_error"
			errorShapes: { unauthorized: null; validation_error: null }
			errorsByStatus: { 400: null; 401: null }
			input: { headers: { "x-api-key": string; "x-request-id": string } }
			meta: {}
			output: { "application/json": { ok: { accepted: boolean } } }
		}
	}
	"/in/cookies": {
		get: {
			ctx: WithOutput<BaseCtx & { input: { cookies: { locale: string; sid: string } }; readonly errors: { unauthorized: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; validation_error: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError } }, { "application/json": { ok: { locale: string; valid: boolean } } }>
			errors: "unauthorized" | "validation_error"
			errorShapes: { unauthorized: null; validation_error: null }
			errorsByStatus: { 400: null; 401: null }
			input: { cookies: { locale: string; sid: string } }
			meta: {}
			output: { "application/json": { ok: { locale: string; valid: boolean } } }
		}
	}
	"/in/params/:orgId/members/:memberId": {
		get: {
			ctx: WithOutput<BaseCtx & { input: { params: { memberId: string; orgId: string } }; readonly params: { orgId: string; memberId: string }; readonly errors: { unauthorized: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; validation_error: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError } }, { "application/json": { ok: { memberId: string; orgId: string } } }>
			errors: "unauthorized" | "validation_error"
			errorShapes: { unauthorized: null; validation_error: null }
			errorsByStatus: { 400: null; 401: null }
			input: { params: { memberId: string; orgId: string } }
			meta: {}
			output: { "application/json": { ok: { memberId: string; orgId: string } } }
		}
	}
	"/in/none": {
		get: {
			ctx: WithOutput<BaseCtx & { readonly errors: { unauthorized: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; validation_error: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError } }, { "application/json": { ok: { ping: "pong" } } }>
			errors: "unauthorized" | "validation_error"
			errorShapes: { unauthorized: null; validation_error: null }
			errorsByStatus: { 400: null; 401: null }
			input: {}
			meta: { operationId: "input.none"; tags: ["input"] }
			output: { "application/json": { ok: { ping: "pong" } } }
		}
	}
	"/in/json-search": {
		post: {
			ctx: WithOutput<BaseCtx & { input: { json: { name: string }; search: { dryRun?: boolean | undefined } }; readonly errors: { unauthorized: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; validation_error: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError } }, { "application/json": { created: { dryRun: boolean; id: string } } }>
			errors: "unauthorized" | "validation_error"
			errorShapes: { unauthorized: null; validation_error: null }
			errorsByStatus: { 400: null; 401: null }
			input: { json: { name: string }; search: { dryRun?: boolean | undefined } }
			meta: {}
			output: { "application/json": { created: { dryRun: boolean; id: string } } }
		}
	}
	"/in/json-headers": {
		post: {
			ctx: WithOutput<BaseCtx & { input: { headers: { "x-idempotency-key": string }; json: { amount: number } }; readonly errors: { unauthorized: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; validation_error: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError } }, { "application/json": { ok: { paymentId: string } } }>
			errors: "unauthorized" | "validation_error"
			errorShapes: { unauthorized: null; validation_error: null }
			errorsByStatus: { 400: null; 401: null }
			input: { headers: { "x-idempotency-key": string }; json: { amount: number } }
			meta: {}
			output: { "application/json": { ok: { paymentId: string } } }
		}
	}
	"/in/json-cookies": {
		post: {
			ctx: WithOutput<BaseCtx & { input: { cookies: { csrf: string }; json: { message: string } }; readonly errors: { unauthorized: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; validation_error: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError } }, { "application/json": { created: { id: string } } }>
			errors: "unauthorized" | "validation_error"
			errorShapes: { unauthorized: null; validation_error: null }
			errorsByStatus: { 400: null; 401: null }
			input: { cookies: { csrf: string }; json: { message: string } }
			meta: {}
			output: { "application/json": { created: { id: string } } }
		}
	}
	"/in/form-headers-cookies": {
		post: {
			ctx: WithOutput<BaseCtx & { input: { cookies: { device: string }; form: { code: string }; headers: { "x-fingerprint": string } }; readonly errors: { unauthorized: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; validation_error: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError } }, { "application/json": { ok: { verified: boolean } } }>
			errors: "unauthorized" | "validation_error"
			errorShapes: { unauthorized: null; validation_error: null }
			errorsByStatus: { 400: null; 401: null }
			input: { cookies: { device: string }; form: { code: string }; headers: { "x-fingerprint": string } }
			meta: {}
			output: { "application/json": { ok: { verified: boolean } } }
		}
	}
	"/in/search-cookies-headers": {
		get: {
			ctx: WithOutput<BaseCtx & { input: { cookies: { timezone: string }; headers: { "accept-language": string }; search: { date: string } }; readonly errors: { unauthorized: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; validation_error: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError } }, { "application/json": { ok: { events: string[] } } }>
			errors: "unauthorized" | "validation_error"
			errorShapes: { unauthorized: null; validation_error: null }
			errorsByStatus: { 400: null; 401: null }
			input: { cookies: { timezone: string }; headers: { "accept-language": string }; search: { date: string } }
			meta: {}
			output: { "application/json": { ok: { events: string[] } } }
		}
	}
	"/in/all/:resourceId": {
		put: {
			ctx: WithOutput<BaseCtx & { input: { headers: { "if-match": string }; json: { data: Partial<Record<string, unknown>> }; search: { force?: boolean | undefined; version: number } }; readonly params: { resourceId: string }; readonly errors: { unauthorized: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; validation_error: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError } }, { "application/json": { ok: { etag: string; version: number } } }>
			errors: "unauthorized" | "validation_error"
			errorShapes: { unauthorized: null; validation_error: null }
			errorsByStatus: { 400: null; 401: null }
			input: { headers: { "if-match": string }; json: { data: Partial<Record<string, unknown>> }; search: { force?: boolean | undefined; version: number } }
			meta: {}
			output: { "application/json": { ok: { etag: string; version: number } } }
		}
	}
	"/out/text": {
		get: {
			ctx: WithOutput<BaseCtx & { readonly errors: { unauthorized: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; validation_error: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError } }, { "text/plain": { ok: string } }>
			errors: "unauthorized" | "validation_error"
			errorShapes: { unauthorized: null; validation_error: null }
			errorsByStatus: { 400: null; 401: null }
			input: {}
			meta: {}
			output: { "text/plain": { ok: string } }
		}
	}
	"/out/html": {
		get: {
			ctx: WithOutput<BaseCtx & { readonly errors: { unauthorized: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; validation_error: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError } }, { "text/html": { ok: string } }>
			errors: "unauthorized" | "validation_error"
			errorShapes: { unauthorized: null; validation_error: null }
			errorsByStatus: { 400: null; 401: null }
			input: {}
			meta: {}
			output: { "text/html": { ok: string } }
		}
	}
	"/out/csv": {
		get: {
			ctx: WithOutput<BaseCtx & { readonly errors: { unauthorized: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; validation_error: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError } }, { "text/csv": { ok: string } }>
			errors: "unauthorized" | "validation_error"
			errorShapes: { unauthorized: null; validation_error: null }
			errorsByStatus: { 400: null; 401: null }
			input: {}
			meta: {}
			output: { "text/csv": { ok: string } }
		}
	}
	"/out/xml": {
		get: {
			ctx: WithOutput<BaseCtx & { readonly errors: { unauthorized: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; validation_error: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError } }, { "application/xml": { ok: string } }>
			errors: "unauthorized" | "validation_error"
			errorShapes: { unauthorized: null; validation_error: null }
			errorsByStatus: { 400: null; 401: null }
			input: {}
			meta: {}
			output: { "application/xml": { ok: string } }
		}
	}
	"/out/binary": {
		get: {
			ctx: WithOutput<BaseCtx & { readonly errors: { unauthorized: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; validation_error: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError } }, { "application/octet-stream": { ok: unknown } }>
			errors: "unauthorized" | "validation_error"
			errorShapes: { unauthorized: null; validation_error: null }
			errorsByStatus: { 400: null; 401: null }
			input: {}
			meta: {}
			output: { "application/octet-stream": { ok: unknown } }
		}
	}
	"/out/sse": {
		get: {
			ctx: WithOutput<BaseCtx & { readonly errors: { unauthorized: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; validation_error: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError } }, { "text/event-stream": { ok: string } }>
			errors: "unauthorized" | "validation_error"
			errorShapes: { unauthorized: null; validation_error: null }
			errorsByStatus: { 400: null; 401: null }
			input: {}
			meta: {}
			output: { "text/event-stream": { ok: string } }
		}
	}
	"/out/multi-status": {
		post: {
			ctx: WithOutput<BaseCtx & { input: { json: { slug: string } }; readonly errors: { conflict: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; unauthorized: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; validation_error: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError } }, { "application/json": { conflict: { existing: string; message: string }; created: { id: string; slug: string } } }>
			errors: "conflict" | "unauthorized" | "validation_error"
			errorShapes: { conflict: null; unauthorized: null; validation_error: null }
			errorsByStatus: { 400: null; 401: null; 409: null }
			input: { json: { slug: string } }
			meta: {}
			output: { "application/json": { conflict: { existing: string; message: string }; created: { id: string; slug: string } } }
		}
	}
	"/out/ok-or-accepted": {
		post: {
			ctx: WithOutput<BaseCtx & { input: { json: { payload: string } }; readonly errors: { unauthorized: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; validation_error: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError } }, { "application/json": { accepted: { eta: number; jobId: string }; ok: { result: string } } }>
			errors: "unauthorized" | "validation_error"
			errorShapes: { unauthorized: null; validation_error: null }
			errorsByStatus: { 400: null; 401: null }
			input: { json: { payload: string } }
			meta: {}
			output: { "application/json": { accepted: { eta: number; jobId: string }; ok: { result: string } } }
		}
	}
	"/out/no-content/:id": {
		delete: {
			ctx: WithOutput<BaseCtx & { readonly params: { id: string }; readonly errors: { not_found: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; unauthorized: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; validation_error: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError } }, {}>
			errors: "not_found" | "unauthorized" | "validation_error"
			errorShapes: { not_found: null; unauthorized: null; validation_error: null }
			errorsByStatus: { 400: null; 401: null; 404: null }
			input: {}
			meta: {}
			output: {}
		}
	}
	"/methods/resource": {
		get: {
			ctx: WithOutput<BaseCtx & { readonly errors: { unauthorized: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; validation_error: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError } }, { "application/json": { ok: { items: string[] } } }>
			errors: "unauthorized" | "validation_error"
			errorShapes: { unauthorized: null; validation_error: null }
			errorsByStatus: { 400: null; 401: null }
			input: {}
			meta: { operationId: "resources.list"; tags: ["methods"] }
			output: { "application/json": { ok: { items: string[] } } }
		}
		post: {
			ctx: WithOutput<BaseCtx & { input: { json: { name: string } }; readonly errors: { unauthorized: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; validation_error: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError } }, { "application/json": { created: { id: string } } }>
			errors: "unauthorized" | "validation_error"
			errorShapes: { unauthorized: null; validation_error: null }
			errorsByStatus: { 400: null; 401: null }
			input: { json: { name: string } }
			meta: { operationId: "resources.create"; tags: ["methods"] }
			output: { "application/json": { created: { id: string } } }
		}
	}
	"/methods/resource/:id": {
		put: {
			ctx: WithOutput<BaseCtx & { input: { json: { name: string }; params: { id: string } }; readonly params: { id: string }; readonly errors: { unauthorized: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; validation_error: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError } }, { "application/json": { ok: { id: string; name: string } } }>
			errors: "unauthorized" | "validation_error"
			errorShapes: { unauthorized: null; validation_error: null }
			errorsByStatus: { 400: null; 401: null }
			input: { json: { name: string }; params: { id: string } }
			meta: { operationId: "resources.update"; tags: ["methods"] }
			output: { "application/json": { ok: { id: string; name: string } } }
		}
		patch: {
			ctx: WithOutput<BaseCtx & { input: { json: { name?: string | undefined }; params: { id: string } }; readonly params: { id: string }; readonly errors: { unauthorized: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; validation_error: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError } }, { "application/json": { ok: { id: string } } }>
			errors: "unauthorized" | "validation_error"
			errorShapes: { unauthorized: null; validation_error: null }
			errorsByStatus: { 400: null; 401: null }
			input: { json: { name?: string | undefined }; params: { id: string } }
			meta: { operationId: "resources.patch"; tags: ["methods"] }
			output: { "application/json": { ok: { id: string } } }
		}
		delete: {
			ctx: WithOutput<BaseCtx & { readonly params: { id: string }; readonly errors: { unauthorized: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; validation_error: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError } }, {}>
			errors: "unauthorized" | "validation_error"
			errorShapes: { unauthorized: null; validation_error: null }
			errorsByStatus: { 400: null; 401: null }
			input: {}
			meta: { operationId: "resources.delete"; tags: ["methods"] }
			output: {}
		}
	}
	"/status/ok": {
		get: {
			ctx: WithOutput<BaseCtx & { readonly errors: { unauthorized: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; validation_error: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError } }, { "application/json": { ok: { v: number } } }>
			errors: "unauthorized" | "validation_error"
			errorShapes: { unauthorized: null; validation_error: null }
			errorsByStatus: { 400: null; 401: null }
			input: {}
			meta: {}
			output: { "application/json": { ok: { v: number } } }
		}
	}
	"/status/created": {
		post: {
			ctx: WithOutput<BaseCtx & { input: { json: { x: string } }; readonly errors: { unauthorized: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; validation_error: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError } }, { "application/json": { created: { id: string } } }>
			errors: "unauthorized" | "validation_error"
			errorShapes: { unauthorized: null; validation_error: null }
			errorsByStatus: { 400: null; 401: null }
			input: { json: { x: string } }
			meta: {}
			output: { "application/json": { created: { id: string } } }
		}
	}
	"/status/accepted": {
		post: {
			ctx: WithOutput<BaseCtx & { input: { json: { task: string } }; readonly errors: { unauthorized: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; validation_error: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError } }, { "application/json": { accepted: { jobId: string } } }>
			errors: "unauthorized" | "validation_error"
			errorShapes: { unauthorized: null; validation_error: null }
			errorsByStatus: { 400: null; 401: null }
			input: { json: { task: string } }
			meta: {}
			output: { "application/json": { accepted: { jobId: string } } }
		}
	}
	"/status/no-content": {
		delete: {
			ctx: WithOutput<BaseCtx & { readonly errors: { unauthorized: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; validation_error: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError } }, {}>
			errors: "unauthorized" | "validation_error"
			errorShapes: { unauthorized: null; validation_error: null }
			errorsByStatus: { 400: null; 401: null }
			input: {}
			meta: {}
			output: {}
		}
	}
	"/stream/events": {
		get: {
			ctx: WithOutput<BaseCtx & { readonly errors: { unauthorized: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; validation_error: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError } }, { "text/event-stream": { ok: string } }>
			errors: "unauthorized" | "validation_error"
			errorShapes: { unauthorized: null; validation_error: null }
			errorsByStatus: { 400: null; 401: null }
			input: {}
			meta: {}
			output: { "text/event-stream": { ok: string } }
		}
	}
	"/stream/filtered": {
		get: {
			ctx: WithOutput<BaseCtx & { input: { search: { channel: string; since?: string | undefined } }; readonly errors: { unauthorized: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; validation_error: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError } }, { "text/event-stream": { ok: string } }>
			errors: "unauthorized" | "validation_error"
			errorShapes: { unauthorized: null; validation_error: null }
			errorsByStatus: { 400: null; 401: null }
			input: { search: { channel: string; since?: string | undefined } }
			meta: {}
			output: { "text/event-stream": { ok: string } }
		}
	}
	"/rs/upload": {
		post: {
			ctx: WithOutput<BaseCtx & { input: { json: { chunks: number; fileName: string } }; readonly errors: { unauthorized: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; validation_error: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError } }, { "application/json": { accepted: { uploadId: string } } }>
			errors: "unauthorized" | "validation_error"
			errorShapes: { unauthorized: null; validation_error: null }
			errorsByStatus: { 400: null; 401: null }
			input: { json: { chunks: number; fileName: string } }
			meta: {}
			output: { "application/json": { accepted: { uploadId: string } } }
		}
	}
	"/rs/form-upload": {
		post: {
			ctx: WithOutput<BaseCtx & { input: { form: { file: string; name: string } }; readonly errors: { unauthorized: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; validation_error: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError } }, { "application/json": { ok: { size: number } } }>
			errors: "unauthorized" | "validation_error"
			errorShapes: { unauthorized: null; validation_error: null }
			errorsByStatus: { 400: null; 401: null }
			input: { form: { file: string; name: string } }
			meta: {}
			output: { "application/json": { ok: { size: number } } }
		}
	}
	"/rs/ingest": {
		post: {
			ctx: WithOutput<BaseCtx & { input: { headers: { "x-pipeline-id": string }; json: { records: number }; search: { batch?: boolean | undefined } }; readonly errors: { unauthorized: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; validation_error: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError } }, { "application/json": { accepted: { eta: number; pipelineId: string } } }>
			errors: "unauthorized" | "validation_error"
			errorShapes: { unauthorized: null; validation_error: null }
			errorsByStatus: { 400: null; 401: null }
			input: { headers: { "x-pipeline-id": string }; json: { records: number }; search: { batch?: boolean | undefined } }
			meta: {}
			output: { "application/json": { accepted: { eta: number; pipelineId: string } } }
		}
	}
	"/openapi.json": {
		get: {
			ctx: WithOutput<BaseCtx & { readonly errors: { unauthorized: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; validation_error: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError } }, {}>
			errors: "unauthorized" | "validation_error"
			errorShapes: { unauthorized: null; validation_error: null }
			errorsByStatus: { 400: null; 401: null }
			input: {}
			meta: {}
			output: {}
		}
	}
	"/openapi.yml": {
		get: {
			ctx: WithOutput<BaseCtx & { readonly errors: { unauthorized: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; validation_error: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError } }, {}>
			errors: "unauthorized" | "validation_error"
			errorShapes: { unauthorized: null; validation_error: null }
			errorsByStatus: { 400: null; 401: null }
			input: {}
			meta: {}
			output: {}
		}
	}
	"/openapi.yaml": {
		get: {
			ctx: WithOutput<BaseCtx & { readonly errors: { unauthorized: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; validation_error: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError } }, {}>
			errors: "unauthorized" | "validation_error"
			errorShapes: { unauthorized: null; validation_error: null }
			errorsByStatus: { 400: null; 401: null }
			input: {}
			meta: {}
			output: {}
		}
	}
	"/docs": {
		get: {
			ctx: WithOutput<BaseCtx & { readonly errors: { unauthorized: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; validation_error: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError } }, {}>
			errors: "unauthorized" | "validation_error"
			errorShapes: { unauthorized: null; validation_error: null }
			errorsByStatus: { 400: null; 401: null }
			input: {}
			meta: {}
			output: {}
		}
	}
	"/manifest.json": {
		get: {
			ctx: WithOutput<BaseCtx & { readonly errors: { unauthorized: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError; validation_error: (opts?: { cause?: unknown; fields?: Record<string, { error_key: string; message: string; path: string }[]>; headers?: Record<string, string>; vars?: Record<string, string | number> }) => HoneyError } }, {}>
			errors: "unauthorized" | "validation_error"
			errorShapes: { unauthorized: null; validation_error: null }
			errorsByStatus: { 400: null; 401: null }
			input: {}
			meta: {}
			output: {}
		}
	}
}

export type RouteCtx<
	TPath extends keyof Routes,
	TMethod extends keyof Routes[TPath] & string
> = Routes[TPath][TMethod] extends { ctx: infer C } ? C : never

export type RouteInput<
	TPath extends keyof Routes,
	TMethod extends keyof Routes[TPath] & string
> = Routes[TPath][TMethod] extends { input: infer I } ? I : never

export type RouteOutput<
	TPath extends keyof Routes,
	TMethod extends keyof Routes[TPath] & string
> = Routes[TPath][TMethod] extends { output: infer O } ? O : never

export type RouteErrors<
	TPath extends keyof Routes,
	TMethod extends keyof Routes[TPath] & string
> = Routes[TPath][TMethod] extends { errors: infer E } ? E : never

export type RouteErrorShapes<
	TPath extends keyof Routes,
	TMethod extends keyof Routes[TPath] & string
> = Routes[TPath][TMethod] extends { errorShapes: infer S } ? S : never

export type RouteErrorsByStatus<
	TPath extends keyof Routes,
	TMethod extends keyof Routes[TPath] & string
> = Routes[TPath][TMethod] extends { errorsByStatus: infer S } ? S : never

export type RouteMeta<
	TPath extends keyof Routes,
	TMethod extends keyof Routes[TPath] & string
> = Routes[TPath][TMethod] extends { meta: infer M } ? M : never
