/* @generated by honey — do not edit. checksum: 27d9d48dcc6b */
import type { TreeNode, RouteHandler, RouteTree } from "honey/tree"

const E = Object.create(null) as Record<string, TreeNode>

const H0: RouteHandler = { bek: null, ef: null, fn: null as unknown as RouteHandler["fn"], mw: [], ek: new Set(), iv: null, os: null, mt: null, ov: null, rp: "" }
const H1: RouteHandler = { bek: null, ef: null, fn: null as unknown as RouteHandler["fn"], mw: [], ek: new Set(), iv: null, os: null, mt: null, ov: null, rp: "" }
const H2: RouteHandler = { bek: null, ef: null, fn: null as unknown as RouteHandler["fn"], mw: [], ek: new Set(), iv: null, os: {"application/json":{"created":{"type":"string"}}} as unknown as RouteHandler["os"], mt: null, ov: null, rp: "" }

export const tree: TreeNode = { s: Object.assign(Object.create(null), { "health": { s: E, d: null, w: null, m: { GET: H0 }, ws: null }, "users": { s: E, d: { n: "id", c: { s: E, d: null, w: null, m: { GET: H1 }, ws: null } }, w: null, m: null, ws: null }, "echo": { s: E, d: null, w: null, m: { POST: H2 }, ws: null } }), d: null, w: null, m: null, ws: null }

export const handlers: Record<string, RouteHandler> = {
	"GET /health": H0,
	"GET /users/:id": H1,
	"POST /echo": H2
}

export type RouteSelector = "GET /health" | "GET /users/:id" | "POST /echo"
export const routeTree: RouteTree = { root: tree, meta: {}, handlers }
