/* @generated by honey — do not edit. checksum: 535cc39071fa */
import type { HoneyContext } from "honey"

export type BaseCtx = HoneyContext<unknown> & { realtime: { publish: (topic: string, data: unknown) => void } }

export type RouteSelector = "GET /health" | "GET /users/:id" | "POST /echo"

declare module "honey" {
	interface HoneyCodegen {
		routeSelector: RouteSelector
	}
}

export type Routes = {
	"/health": {
		get: {
			ctx: BaseCtx
			errors: never
			input: {}
			meta: {}
			output: {}
		}
	}
	"/users/:id": {
		get: {
			ctx: BaseCtx & { readonly params: { id: string } }
			errors: never
			input: {}
			meta: {}
			output: {}
		}
	}
	"/echo": {
		post: {
			ctx: BaseCtx
			errors: never
			input: {}
			meta: {}
			output: { "application/json": { created: string } }
		}
	}
}

export type RouteCtx<
	TPath extends keyof Routes,
	TMethod extends keyof Routes[TPath] & string
> = Routes[TPath][TMethod] extends { ctx: infer C } ? C : never

export type RouteInput<
	TPath extends keyof Routes,
	TMethod extends keyof Routes[TPath] & string
> = Routes[TPath][TMethod] extends { input: infer I } ? I : never

export type RouteOutput<
	TPath extends keyof Routes,
	TMethod extends keyof Routes[TPath] & string
> = Routes[TPath][TMethod] extends { output: infer O } ? O : never

export type RouteErrors<
	TPath extends keyof Routes,
	TMethod extends keyof Routes[TPath] & string
> = Routes[TPath][TMethod] extends { errors: infer E } ? E : never

export type RouteErrorShapes<
	TPath extends keyof Routes,
	TMethod extends keyof Routes[TPath] & string
> = Routes[TPath][TMethod] extends { errorShapes: infer S } ? S : never

export type RouteErrorsByStatus<
	TPath extends keyof Routes,
	TMethod extends keyof Routes[TPath] & string
> = Routes[TPath][TMethod] extends { errorsByStatus: infer S } ? S : never

export type RouteMeta<
	TPath extends keyof Routes,
	TMethod extends keyof Routes[TPath] & string
> = Routes[TPath][TMethod] extends { meta: infer M } ? M : never
