// Code generated by honey. DO NOT EDIT.
package cli

import "errors"

// ErrMissingAPIKey is returned when no API key can be found via flags, env, or config file.
var ErrMissingAPIKey = errors.New("api key required: set --api-key, env var, or config file")

// ResolveAPIKey returns the resolved API key or ErrMissingAPIKey if none is available.
func ResolveAPIKey(cfg Config) (string, error) {
	if cfg.APIKey != "" {
		return cfg.APIKey, nil
	}
	return "", ErrMissingAPIKey
}
