// Code generated by honey. DO NOT EDIT.
package cli

import (
	"fmt"
	"io"
	"os"
	"path/filepath"

	"github.com/pelletier/go-toml/v2"
	"github.com/spf13/pflag"
)

// Config holds resolved runtime values for the CLI binary.
//
// Precedence (high → low) — see LoadConfig below:
//
//  1. --api-key / --base-url / --output / … flag set on the command line.
//  2. Env var: <ENV_PREFIX>_API_KEY / _BASE_URL / _OUTPUT / …
//  3. Config file from --config, $<ENV_PREFIX>_CONFIG, $XDG_CONFIG_HOME/<name>/config.toml,
//     $HOME/.config/<name>/config.toml, os.UserConfigDir()/<name>/config.toml.
//  4. Built-in defaults.
//  5. (missing api-key → ErrMissingAPIKey, mapped to exit 4).
type Config struct {
	APIKey     string
	BaseURL    string
	Output     string
	Timeout    string
	Verbose    bool
	ConfigPath string
}

type tomlConfig struct {
	APIKey  string `toml:"api_key"`
	BaseURL string `toml:"base_url"`
	Output  string `toml:"output"`
	Timeout string `toml:"timeout"`
}

// LoadConfig merges flag values, env vars, and a TOML config file into a Config.
//
// The resolution order matches the Config doc-comment precedence list.
func LoadConfig(flags *pflag.FlagSet, envPrefix, configName string) (Config, error) {
	var cfg Config

	cfgPath := ""
	if flags.Changed("config") {
		v, _ := flags.GetString("config")
		cfgPath = v
	} else if v := os.Getenv(envPrefix + "_CONFIG"); v != "" {
		cfgPath = v
	} else {
		cfgPath = defaultConfigPath(configName)
	}

	var fromFile tomlConfig
	if cfgPath != "" {
		if data, err := os.ReadFile(cfgPath); err == nil {
			if err := toml.Unmarshal(data, &fromFile); err != nil {
				return cfg, fmt.Errorf("parse config %s: %w", cfgPath, err)
			}
		}
	}
	cfg.ConfigPath = cfgPath

	cfg.APIKey = fromFile.APIKey
	if v := os.Getenv(envPrefix + "_API_KEY"); v != "" {
		cfg.APIKey = v
	}
	if flags.Changed("api-key") {
		v, _ := flags.GetString("api-key")
		cfg.APIKey = v
	}

	cfg.BaseURL = fromFile.BaseURL
	if v := os.Getenv(envPrefix + "_BASE_URL"); v != "" {
		cfg.BaseURL = v
	}
	if flags.Changed("base-url") {
		v, _ := flags.GetString("base-url")
		cfg.BaseURL = v
	}

	cfg.Output = fromFile.Output
	if v := os.Getenv(envPrefix + "_OUTPUT"); v != "" {
		cfg.Output = v
	}
	if flags.Changed("output") {
		v, _ := flags.GetString("output")
		cfg.Output = v
	}
	if cfg.Output == "" {
		cfg.Output = "json"
	}

	cfg.Timeout = fromFile.Timeout
	if v := os.Getenv(envPrefix + "_TIMEOUT"); v != "" {
		cfg.Timeout = v
	}
	if flags.Changed("timeout") {
		v, _ := flags.GetString("timeout")
		cfg.Timeout = v
	}
	if cfg.Timeout == "" {
		cfg.Timeout = "30s"
	}

	if flags.Changed("verbose") {
		v, _ := flags.GetBool("verbose")
		cfg.Verbose = v
	}

	return cfg, nil
}

func defaultConfigPath(configName string) string {
	if configName == "" {
		return ""
	}
	if xdg := os.Getenv("XDG_CONFIG_HOME"); xdg != "" {
		return filepath.Join(xdg, configName, "config.toml")
	}
	if home := os.Getenv("HOME"); home != "" {
		return filepath.Join(home, ".config", configName, "config.toml")
	}
	if dir, err := os.UserConfigDir(); err == nil {
		return filepath.Join(dir, configName, "config.toml")
	}
	return ""
}

// readDataFlag resolves the value of a --data flag into raw bytes.
//
// Rules:
//   - "@path"        → reads file at path.
//   - "-"            → reads os.Stdin.
//   - ""             → returns nil, nil (caller decides whether required).
//   - anything else  → treats val as literal JSON.
//
// Exported as ReadDataFlag for use from cmd/*.go.
func ReadDataFlag(val string) ([]byte, error) {
	return readDataFlag(val)
}

func readDataFlag(val string) ([]byte, error) {
	if val == "" {
		return nil, nil
	}
	if val == "-" {
		data, err := io.ReadAll(os.Stdin)
		if err != nil {
			return nil, fmt.Errorf("read stdin: %w", err)
		}
		return data, nil
	}
	if val[0] == '@' {
		path := val[1:]
		data, err := os.ReadFile(path)
		if err != nil {
			return nil, fmt.Errorf("read data file %s: %w", path, err)
		}
		return data, nil
	}
	return []byte(val), nil
}
