// Code generated by honey. DO NOT EDIT.
package cli

import (
	"context"
	"errors"
	"net"
)

// ExitFor maps a CLI-level error to a process exit code.
//
// Codes:
//
//	0  success
//	1  4xx client error (status < 500)
//	2  5xx server error (status >= 500)
//	3  network / transport failure or status == 0
//	4  bad flags / bad config / missing api key
//	5  3xx unexpected redirect
func ExitFor(err error) int {
	if err == nil {
		return 0
	}
	if errors.Is(err, ErrMissingAPIKey) {
		return 4
	}
	if errors.Is(err, context.DeadlineExceeded) || errors.Is(err, context.Canceled) {
		return 3
	}

	var netErr net.Error
	if errors.As(err, &netErr) {
		return 3
	}

	var apiErr interface{ StatusCode() int }
	if errors.As(err, &apiErr) {
		return exitForStatus(apiErr.StatusCode())
	}

	return 3
}

func exitForStatus(status int) int {
	switch {
	case status == 0:
		return 3
	case status >= 300 && status < 400:
		return 5
	case status >= 400 && status < 500:
		return 1
	case status >= 500 && status < 600:
		return 2
	default:
		return 1
	}
}
