// Code generated by honey. DO NOT EDIT.
package cli

import (
	"context"
	"errors"
	"net"
)

// UsageError marks bad flags, bad config and invalid input; it maps to exit 4.
type UsageError struct{ Err error }

func (e *UsageError) Error() string { return e.Err.Error() }
func (e *UsageError) Unwrap() error { return e.Err }

// Usage wraps err as a UsageError.
func Usage(err error) error {
	if err == nil {
		return nil
	}
	return &UsageError{Err: err}
}

// ExitFor maps a CLI-level error to a process exit code.
//
// Codes:
//
//	0  success
//	1  4xx client error
//	2  5xx server error
//	3  network / transport failure or timeout
//	4  bad flags / bad config / missing api key
//	5  3xx unexpected redirect
func ExitFor(err error) int {
	if err == nil {
		return 0
	}
	if errors.Is(err, ErrMissingAPIKey) {
		return 4
	}
	var usage *UsageError
	if errors.As(err, &usage) {
		return 4
	}

	/* SDK errors expose Status() (APIError) */
	var apiErr interface{ Status() int }
	if errors.As(err, &apiErr) {
		return exitForStatus(apiErr.Status())
	}

	if errors.Is(err, context.DeadlineExceeded) || errors.Is(err, context.Canceled) {
		return 3
	}
	var netErr net.Error
	if errors.As(err, &netErr) {
		return 3
	}
	return 3
}

func exitForStatus(status int) int {
	switch {
	case status == 0:
		return 3
	case status >= 300 && status < 400:
		return 5
	case status >= 400 && status < 500:
		return 1
	case status >= 500 && status < 600:
		return 2
	default:
		return 1
	}
}
