// Code generated by honey. DO NOT EDIT.
package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"sort"
	"strings"
	"text/tabwriter"

	"sigs.k8s.io/yaml"
)

// Emit writes data to w in the requested mode.
//
// Supported modes: json (pretty, 2-space indent), ndjson, yaml, table.
// Unknown modes return an error that ExitFor maps to exit code 4.
func Emit(data any, mode string, w io.Writer) error {
	if data == nil {
		return nil
	}
	switch mode {
	case "", "json":
		enc, err := json.MarshalIndent(data, "", "  ")
		if err != nil {
			return err
		}
		_, err = fmt.Fprintln(w, string(enc))
		return err
	case "ndjson":
		enc, err := json.Marshal(data)
		if err != nil {
			return err
		}
		_, err = fmt.Fprintln(w, string(enc))
		return err
	case "yaml":
		enc, err := yaml.Marshal(data)
		if err != nil {
			return err
		}
		_, err = w.Write(enc)
		return err
	case "table":
		return printTable(data, w)
	default:
		return fmt.Errorf("unknown output mode %q: valid modes are json, ndjson, yaml, table", mode)
	}
}

// printTable renders data as an aligned table when possible, or falls back to raw print.
func printTable(data any, w io.Writer) error {
	switch v := data.(type) {
	case []any:
		if len(v) == 0 {
			return nil
		}
		rows := make([]map[string]any, 0, len(v))
		for _, row := range v {
			if m, ok := row.(map[string]any); ok {
				rows = append(rows, m)
			} else {
				fmt.Fprintln(w, row)
				return nil
			}
		}
		keys := collectKeys(rows)
		tw := tabwriter.NewWriter(w, 0, 0, 2, ' ', 0)
		fmt.Fprintln(tw, strings.Join(keys, "\t"))
		for _, row := range rows {
			cols := make([]string, len(keys))
			for i, k := range keys {
				cols[i] = fmt.Sprintf("%v", row[k])
			}
			fmt.Fprintln(tw, strings.Join(cols, "\t"))
		}
		return tw.Flush()
	case map[string]any:
		keys := make([]string, 0, len(v))
		for k := range v {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		tw := tabwriter.NewWriter(w, 0, 0, 2, ' ', 0)
		for _, k := range keys {
			fmt.Fprintf(tw, "%s\t%v\n", k, v[k])
		}
		return tw.Flush()
	default:
		_, err := fmt.Fprintln(w, data)
		return err
	}
}

func collectKeys(rows []map[string]any) []string {
	seen := map[string]bool{}
	keys := []string{}
	for _, row := range rows {
		for k := range row {
			if !seen[k] {
				seen[k] = true
				keys = append(keys, k)
			}
		}
	}
	sort.Strings(keys)
	return keys
}
