// Code generated by honey. DO NOT EDIT.
package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"iter"
	"os"

	"sigs.k8s.io/yaml"
)

// SSEEvent is the concrete SSE event type consumed by StreamSSE. The CLI's
// generated cmd/*.go files wrap the SDK's iterator into a Seq2[SSEEvent, error]
// before passing it in, so this runtime stays SDK-agnostic. Go generics do not
// support struct-field access through a type parameter, so this is a plain
// concrete struct rather than a constrained generic.
type SSEEvent struct {
	Data  string
	Event string
	ID    string
	Retry int
}

// streamEvent is the on-wire shape that gets emitted for each SSE event.
type streamEvent struct {
	Event string          `json:"event,omitempty"`
	ID    string          `json:"id,omitempty"`
	Data  json.RawMessage `json:"data"`
	Retry int             `json:"retry,omitempty"`
}

// StreamSSE consumes an iter.Seq2 of SSE events and writes them to w.
//
// --output modes:
//
//	ndjson (default for streams) → one JSON object per line.
//	yaml                         → YAML documents separated by "---\n".
//	table                        → falls back to ndjson; prints a warning to os.Stderr.
//	json                         → treated as ndjson (no way to represent a live stream as one object).
func StreamSSE(it iter.Seq2[SSEEvent, error], w io.Writer, mode string) error {
	if mode == "table" {
		fmt.Fprintln(os.Stderr, "warning: --output=table is not supported for streaming endpoints; falling back to ndjson")
		mode = "ndjson"
	}
	for ev, err := range it {
		if err != nil {
			return err
		}
		out := streamEvent{
			Event: ev.Event,
			ID:    ev.ID,
			Retry: ev.Retry,
		}
		if ev.Data == "" {
			out.Data = json.RawMessage("null")
		} else if json.Valid([]byte(ev.Data)) {
			out.Data = json.RawMessage(ev.Data)
		} else {
			enc, _ := json.Marshal(ev.Data)
			out.Data = enc
		}

		switch mode {
		case "yaml":
			enc, err := yaml.Marshal(out)
			if err != nil {
				return err
			}
			if _, err := w.Write(enc); err != nil {
				return err
			}
			if _, err := fmt.Fprint(w, "---\n"); err != nil {
				return err
			}
		default:
			enc, err := json.Marshal(out)
			if err != nil {
				return err
			}
			if _, err := fmt.Fprintln(w, string(enc)); err != nil {
				return err
			}
		}
	}
	return nil
}
