/* @generated by honey — do not edit. checksum: 1f4fdfb609f7 */
import type { TreeNode, RouteHandler, RouteTree } from "@lovrozagar/honey/tree"

const E = Object.create(null) as Record<string, TreeNode>
function N(s: Record<string, TreeNode>, m: Record<string, RouteHandler> | null = null, d: TreeNode["d"] = null, w: { n: string; m: Record<string, RouteHandler> } | null = null): TreeNode {
	return { s, d, w: w as TreeNode["w"], m: m as TreeNode["m"], ws: null }
}
function S(o: Record<string, TreeNode>): Record<string, TreeNode> {
	return Object.assign(Object.create(null), o) as Record<string, TreeNode>
}
const FN = null as unknown as RouteHandler["fn"]

const T0 = "api_error"
const T1 = "unauthorized"
const T2 = "invalid_input"
const P0 = "GET /api"
const P1 = "GET /api/health"
const P2 = "GET /api/events"
const P3 = "GET /api/events-live"
const P4 = "ALL /api/echo"
const P5 = "GET /api/v1/organizations"
const T3 = "org_limit_reached"
const P6 = "POST /api/v1/organizations"
const P7 = "GET /api/v1/organizations/:orgId"
const P8 = "DELETE /api/v1/organizations/:orgId"
const P9 = "POST /api/realtime/broadcast/:topic"
const P10 = "GET /api/boundary/default"
const P11 = "GET /api/boundary/custom"
const P12 = "GET /api/openapi.json"
const P13 = "GET /api/openapi.yml"
const P14 = "GET /api/openapi.yaml"
const P15 = "GET /api/docs"
const P16 = "GET /api/manifest.json"
const P17 = "GET /api/generated-tree"
const J1 = {"type":"string"}
const A0 = ["id"]
const A1 = [T1,T0]
const J0 = {"id":J1}
const M0 = {"description":"Test route","summary":"Root test route","tags":["test"]} as unknown as MetaShape
const I0 = {"search":{"type":"object","properties":J0,"required":A0}} as unknown as RouteHandler["iv"]
const O0 = {"application/json":{"ok":{"type":"object","properties":J0,"required":A0,"additionalProperties":false}}} as unknown as RouteHandler["os"]

const H0: RouteHandler = { bek: T0, fn: FN, mw: [], ek: new Set([T1,T0,T2]), iv: I0, os: O0, mt: M0 }
const H1: RouteHandler = { bek: T0, fn: FN, mw: [], ek: new Set(A1), iv: null, os: null, mt: null }
const H2: RouteHandler = { bek: T0, fn: FN, mw: [], ek: new Set(A1), iv: null, os: null, mt: null }
const H3: RouteHandler = { bek: T0, fn: FN, mw: [], ek: new Set(A1), iv: null, os: null, mt: null }
const H4: RouteHandler = { bek: T0, fn: FN, mw: [], ek: new Set(A1), iv: null, os: null, mt: null }
const H5: RouteHandler = { bek: T0, fn: FN, mw: [], ek: new Set(A1), iv: null, os: null, mt: null }
const H6: RouteHandler = { bek: T0, fn: FN, mw: [], ek: new Set([T1,T0,"org_slug_taken",T3,T2]), iv: null, os: null, mt: null }
const H7: RouteHandler = { bek: T0, fn: FN, mw: [], ek: new Set(A1), iv: null, os: null, mt: null }
const H8: RouteHandler = { bek: T0, fn: FN, mw: [], ek: new Set(A1), iv: null, os: null, mt: null }
const H9: RouteHandler = { bek: T0, fn: FN, mw: [], ek: new Set(A1), iv: null, os: null, mt: null }
const H10: RouteHandler = { bek: T0, fn: FN, mw: [], ek: new Set(A1), iv: null, os: null, mt: null }
const H11: RouteHandler = { bek: T3, fn: FN, mw: [], ek: new Set([T1,T0,T3]), iv: null, os: null, mt: null }
const H12: RouteHandler = { bek: T0, fn: FN, mw: [], ek: new Set(A1), iv: null, os: null, mt: null }
const H13: RouteHandler = { bek: T0, fn: FN, mw: [], ek: new Set(A1), iv: null, os: null, mt: null }
const H14: RouteHandler = { bek: T0, fn: FN, mw: [], ek: new Set(A1), iv: null, os: null, mt: null }
const H15: RouteHandler = { bek: T0, fn: FN, mw: [], ek: new Set(A1), iv: null, os: null, mt: null }
const H16: RouteHandler = { bek: T0, fn: FN, mw: [], ek: new Set(A1), iv: null, os: null, mt: null }
const H17: RouteHandler = { bek: T0, fn: FN, mw: [], ek: new Set(A1), iv: null, os: null, mt: null }

export const tree: TreeNode = N(S({ "api": N(S({ "health": N(E, { GET: H1 }), "events": N(E, { GET: H2 }), "events-live": N(E, { GET: H3 }), "echo": N(E, { ALL: H4 }), "v1": N(S({ "organizations": N(E, { GET: H5, POST: H6 }, { n: "orgId", c: N(E, { GET: H7, DELETE: H8 }) }) })), "realtime": N(S({ "broadcast": N(E, null, { n: "topic", c: N(E, { POST: H9 }) }) })), "boundary": N(S({ "default": N(E, { GET: H10 }), "custom": N(E, { GET: H11 }) })), "openapi.json": N(E, { GET: H12 }), "openapi.yml": N(E, { GET: H13 }), "openapi.yaml": N(E, { GET: H14 }), "docs": N(E, { GET: H15 }), "manifest.json": N(E, { GET: H16 }), "generated-tree": N(E, { GET: H17 }) }), { GET: H0 }) }))

export const handlers: Record<string, RouteHandler> = {
	[P0]: H0,
	[P1]: H1,
	[P2]: H2,
	[P3]: H3,
	[P4]: H4,
	[P5]: H5,
	[P6]: H6,
	[P7]: H7,
	[P8]: H8,
	[P9]: H9,
	[P10]: H10,
	[P11]: H11,
	[P12]: H12,
	[P13]: H13,
	[P14]: H14,
	[P15]: H15,
	[P16]: H16,
	[P17]: H17
}

export type MetaShape = {
	description: "Test route"
	summary: "Root test route"
	tags: ["test"]
} & Record<string, unknown>


export type RouteSelector = typeof P4 | typeof P8 | typeof P0 | typeof P11 | typeof P10 | typeof P2 | typeof P3 | typeof P17 | typeof P1 | typeof P5 | typeof P7 | typeof P9 | typeof P6
export const meta: Record<string, MetaShape> = {
	[P0]: M0
}
export const routeTree: RouteTree = { root: tree, meta, handlers }
