/* @generated by honey — do not edit. checksum: 4fecffec785a */
import { assembleRouteTree, type PackedRouteTable, type RouteHandler, type RouteTree, type TreeNode } from "@lovrozagar/honey/tree"

declare const P: readonly ["GET /api","GET /api/health","GET /api/events","GET /api/events-live","ALL /api/echo","GET /api/v1/organizations","POST /api/v1/organizations","GET /api/v1/organizations/:orgId","DELETE /api/v1/organizations/:orgId","POST /api/realtime/broadcast/:topic","GET /api/boundary/default","GET /api/boundary/custom","GET /api/openapi.json","GET /api/openapi.yml","GET /api/openapi.yaml","GET /api/docs","GET /api/manifest.json","GET /api/generated-tree"]
const D: PackedRouteTable = {"s":["GET /api","GET /api/health","GET /api/events","GET /api/events-live","ALL /api/echo","GET /api/v1/organizations","POST /api/v1/organizations","GET /api/v1/organizations/:orgId","DELETE /api/v1/organizations/:orgId","POST /api/realtime/broadcast/:topic","GET /api/boundary/default","GET /api/boundary/custom","GET /api/openapi.json","GET /api/openapi.yml","GET /api/openapi.yaml","GET /api/docs","GET /api/manifest.json","GET /api/generated-tree"],"b":["api_error","api_error","api_error","api_error","api_error","api_error","api_error","api_error","api_error","api_error","api_error","org_limit_reached","api_error","api_error","api_error","api_error","api_error","api_error"],"k":["unauthorized","api_error"],"e":[["invalid_input"],[],[],[],[],[],["org_slug_taken","org_limit_reached","invalid_input"],[],[],[],[],["org_limit_reached"],[],[],[],[],[],[]],"i":{"t":[{"q":{"t":"o","p":{"id":{"t":"s"}},"r":["id"]}},null],"x":[0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]},"o":{"t":[{"j":{"ok":{"t":"o","p":{"id":{"t":"s"}},"r":["id"],"ap":false}}},null],"x":[0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]},"m":{"t":[{"description":"Test route","summary":"Root test route","tags":["test"]},null],"x":[0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]}}
export const routeTree: RouteTree = assembleRouteTree(D)
export const tree: TreeNode = routeTree.root
export const handlers: Record<string, RouteHandler> = routeTree.handlers ?? {}

export type MetaShape = {
	description: "Test route"
	summary: "Root test route"
	tags: ["test"]
} & Record<string, unknown>

export type RouteSelector = typeof P[0] | typeof P[1] | typeof P[2] | typeof P[3] | typeof P[4] | typeof P[5] | typeof P[6] | typeof P[7] | typeof P[8] | typeof P[9] | typeof P[10] | typeof P[11] | typeof P[17]
export const meta: Record<string, MetaShape> = routeTree.meta as Record<string, MetaShape>
