/* @generated by honey — do not edit. checksum: 12e4f0eeace3 */
import type { RouteTree, TreeNode } from "@lovrozagar/honey/tree"

function S<T>(o: Record<string, T>): Record<string, T> {
	return Object.assign(Object.create(null) as Record<string, T>, o)
}
function N(s: Record<string, TreeNode> = S({}), m: Record<string, string> | null = null, d: TreeNode["d"] = null, w: TreeNode["w"] = null, ws: string | null = null): TreeNode {
	return { d, m, s, w, ws }
}

const T0 = "api_error"
const T1 = "unauthorized"
const T2 = "invalid_input"
const P0 = "GET /api"
const P1 = "GET /api/health"
const P2 = "GET /api/events"
const P3 = "GET /api/events-live"
const P4 = "ALL /api/echo"
const P5 = "GET /api/v1/organizations"
const T3 = "org_limit_reached"
const P6 = "POST /api/v1/organizations"
const P7 = "GET /api/v1/organizations/:orgId"
const P8 = "DELETE /api/v1/organizations/:orgId"
const P9 = "WS /api/v1/socket"
const P10 = "WS /api/echo-ws"
const P11 = "WS /api/reconnect-ws"
const P12 = "WS /api/realtime/echo"
const P13 = "WS /api/realtime/chat/:roomId"
const P14 = "POST /api/realtime/broadcast/:topic"
const P15 = "GET /api/boundary/default"
const P16 = "GET /api/boundary/custom"
const P17 = "GET /api/generated-tree"
const A0 = [T1,T0]
const M0 = {"description":"Test route","summary":"Root test route","tags":["test"]} as unknown as MetaShape

export const tree: TreeNode = N(S({ "api": N(S({ "health": N(undefined, S({ "GET": P1 })), "events": N(undefined, S({ "GET": P2 })), "events-live": N(undefined, S({ "GET": P3 })), "echo": N(undefined, S({ "ALL": P4 })), "v1": N(S({ "organizations": N(undefined, S({ "GET": P5, "POST": P6 }), { n: "orgId", c: N(undefined, S({ "GET": P7, "DELETE": P8 })) }), "socket": N(undefined, null, null, null, P9) })), "echo-ws": N(undefined, null, null, null, P10), "reconnect-ws": N(undefined, null, null, null, P11), "realtime": N(S({ "echo": N(undefined, null, null, null, P12), "chat": N(undefined, null, { n: "roomId", c: N(undefined, null, null, null, P13) }), "broadcast": N(undefined, null, { n: "topic", c: N(undefined, S({ "POST": P14 })) }) })), "boundary": N(S({ "default": N(undefined, S({ "GET": P15 })), "custom": N(undefined, S({ "GET": P16 })) })), "generated-tree": N(undefined, S({ "GET": P17 })) }), S({ "GET": P0 })) }))

export const routes: RouteTree["routes"] = S({
	[P0]: { bek: T0, ek: [T1,T0,T2], mt: M0 },
	[P1]: { bek: T0, ek: A0 },
	[P2]: { bek: T0, ek: A0 },
	[P3]: { bek: T0, ek: A0 },
	[P4]: { bek: T0, ek: A0 },
	[P5]: { bek: T0, ek: A0 },
	[P6]: { bek: T0, ek: [T1,T0,"org_slug_taken",T3,T2] },
	[P7]: { bek: T0, ek: A0 },
	[P8]: { bek: T0, ek: A0 },
	[P9]: { bek: T0, ek: A0 },
	[P10]: { bek: T0, ek: A0 },
	[P11]: { bek: T0, ek: A0 },
	[P12]: { bek: T0, ek: A0 },
	[P13]: { bek: T0, ek: A0 },
	[P14]: { bek: T0, ek: A0 },
	[P15]: { bek: T0, ek: A0 },
	[P16]: { bek: T3, ek: [T1,T0,T3] },
	[P17]: { bek: T0, ek: A0 }
})

export type MetaShape = {
	description: "Test route"
	summary: "Root test route"
	tags: ["test"]
} & Record<string, unknown>


export type RouteSelector = typeof P4 | typeof P8 | typeof P0 | typeof P16 | typeof P15 | typeof P2 | typeof P3 | typeof P17 | typeof P1 | typeof P5 | typeof P7 | typeof P14 | typeof P6
export const meta: Record<string, MetaShape> = S({
	[P0]: M0
})
export const routeTree: RouteTree = { v: 2, root: tree, routes, meta }
